### ISSUE TITLE
Add to homescreen icon showing blank in iphone(apple-touch-icon)

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#113]
Help Scout Link: https://secure.helpscout.net/conversation/842910342/64467?folderId=2770545

As  Per Safari Web Content Guide image size in PWA are

<link rel="apple-touch-icon" sizes="152x152" href="touch-icon-ipad.png">
<link rel="apple-touch-icon" sizes="180x180" href="touch-icon-iphone-retina.png">
<link rel="apple-touch-icon" sizes="167x167" href="touch-icon-ipad-retina.png">

In our Plugin Image sizes(apple-touch-icon) are 192x192 and 512x512

**Comment by ajeetku** [comment]
Pushed in Version 1.4
