### ISSUE TITLE
UTM tracking issue in PWA

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#114]
Ref Article: https://medium.com/dev-channel/tracking-pwa-events-with-google-analytics-3b50030d8922

Help Scout Link: https://secure.helpscout.net/conversation/845239923/64796?folderId=2770545

**Comment by akashagrjsr** [comment]
In Offline Google Analytics option where it is tracking the analytics id if the AMP support is off.
Screenshot: https://monosnap.com/file/MkWOozHPjRMuUITNLoO0Dn6Z8KvSHr

**Comment by ahmedkaludi** [comment]
MY CONCLUSION: 

Properly test it
