### ISSUE TITLE
Add to Homescreen Bar | Not Working

### ISSUE THREAD

**Issue by andrewkoski** [ahmedkaludi/pwa-for-wp#115]
Alright, I can't get it going. It was working for a little bit, but then stopped.
Please reference https://andrewkoski.com.

![Screenshot_20190510-170001](https://user-images.githubusercontent.com/13125986/57562124-20b23b80-7345-11e9-984b-3102d888d22d.png)

**Comment by ahmedkaludi** [comment]
kindly ask for the support on http://pwa-for-wp.com/contact-us/
