### ISSUE TITLE
Home url issue

### ISSUE THREAD

**Issue by soktherat** [ahmedkaludi/pwa-for-wp#126]
Replace all home_url/get_home_url with site_url/get_site_url.

For compatibility with WPML & others, eg. https://example.com/en/pwa-register-sw.js not exists.

**Comment by Sanjeevsetu** [comment]
Hi @soktherat, 

Do you have multisite? after changing the url does it work for you? if not could you please contact us here http://pwa-for-wp.com/contact-us/. We will make it proper compatible with WPML

**Comment by ahmedkaludi** [comment]
@soktherat Can you please help us see this issue?

**Comment by soktherat** [comment]
Issue exists when WPML is used in "Different languages in directories" mode - home_url is changed to https://example.com/en/ or https://example.com/directory/en/ (for wp in directory installation).

For links to files in root directory (https://example.com/pwa-manifest.json or https://example.com/directory/pwa-manifest.json) we have to use site_url - it's not modified by WPML.

Necessary changes:
1. in common-function.php in function pwaforwp_front_url()
2. in class-service-worker.php in fuction pwaforwp_service_worker_non_amp() - use pwaforwp_front_url()
3. in class-file-creation.php in function pwaforwp_swr() - $ServiceWorkerfileName can use pwaforwp_front_url()
4. in class-file-creation.php in function pwaforwp_manifest() - $scope_url can use pwaforwp_front_url()

Scope in manifest have to be https://example.com/ for app to work with all languages.
Start_url can be home_url - I had some fetch errors when was set to site_url - ideally it should be set to user language but it's not possible for one time generated manifest file, so default language is fine.

I haven't tested AMP or multisite.

Thank You for this plugin and your work :)

**Comment by ahmedkaludi** [comment]
Thanks for the amazing explanation. We will fix this in our next update.
