### ISSUE TITLE
PWA for WordPress "Serious issues: Media error: Format(s) not supported or source(s) not found"

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#136]
Help Scout Link: https://secure.helpscout.net/conversation/879511016/70765?folderId=2770545

**Comment by alexlii1971** [comment]
Hello @akashagrjsr 

This info might be helpful to resovle this issue:

https://philna.sh/blog/2018/10/23/service-workers-beware-safaris-range-request/
https://github.com/philnash/philna.sh/blob/ba798a2d5d8364fc7c1dae1819cbd8ef103c8b67/sw.js#L50-L94

would you please have a check?

**Comment by ajeetku** [comment]
Discussion  with user

**Comment by ajeetku** [comment]
Video streaming fixed & pushed in version 1.5
