### ISSUE TITLE
If CDN compatiblity is enabled, Layout of the website is broken

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#140]
Help Scout Link: https://secure.helpscout.net/conversation/888459427/71795?folderId=2770545

**Comment by akashagrjsr** [comment]
this issue is still in amp version. https://secure.helpscout.net/conversation/898939825/73206?folderId=1060551

**Comment by Sanjeevsetu** [comment]
ref: https://secure.helpscout.net/conversation/897413159/72970?folderId=2632028
