### ISSUE TITLE
Showing "//" when adding to home screen in Firefox browser

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/pwa-for-wp#147]
Showing "//" after the domain name when adding to the home screen in Firefox browser but working fine
Ref:
 https://secure.helpscout.net/conversation/901067984/73515?folderId=3081347

![photo_2019-07-11_18-44-16](https://user-images.githubusercontent.com/44563327/61111203-ac138e80-a4a6-11e9-86ef-3ad658a2d581.jpg)

**Comment by ajeetku** [comment]
Merge & pushed in 1.4
