### ISSUE TITLE
Need to add feature to add custom startpage url

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#148]
Help Scout Link: https://secure.helpscout.net/conversation/901971315/73608/

Need to add a feature where we can select startup page in our app
not all of the website owner wants to their app start with the main page of the site.

**Comment by ajotka** [comment]
I need it too. Thanks for reporting :+1:

**Comment by ahmedkaludi** [comment]
Development will be continued on #153
