### ISSUE TITLE
Need to serve required files from upload directory

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#149]
Ref: https://secure.helpscout.net/conversation/901825927/73575?folderId=2770545

Issue: Users are not allowed to write files in the root folder, In this case, we need to create FILE in the upload folder and serve it to users(manifest.json,service-worker.js, etc.), User is not getting notice of download files.

Suggestion: We can write rewrite rules to serve files from the upload folder. This rewrite rule is in a way of Wordpress.

**Comment by ahmedkaludi** [comment]
This would be a setting in Advanced options called "Delivery method" where this would be an alternative option for people who are unable to get working as a normal way.

**Comment by ajeetku** [comment]
Pushed in version 1.4
