### ISSUE TITLE
Landscape orientation is not working in PWA correctly

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#151]
Ref: https://secure.helpscout.net/conversation/905612882/74357?folderId=2770545

**Comment by akashagrjsr** [comment]
One more user: https://secure.helpscout.net/conversation/911076794/75230?folderId=2770545

PWA does not rotate the screen to be more friendly with the video/player. It should rotate the screen according to the mobile device.

**Comment by ajeetku** [comment]
Pushed in version 1.4
