### ISSUE TITLE
Add the caching strategists documentation 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/pwa-for-wp#152]
https://trello.com/c/CG6sXlS5/448-what-is-caching-strategies-in-pwa-and-how-to-use-it

**Comment by ahmedkaludi** [comment]
https://pwa-for-wp.com/docs/article/what-is-caching-strategies-in-pwa-and-how-to-use-it/

**Comment by ajeetku** [comment]
1c3f339
