### ISSUE TITLE
Manifest not working when Best Preloader plugin is active.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/pwa-for-wp#155]
Manifest not working when Best Preloader plugin is active.
Ref: https://secure.helpscout.net/conversation/914274498/76633?folderId=2322652

**Comment by Sanjeevsetu** [comment]
This bug is in Best Preloader plugin. They have used div inside wp_head which cause problem.

https://wordpress.org/support/topic/do-not-use-div-tag-inside-wp_head/
