### ISSUE TITLE
when WordPress Address (URL) and Site Address (URL) is different service worker is not working

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/pwa-for-wp#160]
error:  "The path of the provided scope ('/') is not under the max scope allowed ('/vz01pro1/'). Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope."

Ref: https://secure.helpscout.net/conversation/921038183/77456?folderId=2632030

https://monosnap.com/file/o6YjdGJ73JyvyLDOudDUTfDjwqGmBJ

**Comment by ajeetku** [comment]
Resolved in Version: 1.3
