### ISSUE TITLE
Range request for video files

### ISSUE THREAD

**Issue by BremzeLV** [ahmedkaludi/pwa-for-wp#162]
Hey, when I activate this plugin then in WordPress my videos are not showing in IOS(Safari) devices and FV player is responding with error "Video file is not found".
Native WP video player and any other video player are not working too.

On IOS when starting the video there is empty response with no data.

When I disable this plugin, and clear safari cache in settings (clears PWA cache) videos are starting to work.

I have come to think that this can be the issue: https://stackoverflow.com/questions/52087208/pwa-cached-video-will-not-play-in-mobile-safari-11-4

I think range requests are breaking this plugin. Can someone explain, how we can fix this? A lot of users already cached my PWA and I can't just disable this plugin and ask them to clean the cache in IOS system.

live preview, open in ios device: https://sadursme.lv/dzerumos-iedzeris-soferis-veic-neizskaidrojamus-manevrus-iebrauc-gravi-video/

EDIT: I see its duplicate from https://github.com/ahmedkaludi/pwa-for-wp/issues/136

EDIT2: Its seems this fixed the issue but only when web app first loads so from the cache it's still broken. Please implement this in upcoming release because its real pain in the a$$. 

EDIT3: After further investigation, it seems that with this fix fetch loads whole video rather than by chunks. For now its works because its skipping PWA requests in video loading all together.

BTW loving the plugin <3

**Comment by ahmedkaludi** [comment]
can we continue this on the email ( http://pwa-for-wp.com/contact-us/ ) ? because our whole team is available and we can solve this faster with your help. 

We tried fixing #136 and spent a lot of time but we couldn't get to the root of it. hopefully this time we will be able to do it.

**Comment by alexlii1971** [comment]
Hello, 

I subscribed this topic, and it is duplicated with #136 that was submitted by myself.

I already send you all of accounts on our server, please let me know what I can do to assist you and fix this issue.

**Comment by ahmedkaludi** [comment]
@alexlii1971 Yes, i'll try to work on that next week.

@BremzeLV Any reply on my message I sent you?

**Comment by ahmedkaludi** [comment]
We can continue to discuss this topic on email to keep the bugs organized: https://pwa-for-wp.com/contact-us/

**Comment by alexlii1971** [comment]
Hello,

For me, the video works well on Safari and Chrome, but there are some error on Firefox:

http://prntscr.com/p9nvyh


Should you need any further more info, please let me know
