### ISSUE TITLE
PWA not working along with onesignal when used with multisite network

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/pwa-for-wp#169]
PWA not working along with one signal when used with multisite network

test environment for you to visualize the problem:

Follow the URLs:

1) Subsite 1. PWA Active Network. Onesignal active site by site.
The site is opening, but Onesignal does not work and Add to Home screen does not work.
https://modelo.meugabinete.app

2) Subsite 2. PWA Active Network. Onesignal not active.
The site has stopped working. A white screen is displayed.
https://demo.meugabinete.app/

Ref: https://secure.helpscout.net/conversation/940287670/79387?folderId=3081347

**Comment by ahmedkaludi** [comment]
**IMPORTANT**

- [ ] Also, we have another option called "OneSignal Compatibility" in the advanced section, why? https://monosnap.com/file/ata2SNHDssNjopiZqG3gE16lPH2RDJ

**Comment by ajeetku** [comment]
Pushed in version 1.5
