### ISSUE TITLE
Service Worker using Cloudflare Workers

### ISSUE THREAD

**Issue by pvnanini** [ahmedkaludi/pwa-for-wp#171]
Hello I'm not a developer so I don't know if this apply to your project but I want to ping you with this code that runs a pwa using a Cloudflare workers
https://github.com/DigitalOptimizationGroup/cloudflare-worker-preact-pwa
https://workers.cloudflare.com/docs
Regards,

**Comment by ahmedkaludi** [comment]
We already have a service worker of our own which is also compatible with AMP, why would we need CF worker then?

**Comment by ahmedkaludi** [comment]
we can do further communication on https://pwa-for-wp.com/contact-us/
