### ISSUE TITLE
serviceworker.js should download properly even it does not have write permission.

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#176]
- [x] Service Worker File Should add in the background even f the file has no permission.
Screenshot: https://monosnap.com/file/4CNKQ9dVKjQSA5vyVAB8OdQYn4lcFY

- [x] Download button should remove:
Screenshot: https://monosnap.com/file/axYr62uQ9YHPC9TnqEKtKuTMFGbyYn

- [ ]  Given documentation should be update:
http://pwa-for-wp.com/docs/article/how-to-download-required-files-manually-and-place-it-in-root-directory-or-change-the-permission/

Ref: https://secure.helpscout.net/conversation/945638912/80056?folderId=1060554

**Comment by ajeetku** [comment]
Resolved & pushed in version 1.5
