### ISSUE TITLE
 ServiceWorker registration failed 

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/pwa-for-wp#178]
ServiceWorker registration failed

Getting this error  ServiceWorker registration failed in the search console.

All the details of the user are in helpscout link:https://secure.helpscout.net/conversation/952916959/82015?folderId=2632030

- [x]  Issue related with one signal in multisite and caching

**Comment by amer07** [comment]
**CASE-2**
- [ https://secure.helpscout.net/conversation/955116692/82330?folderId=2770543]

**Comment by ajeetku** [comment]
https://secure.helpscout.net/conversation/955587655/82386?folderId=2632030

**Comment by ajeetku** [comment]
Pushed in Version 1.6
