### ISSUE TITLE
Different behaviors between "go to url" and "open in new window"

### ISSUE THREAD

**Issue by alexlii1971** [ahmedkaludi/pwa-for-wp#180]
Hello,

It works well with the urls to be set as  "go to url" like a really native APP.

But, If a url on the site is set to be "open in new window", there will be an top bar with "Done" button, please check the screenshot:
http://prntscr.com/p740b7

It would be great if it treat all of urls as "go to url" without that bar.

Can we expect it please?

Thanks

**Comment by Sanjeevsetu** [comment]
Actually any external urls can't be opened inside pwa app, Its a PWA limitation. For more help contact us
