### ISSUE TITLE
The discount code get showed right after the user adds the app (with WooCommerce Integration)

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#182]
We need to implement a new feature in which if the user will get a discount code for the product if he added the app after Add To HomeScreen.

When the user clicks on adding a product to cart, then we need to Trigger a bar or popup for "Add To HomeScreen". When the user clicks on the Add To HomeScreen and when the app gets installed then we need to offer the coupon in the headline and the user gets it as soon as the app is added.
 
Ref: https://secure.helpscout.net/conversation/950272605/81350?folderId=1060554

**Comment by ajeetku** [comment]
Released in https://pwa-for-wp.com/extensions/rewards-on-pwa-install/
