### ISSUE TITLE
PWA for WP is not compatible with Multisite and Onesignal

### ISSUE THREAD

**Issue by Josimarcsilva** [ahmedkaludi/pwa-for-wp#188]
Hi,
PWA for WP is not compatible with Multisite and Onesignal

After upgrading to version 1.5 the issues are:

1) The  "Add to Home On Element Click" feature does not work on Multisite with Onesignal.

2) The "Custom Add To Home Banner" feature does not work on Multisite with Onesignal.

3) When Onesignal is active on a subsite PWA will only start working when the user accepts receiving notifications. If the user does not accept notifications, PWA functionality does not work.

Below the images to illustrate the problems:

![ErroPwa1](https://user-images.githubusercontent.com/4340052/65372625-02d8d980-dc49-11e9-8c09-905f9c2fefe6.jpg)
![ErroPwa2](https://user-images.githubusercontent.com/4340052/65372629-08ceba80-dc49-11e9-8009-2af2a81ffe5b.jpg)
![ErroPwa3](https://user-images.githubusercontent.com/4340052/65372632-0bc9ab00-dc49-11e9-936a-2b3f9c43520e.jpg)
![ErroPwa4](https://user-images.githubusercontent.com/4340052/65372633-0ec49b80-dc49-11e9-8ca8-cda7ce563d31.jpg)
![ErroPwa5](https://user-images.githubusercontent.com/4340052/65372635-13894f80-dc49-11e9-9c98-b0ba2a4ef339.jpg)

**Comment by Josimarcsilva** [comment]
The correct URL to verify the problem is https://modelo.meugabinete.app

**Comment by ajeetku** [comment]
Pushed in Version 1.6

**Comment by Josimarcsilva** [comment]
Hi,

We still have a problem here.
PWA is only working when the user agrees to receive notifications from Onesignal.

If the user does not accept the OneSignal notifications "Add to Home On Element Click" and "Custom Add To Home Banner" do not work.

Take the test at https://modelo.meugabinete.app
