### ISSUE TITLE
Click at Home menu is not working properly

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/pwa-for-wp#191]
Ref:https://secure.helpscout.net/conversation/961407709/84959?folderId=2770543
See the screenshot: https://prnt.sc/p92f0y

**Comment by ahmedkaludi** [comment]
- [ ] Add to homescreen not clikable

- [ ] not working in mobile redirection scenario

**Comment by ajeetku** [comment]
Released in "Call To Action for PWA" Version 1.1

**Comment by ajeetku** [comment]
9660450

**Comment by ajeetku** [comment]
Pushed in Version 1.6
