### ISSUE TITLE
Samsung Internet Browser Compatibility

### ISSUE THREAD

**Issue by Josimarcsilva** [ahmedkaludi/pwa-for-wp#192]
Hi,

Samsung is one of the largest smartphone manufacturers in the world. All Samsung devices already have Samsung Internet Browser installed by default and so the Samsung Browser already has over 1,000,000,000+.

It would be important to make "Custom Add To Home Banner" and "Add To Home On Element Click" work on Samsung Browser too. 

I performed some testing and these two features of your plugin do not function in Samsung Internet Browser.

Samsung Internet Browser is currently PWA compliant. See image below:

![Samsung Internet Browser](https://user-images.githubusercontent.com/4340052/65374500-ef396d00-dc60-11e9-8643-feecda65f575.jpg)

**Comment by ajeetku** [comment]
the same Issue with iPhone & default browsers also

**Comment by ajeetku** [comment]
In Samsung native browser PWA banners are working properly and show the popup when we click on the PWA banner. https://prnt.sc/v6vl9s this popup is working on both banners (Custom Add To Home Banner / CTA add to home banner)
