### ISSUE TITLE
PWA - Loading markup but not loading CSS

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/pwa-for-wp#195]
User website is loading the markup offline but failed to load CSS. 
Screenshot:- https://monosnap.com/file/msUip1UOd1a4yZKRDkcZUe0ycFgub1

Helpscout Link:- https://secure.helpscout.net/conversation/964283144/85771?folderId=3243584

**Comment by ajeetku** [comment]
on user side for css delivery, used cdn which is external links.
So need to enable `Cache External Links` option to cache those css

**Comment by ajeetku** [comment]
updated at 1.7
