### ISSUE TITLE
Issue with call to action

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/pwa-for-wp#198]
**Case 1**

- [x] - [Sticky  bar not showing ]

- [x] - [ Call to action Custom Add To Home Banner is not working in mobile version] 
- [x] - [Stortcode is not working ] 

https://secure.helpscout.net/conversation/955116692/82330?folderId=2770543

**Comment by sardarui** [comment]
In IOS, the following behavior of CTA 

- [ ] **Case1**
CTA settings(steps) of safari browser is extracted in chrome browser
- [ ] **Case2**
CTA settings(steps) of chrome browser is extracted in safari browser

Ref ticket: https://secure.helpscout.net/conversation/961407709/84959?folderId=3126461
Ref URL: https://kisahdunia.com

**Comment by ajeetku** [comment]
Pushed in 1.3
