### ISSUE TITLE
problem is coming when Rest API in worpress tweaks section is set to Restricted access(Recommnede)

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/pwa-for-wp#209]
Error coming in the section of manifest when Rest API in wordpress tweaks section is set to Restricted access(Recommende).
Rest API section: https://prnt.sc/pfzsxl
Error: https://prnt.sc/pfxgt8

**Comment by akashagrjsr** [comment]
Ref: https://secure.helpscout.net/conversation/968392778/86976/

**Comment by ajeetku** [comment]
Solution added in #172 
Pushed in 1.7.1.1
