### ISSUE TITLE
Exclude Specific files in the PWA App

### ISSUE THREAD

**Issue by arunsamran** [ahmedkaludi/pwa-for-wp#210]
Hi Team,

How we can exclude the specific files in the PWA via service workers. This is not user-friendly and I have tried using the exclude cache URL options in the back-end but it's not working?

Please address this as urgent? 

https://dev3.samrantech.com/tango-amistoso/

In this above URL,  i need to exclude the popup file which is from the AMP theme folder. Please help.

**Comment by arunsamran** [comment]
Hi Team, 

Any update on this 'Urls Excludes From Cache List' it's not working for me. So please guide or advice on this urgent live issue

Thanks,

**Comment by ajeetku** [comment]
@arunsamran We already have option to 'Exclude url' from caching.
you can find in this path `PWA settings > Advance > Urls Exclude From Cache List` option.

if you still have any other issue you can mail us on https://pwa-for-wp.com/contact-us/
We will happy to help you.
