### ISSUE TITLE
Cannot modify header information

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/pwa-for-wp#214]
User can't access to his premium menu and getting warning like: 
Warning: Cannot modify header information - headers already sent by (output started at /homepages/1/d619295783/htdocs/clickandbuilds/OrangeDef/wp-admin/includes/template.php:2340) in /homepages/1/d619295783/htdocs/clickandbuilds/OrangeDef/wp-includes/pluggable.php on line 1251

Warning: Cannot modify header information - headers already sent by (output started at /homepages/1/d619295783/htdocs/clickandbuilds/OrangeDef/wp-admin/includes/template.php:2340) in /homepages/1/d619295783/htdocs/clickandbuilds/OrangeDef/wp-includes/pluggable.php on line 1254

https://secure.helpscout.net/conversation/979923445/90925?folderId=3257665

**Comment by ajeetku** [comment]
Pushed in 1.7.1.1
