### ISSUE TITLE
Pre-caching improvement: automate precaching list while update or publish any posts

### ISSUE THREAD

**Issue by Thakur25** [ahmedkaludi/pwa-for-wp#215]
After the latest update of PWA, an issue is showing "Update your pwa pre caching url list by clicking on button". Even after clicking on the button, when the post is created, it again shows up on
dashboard.

Ref: https://secure.helpscout.net/conversation/980939267/91321?folderId=3250553

Here is the screenshot:
 https://monosnap.com/file/hST7e7UIVROkvFcyAdK2W0ZV0eppRm

**Comment by wankhedekomal** [comment]
One more user is facing the same issue. also CPU usage is increases while facing this issue.

Ref: https://secure.helpscout.net/conversation/981973475/91627?folderId=3257665

**Comment by ajeetku** [comment]
For CPU usage is increases We create another ticket
Pushed in 1.7.1.1
