### ISSUE TITLE
this condition should switch to alt method

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#217]
![image](https://user-images.githubusercontent.com/48554002/66923428-6ab2f200-f046-11e9-951d-7b51dd783b3f.png)
https://secure.helpscout.net/conversation/974831480/88538?folderId=2770545

**Comment by akashagrjsr** [comment]
We should check the given condition and find out the solution:

"Change the permission or download the file Instruction."

**Comment by nommanshaik18** [comment]
Another user with the same issue. please discuss with Ahmed sir

- [ ] https://secure.helpscout.net/conversation/960503073/84468?folderId=3081347

**Comment by Arihantkankariya09** [comment]
Another user is facing the same issue.
Ref :- https://secure.helpscout.net/conversation/995029333/95927?folderId=3243584

**Comment by ajeetku** [comment]
PHP Fatal error: Uncaught Error: Call to undefined function get_filesystem_method() 
Ref: https://wordpress.org/support/topic/call-to-undefined-function-get_filesystem_method/

**Comment by ajeetku** [comment]
Above commit solutions are pushed in the live version

Didn't get Response from above Users added by @nommanshaik18  & @akashagrjsr
