### ISSUE TITLE
custom add to homescreen looking bad on Responsive

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/pwa-for-wp#221]
Hi dear, can you help me how to fix size (responsive) pop up add homescreen on any mobile?
Any customize for that problem?

You can see this pict what showing on mywp (im using Asus Max Pro M2 to take this screenshot):
http://prnt.sc/pkps27

REF: https://wordpress.org/support/topic/not-responsive-and-bad-view-button-home-screen-pop-up/

**Comment by ajeetku** [comment]
pushed in 1.7.1.2
