### ISSUE TITLE
Pwa call to action feature bug after latest update

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/pwa-for-wp#223]
https://imgur.com/PBDTfAz

Via info@muii.dk on helpscout

**Comment by ajeetku** [comment]
Commit: https://github.com/ahmedkaludi/call-to-action-for-pwa/commit/e37f5e3d4b00ca3b65f9f1f0fb8299b7803727b6

**Comment by ajeetku** [comment]
CTA Pushed in version 1.5
