### ISSUE TITLE
loader disable is not working

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/pwa-for-wp#228]
loader in PWA is not working properly.
after disabling loader page still shows loader on a page.
Ref: https://secure.helpscout.net/conversation/987889610/93950?folderId=3257665

**Comment by ajeetku** [comment]
Orientation issues use "any" instead of "auto" ref: https://developer.mozilla.org/en-US/docs/Web/Manifest/orientation

**Comment by ajeetku** [comment]
Pushed in 1.7.2
