### ISSUE TITLE
Issue in data analytics tracking count numbers  showing wrong 

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/pwa-for-wp#234]
CASE-I
https://secure.helpscout.net/conversation/987681421/93858?folderId=2770543
In data analytics tracking count is showing wrong and also analysis graph not showing.
See this screenshot:https://monosnap.com/file/oQVKexJKFzX9wKBI0HD5ORRdilDcCi

**Comment by ajeetku** [comment]
Commit: 4207409
Data-analytics For version 1.2

**Comment by ajeetku** [comment]
Pushed in version 1.2
