### ISSUE TITLE
Fatal error: Uncaught ArgumentCountError: Too few arguments to function pwaforwp_nav_menu_link_atts(),

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/pwa-for-wp#236]
CASE-I
https://secure.helpscout.net/conversation/992388636/95258?folderId=1060556
See this screenshot: https://prnt.sc/pqmn7v

**Comment by ajeetku** [comment]
Commit: b606e6a

**Comment by ajeetku** [comment]
CTA Pushed in version 1.5
