### ISSUE TITLE
Need to make compatible with all mode in amp by automatic plugin

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/pwa-for-wp#237]
Need to make compatible with all mode in amp by the automatic plugin,

https://monosnap.com/file/AuVPHLFp9RBbobWG5jSPVcQIVcxACs

REF:https://secure.helpscout.net/conversation/990932213/94913?folderId=3008055

**Comment by ajeetku** [comment]
Pushed in version 1.7.2.1
