### ISSUE TITLE
Service worker files are not registered and normal method throws 404 error.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/pwa-for-wp#239]
1)When we check in the normal method the file "sw-1-js" throws 404 error.

2)When we check with the PWA alternative method, Then it shows blank with the value '0'
https://monosnap.com/file/QF83mHiCnczupVYFQQ22GPjaE7myWF

Ref Ticket: https://secure.helpscout.net/conversation/990744281/94872?folderId=3126461

**Comment by ajeetku** [comment]
Pushed in Version 1.7.3.3
