### ISSUE TITLE
Service worker file not detected

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#240]
Ref: https://secure.helpscout.net/conversation/984839229/92778?folderId=1060554

Screenshot: https://monosnap.com/file/gdiEJI39ImAHtZ5DlgXxrBta8mR3Uc

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/pwa-for-wp/issues/238 Similar issue

**Comment by ajeetku** [comment]
Pushed in version 1.7.2
