### ISSUE TITLE
If Custom ADD to home screen is enabled then Standard Android add to the home screen should get diasble

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/pwa-for-wp#241]
If Custom ADD to home screen is enabled Standard Android add to the home screen should get diasble

https://secure.helpscout.net/conversation/997420599/96653?folderId=1060556

**Comment by ajeetku** [comment]
CTA: d02de4d

**Comment by ajeetku** [comment]
Pushed in PWA Version: 1.7.3.1
CTA version: 1.5.1
