### ISSUE TITLE
Need to built compatibility with Real-time Notifications extension of Ulltimate Member

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/pwa-for-wp#242]
As per the user's request need to build PWA compatibility with Ultimate Member and its extension Real-time Notifications.

Ref Ticket: https://secure.helpscout.net/conversation/990744281/94872?folderId=3126461

**Comment by michael-newman** [comment]
Would like to request consideration to prioritize this enhancement... thoughts?

**Comment by sardarui** [comment]
Another user requesting Ultimate member notification integration with our plugin.
Ref Ticket: https://secure.helpscout.net/conversation/1490829744/192163?folderId=3126461#thread-4329543102

**Comment by michael-newman** [comment]
Ajeetku, Please know we would gladly and actively collaborate with you on Ultimate Member REal-time Notification integration. Thank you, Mike

**Comment by michael-newman** [comment]
Could you provide timing on this request?

Please note Ultimate Member currently has over 200k+ installs and their Real-time Notifications are user-specific... PWA compatibility would be HUGE for user engagement!

Appreciate your consideration, Mike

**Comment by ajeetku** [comment]
Created a ticket on their side for proper integration. 
https://github.com/ultimatemember/ultimatemember/issues/872

**Comment by ajeetku** [comment]
@michael-newman, please create a support ticket on their side. as they responded in this ticket ultimatemember/ultimatemember#872

**Comment by ajeetku** [comment]
Compatibility Added [push-notification](https://wordpress.org/plugins/push-notification/#developers) in version 1.20

**Comment by ajeetku** [comment]
closing this ticket Fixed applied in Push-notification
