### ISSUE TITLE
Multiple issues related to PWA CTA

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#248]
- [x] Close Icon is not in correct posstion.
Screenshot: https://monosnap.com/file/5NsHiCZyZu6YpDT01z0SN8j9eYfaro

- [x] Make CTA Bar Smooth, scroll show and hide

- [x] After closing the CTA bar it should not show again. It should be cookie-based.

- [x] Custom add to the home banner  "X" is not aligned properly.

Ref: https://secure.helpscout.net/conversation/988062529/94002?folderId=1060554

**Comment by ajeetku** [comment]
CTA: 11ea455,  34ed239

**Comment by ajeetku** [comment]
Pushed in CTA 1.5.1 & PWA: 1.7.3.1
