### ISSUE TITLE
Need to Add feature to display PWA CTA in Mobile version only

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#252]
Ref: https://secure.helpscout.net/conversation/984839229/92778?folderId=1060554

We need to add an option to display PWA CTA in the Mobile version only. Users can hide PWA CTA in desktop versions only.

**Comment by ajeetku** [comment]
CTA : 5aaba4e

**Comment by ajeetku** [comment]
Pushed in CTA: 1.6 
PWA: 1.7.4.1
