### ISSUE TITLE
Need to add a feature in "CTA" to change background color and translation.

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/pwa-for-wp#256]
Need to add a feature in "CTA" to change background color and translation.

See these screenshot:
https://monosnap.com/file/tBiKCSbWGMveYSBb2cGM6znmEjZIIl
https://monosnap.com/file/shoUSIdyRwMMnavfoNTY0TViFOjv0r

REF:https://secure.helpscout.net/conversation/994189198/95727?folderId=3008055

**Comment by ajeetku** [comment]
CTA: cd3fdb7

**Comment by ajeetku** [comment]
pushed in version 1.6
