### ISSUE TITLE
Manual push notification are not receiving in mobile but receiving perfectly in desktop.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/pwa-for-wp#258]
When a user sending manual push notification then notifications are receiving in desktop version but not receiving in mobile versions.

Ref ticket: https://secure.helpscout.net/conversation/1001770206/97286?folderId=3126461

**Comment by SayyadF** [comment]
Another user facing this issue
Ref:https://secure.helpscout.net/conversation/1008853269/98383/
