### ISSUE TITLE
Enable On Desktop feature is not working properly for "Custom Add To Home Banner"

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#261]
Ref: https://secure.helpscout.net/conversation/1010699293/98679?folderId=1060554

If the user has disabled the "Enable On Desktop feature" then also the "Custom Add To Home Banner" is showing on the desktop.

**Comment by ajeetku** [comment]
This Feature is related to CTA Banner 
The similar ticket Generated: https://github.com/ahmedkaludi/pwa-for-wp/issues/252

**Comment by ajeetku** [comment]
Pushed in CTA: 1.6
