### ISSUE TITLE
UTM tracking referral not set for PWA APP.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/pwa-for-wp#262]
In Google Analytics, UTM tracking referral is not set for PWA app.

Ref:- https://secure.helpscout.net/conversation/1012894836/99036?folderId=3243584

Screenshot:
![pwa](https://user-images.githubusercontent.com/23516562/69476788-7a231900-0e04-11ea-9775-f29cae3925a2.png)

**Comment by ajeetku** [comment]
PWA pushed 1.7.4.1
