### ISSUE TITLE
CTA  FOR PWA pop up should close if the user clicks on the CTA popup

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#266]
Ref: https://secure.helpscout.net/conversation/968791236/87065?folderId=2770545

If we close the CTA popup then it should be closed permanently rather than popup comes after 4 minutes.

**Comment by ajeetku** [comment]
CTA: 61efdd9

**Comment by ajeetku** [comment]
pushed version CTA: 1.6
