### ISSUE TITLE
Feature: "only show add to home banner on specific page"

### ISSUE THREAD

**Issue by wtzr** [ahmedkaludi/pwa-for-wp#267]
We prefer an option to be able to control where the add to home banner is shown, instead of being directly visible whenever a customer lands on any page. 

In our case it only makes sense to show people the option for "add to home" once they have interacted with our website and land on a certain page.

**Comment by ahmedkaludi** [comment]
We are going to do this in https://github.com/ahmedkaludi/pwa-for-wp/issues/269
