### ISSUE TITLE
Need to Hide CTA button Added by short code, once user installed PWA APP.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/pwa-for-wp#270]
As per the user when he adds a CTA button by using shortcode in a page or a post once PWA is installed on the home screen then it should be removed.

Ref Ticket: https://secure.helpscout.net/conversation/1014749135/99357/

This scenario is occurring on the localhost too.

**Comment by ajeetku** [comment]
CTA info : #f599a7

**Comment by ajeetku** [comment]
pushed version CTA: 1.6
