### ISSUE TITLE
CF7 form is not submitting if PWA FOR WP is active

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#271]
Ref: https://secure.helpscout.net/conversation/968791236/87065/

Screenshot: https://monosnap.com/file/gqep0Nnu5YtEmcEefNSTg2i4xTqgGM

If the user is using the CF7 plugin along with PWA plugin then forms are not submitting. It shows errors in the console.

Issue recreated in Local.

**Comment by ajeetku** [comment]
Pushed in Version 1.7.4
