### ISSUE TITLE
PWA CTA bar is not showing due to Custom Add To Home Banner in AMP 

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#275]
Screenshot: https://monosnap.com/file/HWXgBqgyKmVXvC90iPfYOuoIKB5ZWQ
Ref: https://secure.helpscout.net/conversation/1013387709/99105?folderId=2770545

Custom Add To Home Banner should hide in the **AMP version** as well if the user has enabled PWA CTA.

**Comment by ajeetku** [comment]
Pushed in 1.7.5 PWA
CTA 1.7
