### ISSUE TITLE
In PWA service worker taking time to load the page

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/pwa-for-wp#276]
service worker taking 1 sec of more time to load the page in PWA.

Ref: https://secure.helpscout.net/conversation/1024695015/101142?folderId=3257665

**Comment by TMsravan** [comment]
another user when PWA is activated, page speed is getting decease.TTFB is getting increased

https://secure.helpscout.net/conversation/1019473560/100208?folderId=2632030

**Comment by robomike** [comment]
To confirm, GTmetrix report https://gtmetrix.com/reports/smartmow.com/EHboMDxM    , Look at bottom of waterfall tab.  PWA https://smartmow.com/wp-json/pwa-for-wp/v2/pwa-manifest-json/amp took over 6 seconds to load.

**Comment by robomike** [comment]
With PWA off.
https://gtmetrix.com/reports/smartmow.com/4muLSCku  total load time is 2 sec

**Comment by ajeetku** [comment]
Pushed in version 1.7.4.2
