### ISSUE TITLE
AMP URLs ending with "/amp" are not opening if PWA is activated and opening with URLs ending with "amp/"

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#277]
Ref: https://secure.helpscout.net/conversation/1026707122/101496?folderId=2770545

This is a very strange issue. If the user has enabled the PWA plugin and visiting the AMP URLs ending with "/amp" then single post URLs are not opening.  If we add one more slash "/" at the end of the URL then it's opening.

 The issue is not recreating on our local or any other user's website.

Reference video: https://drive.google.com/file/d/1RSOMqrjn2YYfxewfuOQIzBJhQo4FMwPp/view?usp=sharing

**Comment by ajeetku** [comment]
Pushed in version 1.7.4.3
