### ISSUE TITLE
Need to make maskable icon support in PWA

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#280]
Ref: https://secure.helpscout.net/conversation/1035722260/102936?folderId=3126461

**Comment by sardarui** [comment]
More information from the user regarding icons.

https://secure.helpscout.net/conversation/1035722260/102936/#thread-2937712340

**Comment by eperezf** [comment]
Is there any ETA on this feature? iOS icons look fine but Android is not.
![2020-06-08 16 12 21](https://user-images.githubusercontent.com/6854338/84075893-dca7c500-a9a2-11ea-8245-a9e90f6655c0.jpg)

**Comment by ajeetku** [comment]
Released in version 1.7.16.1
