### ISSUE TITLE
1.7.4.1 Beta

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/pwa-for-wp#283]
**UX**
- [x] If we turn on the "Push Notification" but do not setup inside then it should give the warning until it is setup properly.

**IMPORTANT**

- [x] It should give a default message first and then the button. 
The message should be "This feature requires a Free plugin which integrates with a Free Push Notification service". and the button should be "Install Plugin". https://monosnap.com/file/Ns2aBnaYEgq1mA22cb7KM9TczlmUF1

- [x] It should not say "Please Wait", it should say "Installing.." https://monosnap.com/file/JjRDLLj7zOYhiusyYECA2o2vp4jhd2

- [ ] 500 Error WHile installing the plugin: https://monosnap.com/file/XnTEqpuDE3G89jfHq5sbSTskzFXPAR

- [x] there is no need for the "Save settings" before installing or after installing in the Pushnotifications.io section: https://monosnap.com/file/cQ82I2D1OYUNZqMt3Dr1R8St1UtI7M

- [x] https://monosnap.com/file/bET2sBys33l4Dm5WSZjxZPbMltN1fC There should be some text and blue default WP button  
Message should be: "Push notifications has it's separate options view" 
Button should be: "View Settings"

- [ ] There should not be any messages shown only the ones we allow in this panel:  https://monosnap.com/file/7BTxWbEdvoxbpT83Y3DADLEK5AELXo

- [x] It should say "Push Notifications Options" https://monosnap.com/file/Sk7Q2YX5JjwsMi8ExriC9Z2rNdZkqd

- [ ]

**Comment by ajeetku** [comment]
pushed in version 1.7.4.2
