### ISSUE TITLE
New private messages cannot be sent in Buddypress

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/pwa-for-wp#286]
When user trying to send a message then getting error in the console. And The send a new message from the profile header does never open.

See this recorded video:
https://monosnap.com/file/j79MzocCbJq8sYA7Z5fWcBNBJKdXPs

REF:https://secure.helpscout.net/conversation/1041708158/103958?folderId=3008055

**Comment by ajeetku** [comment]
Pushed in version 1.7.4.3
