### ISSUE TITLE
Service worker issue on homepage when user using AMP by automatic.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/pwa-for-wp#288]
When a user using AMP by automatic (AMP mode set to Reader) then instead of the non-AMP service worker, AMP service worker is loading on the non-AMP home page.

Note: working fine on other posts/pages, the issue is on the homepage only.

Ref Ticket: https://secure.helpscout.net/conversation/1035967160/102983?folderId=3126461

**Comment by ajeetku** [comment]
pushed in 1.7.4.4
