### ISSUE TITLE
CTA shortcode button issue

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/pwa-for-wp#289]
When the user is using the CTA shortcode button, after adding the app to the home screen the button is displaying for installed user i.e, showing on the refreshed page. 

Ref Ticket: https://secure.helpscout.net/conversation/1049555224/105593?folderId=3126461

**Comment by ajeetku** [comment]
CTA: 9e65ce5

**Comment by ajeetku** [comment]
Pushed in version 1.7 CTA
