### ISSUE TITLE
One signal push notification plugin is not sending notifications when PWA app is installed.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/pwa-for-wp#290]
Two case scenarios:- 

1. https://secure.helpscout.net/conversation/1048423318/105157?folderId=3243584
- OS Push notifications not working when PWA is installed.
2. https://secure.helpscout.net/conversation/1042179134/104068?folderId=3243584
-He is not getting notifications on mobile.

**Comment by ajeetku** [comment]
With PWA Onesignal Working fine
no issue found

**Comment by vishnuaniyan** [comment]
The issue is there for me, Am using One signal plugin.
PWA for WP Version 1.7.4.4 
One Singnal Version 1.17.9

**Comment by ajeetku** [comment]
Some settings issue on one-signal setting. now one-signal & PWA working fine on https://arivukal.in/
