### ISSUE TITLE
Music player get stop playing when screen locks on Apple iphones 

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/pwa-for-wp#291]
Music player shut off when the screen locks on Apple iPhones.

https://secure.helpscout.net/conversation/1049152908/105278?folderId=2632030

https://aceapp.aceofjacks.com/

**Comment by ajeetku** [comment]
Currently, IOS safari not giving access of MediaSession to set Controls of media( audio or video )
https://developer.mozilla.org/en-US/docs/Web/API/MediaSession#Browser_compatibility
