### ISSUE TITLE
Add to Homecreen custom banner is not showing in samsung mobile device

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/pwa-for-wp#296]
Add to home screen custom banner is not showing in the Samsung mobile device.

Ref: https://secure.helpscout.net/conversation/1048407132/105149?folderId=3257665

**Comment by ajeetku** [comment]
In the updated browser of Samsung which support PWA Custom banners is working.
Checked in Samsung  internet browser >= 10.89.13.21

**Comment by ajeetku** [comment]
Released in 1.7.6
