### ISSUE TITLE
service worker showing status "Click here to setup"

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/pwa-for-wp#298]
when the user using multisite then the user keeps getting this message "click here to set up" for a service worker. even when the service worker is working properly.

screenshot: https://monosnap.com/file/kPPeCxEYA3vNRpisS6zyct6XVaQjph

Ref: https://secure.helpscout.net/conversation/1048407132/105149/

**Comment by ajeetku** [comment]
conversation with user

**Comment by ajeetku** [comment]
Released in 1.7.6
