### ISSUE TITLE
Post links not opening in PWA it opening in safari

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#302]
Ref: https://secure.helpscout.net/conversation/1049693044/105628?folderId=2770545

If the user is visiting any link in PWA then it is opening in the separate tab in IOS. It is not opening inside PWA. The issue is occurring only at one users end.

**Comment by ajeetku** [comment]
Issue fixed on user end with several option changes.
Closing this ticket, for now, if you face this issue please open it again
