### ISSUE TITLE
If the Network first Cache strategy is enabled then the updated content should load on the first time

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#306]
Ref:https://secure.helpscout.net/conversation/1029539433/101966?folderId=2770545

If the network first cache strategy is enabled then the user should should get the updated content on the first time load when he opens the PWA app first time and he is online.

**Comment by ajeetku** [comment]
Waiting For users response

**Comment by ajeetku** [comment]
its can resolve if we change the `Cached time` of HTML options

**Comment by ajeetku** [comment]
This issue is resolved from the user side(with some other solution).
Closing this ticket.
Open this ticket if this issue is reoccurring.
