### ISSUE TITLE
Need to create an option asking where to show the loader only in mobile or in desktop

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/pwa-for-wp#307]
Need to create an option asking were to show the loader only in mobile or in the desktop version,

We need to show it as per the selection.

https://secure.helpscout.net/conversation/1054843907/106449?folderId=1060554

**Comment by vishnuaniyan** [comment]
Need this option.
Anyone please help

**Comment by ajeetku** [comment]
Pushed in version 1.7.8
