### ISSUE TITLE
Google maps internal links are not working in PWA(only in mobile version)

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/pwa-for-wp#309]
Case 1: https://secure.helpscout.net/conversation/1058369713/106988?folderId=2770543

See this video clip: https://monosnap.com/direct/uzDcjoL0ptBefwph9nosFDP5mtsW5l

**Comment by ajeetku** [comment]
This issue occurs because,  the Google map is redirecting via its own(google redirection) link which is different link of origin site. That's the reason behind its opens out of PWA apps.

Closing the ticket.
