### ISSUE TITLE
Need to add a new feature to change color of the 'loader icon'

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/pwa-for-wp#312]
Need to add a new feature to change color of the 'loader icon' for both paid and free users.

Screenshot: https://monosnap.com/file/oIicNkk5il9EqzmTLFBxcfXbo0jOp1

Ref Ticket: https://secure.helpscout.net/conversation/1035967160/0/?folderId=3126461

**Comment by ajeetku** [comment]
Pushed in version 1.7.7
