### ISSUE TITLE
when PWA is activated website is getting slowdown

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/pwa-for-wp#320]
when PWA is activated website is getting slowdown

Description:

1.User is mentioning when PWA has activated the backend and the frontend of his site is becoming slow.

2. He is checking by activating the PWA plugin and checking in the network analysis of chrome debugging

3. He is also mentioning that when he clears the cookies, the site is running fast then after.

https://secure.helpscout.net/conversation/1046923306/104871?folderId=2632030

**Comment by ajeetku** [comment]
Conversation with user

**Comment by ajeetku** [comment]
Closing this ticket. Open this ticket if got any lead for the problem.
