### ISSUE TITLE
Need to add apple-touch-icon-precomposed rel link in head tag

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/pwa-for-wp#321]
In ios, app icon is taking from the theme setting favicon icon, not from the PWA settings images

<link rel="apple-touch-icon-precomposed" sizes="152x152" href="https://febiya.com/storage/2019/01/Favicon.png">

https://secure.helpscout.net/conversation/1059305185/107157?folderId=2632030
view-source:https://febiya.com/

https://monosnap.com/file/4zeemdFS3Yiu2pWgokgxebHDGfrMxQ

**Comment by ajeetku** [comment]
Pushed in version 1.7.7
