### ISSUE TITLE
User want to store Forms data in offline mode

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/pwa-for-wp#323]
The user wants to store data of Gravity Forms in offline mode (fill forms in areas with no signal coverage). 
Ref: https://secure.helpscout.net/conversation/1062294371/107697?folderId=3257665

**Comment by jlorue** [comment]
Hi, just wanted to know if you had any update of this point. Thanks

**Comment by ahmedkaludi** [comment]
We haven’t planned this yet, will do it soon

**Comment by ahmedkaludi** [comment]
Sorry, WPForms. It has an offline addon but you have to go back through each submission and resend each one. Fine for one entry but not so good if you have many. Seems to negate the point of offline access. Should be seemless.

https://wordpress.org/support/topic/offline-form-data-indexeddb/#post-12932296

**Comment by ahmedkaludi** [comment]
another user: https://secure.helpscout.net/conversation/1183500325/133495?folderId=3257665

**Comment by ahmedkaludi** [comment]
Another request with Formidable Forms Pro  https://wordpress.org/support/topic/offline-form-data-indexeddb/#post-12937049

**Comment by tbcomputerguy** [comment]
With regard to WPForms or any form plugin, do you have any idea when you might implement such a feature as offline mode using indexeddb.  If it is going to be 6 mths then I will move on to another platform..WP was the fastest and easiest to implement.

**Comment by MohammedKaludi** [comment]
Hey @tbcomputerguy 

I don't think it will take that long, we have few tasks in hand once that are done we can start working on it.

**Comment by tbcomputerguy** [comment]
Well the sooner the better.  Great product just needs this to be a fantastic product.  I will continue to get site/app ready in WP.  Is there a feature in GitHub that allows notifications when you have something as far as an update.

**Comment by ajeetku** [comment]
We released the support of forms data offline in the addon
https://pwa-for-wp.com/extensions/offline-forms-for-pwa-for-wp/

**Comment by tbcomputerguy** [comment]
Ok I will look at it.  Does the addon allow just one form entry or multiple entries
