### ISSUE TITLE
iOS support for Push notifications.io

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/pwa-for-wp#331]
Ref:- https://secure.helpscout.net/conversation/1070745398/108920/

**Comment by TMsravan** [comment]
REf: https://secure.helpscout.net/conversation/1108002504/116498?folderId=2632030

**Comment by JNAzeem** [comment]
Ref: https://secure.helpscout.net/conversation/1239012524/144952?folderId=3953286

**Comment by JNAzeem** [comment]
Ref: https://secure.helpscout.net/conversation/1285287260/155018?folderId=3953286

**Comment by Sanjeevsetu** [comment]
This feature has been added since v1.28. Please check it
