### ISSUE TITLE
call to action settings in features shows just a blank page

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/pwa-for-wp#332]
case1) https://secure.helpscout.net/conversation/1076197359/110011?folderId=3514643

Call to action Settings opens a blank page in features section.

Screengrab: https://monosnap.com/file/v5kDGrb2XrH77DvjXJYHnJjA3G38ic

**Comment by ajeetku** [comment]
The user is using an old version of the CTA so got the issue. 

In the latest version, it's fixed.
