### ISSUE TITLE
404 Page not showing Network only

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/pwa-for-wp#334]
404 Page not showing Network only caching strategy.

To create this issue:
Use caching strategy network only, and serve a non-existing URL. It will move to "site not reached".

Reference:  https://wordpress.org/support/topic/the-fetchevent-resulted-in-a-network-error-pwa-js-404-issue/#post-12420228

**Comment by ajeetku** [comment]
pushed in version 1.7.8
