### ISSUE TITLE
Performance Resolve, call of pwa manifest json

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/pwa-for-wp#336]
Need to resolve every time call of PWA manifest. make it statically called manifest json file.
Reference: https://wordpress.org/support/topic/slow-site-30/
Screenshot: https://monosnap.com/file/bSoAKoXMqQY97SvlCdUUeIqRETjrnh

**Comment by ajeetku** [comment]
pushed in version 1.7.8
