### ISSUE TITLE
Add to homescreen banner for static view website (No scroll)

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/pwa-for-wp#346]
Reference:  https://wordpress.org/support/topic/cant-display-the-add-to-homescreen-banner/
https://rse.conceptmanufacturing.com/en/accueil-en/

**Comment by akashagrjsr** [comment]
https://secure.helpscout.net/conversation/1097458930/114048?folderId=2770545
One more user-requested for this.

**Comment by ajeetku** [comment]
Pushed in version 1.7.9.3
