### ISSUE TITLE
Need to give the highest Z-index for the pull to refresh bar

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#349]
Ref: https://secure.helpscout.net/conversation/1097458930/114048?folderId=2770545
Screenshot: https://imgur.com/a/5D2HjWp

When the user uses the pull to refresh on IOS then the "Release to Refresh" is hiding behind the header. So, We need to give the highest Z-index for it.

**Comment by ajeetku** [comment]
CTA: c2fa51b

**Comment by ajeetku** [comment]
Released in version 1.3 PTR plugin
