### ISSUE TITLE
App Icon should be load in last.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/pwa-for-wp#362]
Case 1:https://secure.helpscout.net/conversation/1134248817/122326?folderId=2770543

https://monosnap.com/file/6NmvmACgWdsDKFp46NyW3myU1FSfgH

**Comment by ahmedkaludi** [comment]
if you don't know why then give me a call, do it with clarity, this is very important

**Comment by ajeetku** [comment]
Release in version 1.7.11

**Comment by ajeetku** [comment]
Some time manifest not loading if lot of js or contents came before manifest register

**Comment by ajeetku** [comment]
Released in 1.7.13
