### ISSUE TITLE
Pro extension manager should not show the extensions in plugin section

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/pwa-for-wp#363]
when we activate extension manager in AMP, it shows all the pro extensions activated with the extension manager in a different section: https://take.ms/Jad6X

If PWA pro extension manager is activated then the extensions will go into a separate section called "PWA" - that way there will not be a lot of clutter in the plugins section

Use the method we used in AMP, since plugins list generation and excluding is a heavy one, make sure we do not conflict those and keep the performance in mind.

**Comment by ajeetku** [comment]
Released in version 1.3
