### ISSUE TITLE
pwa-sw.js is not loading properly at user end

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#364]
Console Error: pwa-sw.js: Uncaught (in promise) TypeError: Request failed

The issue is a strange and critical one. The issue is occurring for only one user.

Ref: https://secure.helpscout.net/conversation/1138130881/123228?folderId=1060554

**Comment by ajeetku** [comment]
Need to Debug and cause of error

**Comment by ajeetku** [comment]
Some settings issue Found on the user side, now issue fixed

**Comment by ajeetku** [comment]
Pushed in 1.7.11
