### ISSUE TITLE
Need to check the number of installations count of our PWA on users site.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/pwa-for-wp#365]
User reporting that the count is doubled than the visitors-visiting the site.

Ref Ticket: https://secure.helpscout.net/conversation/1137606567/123139/

**Comment by ahmedkaludi** [comment]
let me know if you need help with clarity

**Comment by ajeetku** [comment]
DAFP: 0108814

**Comment by ajeetku** [comment]
Released in the version in version 1.4 of DAFP
