### ISSUE TITLE
Change email endpoint to Sendy API 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/pwa-for-wp#368]
https://sendy.co/api

- [x] PWA FOR WP

- [x] Push Notifications.io plugin

- [x]  Push Notifications.io website

**Comment by ahmedkaludi** [comment]
you can discuss this with @MohammedKaludi

**Comment by ajeetku** [comment]
PN: 3b39428

**Comment by ajeetku** [comment]
Released version 1.7.13
