### ISSUE TITLE
Need to add end point in lincence key  for agency users

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/pwa-for-wp#369]
Case 1: https://secure.helpscout.net/conversation/1142996369/124250?folderId=2770543

**Comment by ahmedkaludi** [comment]
This needs to be built into AMPforWP

**Comment by ahmedkaludi** [comment]
Issue moved to [ahmedkaludi/accelerated-mobile-pages #4404](https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4404) via [**ZenHub**](https://www.zenhub.com/)
