### ISSUE TITLE
Add to Homescreen not working . Can be checked on stage.embibe.com/exams

### ISSUE THREAD

**Issue by krishnakant888** [ahmedkaludi/pwa-for-wp#375]
https://www.dropbox.com/s/poc6qy2lawnea89/Screenrecorder-2020-04-29-21-06-45-454.mp4?dl=0

When I go to Non-amp page and navigate back to amp page it starts showing after that only but if the user never navigates to Non-amp page through view non amp button it never shows.

**Comment by krishnakant888** [comment]
Let me know once it fixed . I have verified all configurations and it's well configured .

**Comment by ajeetku** [comment]
@krishnakant888 in AMP PWA is working, we don't need to move in non-amp for getting default banner. 
We need to wait some time to install the app, that default PWA banner will appear automatically. 

please check on https://wordpress-123147-847862.cloudwaysapps.com/amp

**Comment by krishnakant888** [comment]
It's not coming you can check at stage.embibe.com/exams/jee-main/amp

**Comment by krishnakant888** [comment]
The add to home screen is not working on amp pages.

**Comment by ajeetku** [comment]
on this site stage.embibe.com/exams/jee-main/amp Everything is done, just need to resave the plugin settings. 

now only one issue CORS policy from cloudfront.net please follow https://aws.amazon.com/premiumsupport/knowledge-center/no-access-control-allow-origin-error/

**Comment by krishnakant888** [comment]
Alrady did still not working

**Comment by ajeetku** [comment]
@krishnakant888 its issue of HTTP and course policy
 There are many links that have the wrong method of HTTP to HTTPS. https://prnt.sc/sccwk5 

https://prnt.sc/sccxtp in this screenshot 2 points
1. CORS policy: Images are serving from cloudfront.net. On CloudFront will have the option to allow cors request.
2. There are many links that are moved to https in the wrong way, as mention in1st screenshot.

only this is the issue on your website, I have already saved your PWA setting yesterday.

**Comment by krishnakant888** [comment]
Our way of implementation is working fine on www.embibe.com/exams but when
we used the plugin PWA for WP can you tell any definite way to solve this
cors.

**Comment by ajeetku** [comment]
PWA issue is fixed, for other issues follow the below solution: 
For CORS policy issue please follow the solution of https://aws.amazon.com/premiumsupport/knowledge-center/no-access-control-allow-origin-error/

For HTTPS issue, please connect to support.

**Comment by ajeetku** [comment]
Closing this ticket

**Comment by krishnakant888** [comment]
@ajeetku Add to homescreen it's not working on Amp only and working fine on Non-Amp pages then how it's due to cors policy . Can you take teamviwer access and fix it remotely.
