### ISSUE TITLE
Need to Add more checks to block sql injection

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/pwa-for-wp#376]
April 30, 2020 4:52am 45.227.255.227 (Panama) Blocked for SQL Injection in query string: sw=pwa-register-sw-js UNION ALL SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL#
April 30, 2020 4:52am 45.227.255.227 (Panama) Blocked for SQL Injection in query string: sw=pwa-register-sw-js UNION ALL SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL#
April 30, 2020 4:52am 45.227.255.227 (Panama) Blocked for SQL Injection in query string: sw=pwa-register-sw-js%’ UNION ALL SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL#
April 30, 2020 4:52am 45.227.255.227 (Panama) Blocked for SQL Injection in query string: sw=pwa-register-sw-js%’ UNION ALL SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL#
April 30, 2020 4:52am 45.227.255.227 (Panama) Blocked for SQL Injection in query string: sw=pwa-register-sw-js%’ UNION ALL SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL#
April 30, 2020 4:52am 45.227.255.227 (Panama) Blocked for SQL Injection in query string: sw=pwa-register-sw-js%’ UNION ALL SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL#
April 30, 2020 4:52am 45.227.255.227 (Panama) Blocked for SQL Injection in query string: sw=pwa-register-sw-js%’ UNION ALL SELECT NULL,NULL,NULL,NULL,NULL,NULL#
April 30, 2020 4:52am 45.227.255.227 (Panama) Blocked for SQL Injection in query string: sw=pwa-register-sw-js%’ UNION ALL SELECT NULL,NULL,NULL,NULL,NULL#
April 30, 2020 4:52am 45.227.255.227 (Panama) Blocked for SQL Injection in query string: sw=pwa-register-sw-js%’ UNION ALL SELECT NULL,NULL,NULL,NULL#
April 30, 2020 4:52am 45.227.255.227 (Panama) Blocked for SQL Injection in query string: sw=pwa-register-sw-js%’ UNION ALL SELECT NULL,NULL,NULL#

April 30, 2020 4:48am 45.227.255.227 (Panama) Blocked for SQL Injection in query string: sw=pwa-register-sw-js%’ AND 7659=CAST((CHR(113)||CHR(112)||CHR(122)||CHR(118)||CHR(113))||(SELECT (CASE…
April 30, 2020 4:48am 45.227.255.227 (Panama) Blocked for SQL Injection in query string: sw=pwa-register-sw-js AND (SELECT 7454 FROM(SELECT COUNT(*),CONCAT(0x71707a7671,(SELECT (ELT(7454=7454,…
April 30, 2020 4:48am 45.227.255.227 (Panama) Blocked for SQL Injection in query string: sw=pwa-register-sw-js%’ AND (SELECT 7454 FROM(SELECT COUNT(*),CONCAT(0x71707a7671,(SELECT (ELT(7454=745…
April 30, 2020 4:48am 45.227.255.227 (Panama) Blocked for SQL Injection in query string: sw=pwa-register-sw-js’ AND (SELECT 7454 FROM(SELECT COUNT(*),CONCAT(0x71707a7671,(SELECT (ELT(7454=7454…
April 30, 2020 4:48am 45.227.255.227 (Panama) Blocked for SQL Injection in query string: sw=pwa-register-sw-js’) AND (SELECT 7454 FROM(SELECT COUNT(*),CONCAT(0x71707a7671,(SELECT (ELT(7454=745…
April 30, 2020 4:48am 45.227.255.227 (Panama) Blocked for SQL Injection in query string: sw=pwa-register-sw-js AND (SELECT 7454 FROM(SELECT COUNT(*),CONCAT(0x71707a7671,(SELECT (ELT(7454=7454,…
April 30, 2020 4:48am 45.227.255.227 (Panama) Blocked for SQL Injection in query string: sw=pwa-register-sw-js) AND (SELECT 7454 FROM(SELECT COUNT(*),CONCAT(0x71707a7671,(SELECT (ELT(7454=7454…
April 30, 2020 4:48am 45.227.255.227 (Panama) Blocked for SQL Injection in query string: sw=(SELECT (CASE WHEN (2638=2638) THEN 2638 ELSE 2638*(SELECT 2638 FROM INFORMATION_SCHEMA.CHARACTER_SE…
April 30, 2020 4:48am 45.227.255.227 (Panama) Blocked for SQL Injection in query string: sw=(SELECT (CASE WHEN (5004=4849) THEN 5004 ELSE 5004*(SELECT 5004 FROM INFORMATION_SCHEMA.CHARACTER_SE…
April 30, 2020 4:46am 45.227.255.227 (Panama) Blocked for SQL Injection in query string: pwa_for_wp_script=1%’ UNION ALL SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL#

**Comment by ajeetku** [comment]
https://wordpress.org/support/topic/sql-injection-logs/ Refer

**Comment by ajeetku** [comment]
Release in version 1.7.11
