### ISSUE TITLE
If PWA menu is enabled the menu gets aligned to full width

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#377]
Ref: https://secure.helpscout.net/conversation/1152694399/126453?folderId=1060556

Screenshot: https://prnt.sc/s98kd7

The "display:block" inline CSS is adding. We need to remove this unwanted CSS adding through some JS files.

**Comment by ajeetku** [comment]
CTA : 107dffc

**Comment by ajeetku** [comment]
Released on 1.7.12
