### ISSUE TITLE
Last update 1.7.11 error

### ISSUE THREAD

**Issue by dnikola** [ahmedkaludi/pwa-for-wp#379]
Hello

after last update there is an error

[02-May-2020 08:56:44 UTC] PHP Fatal error:  Uncaught Error: Class 'Elementor\Plugin' not found in /home/xxx/public_html/wp-content/plugins/pwa-for-wp/admin/common-function.php:101
Stack trace:
#0 /home/xxx/public_html/wp-includes/class-wp-hook.php(287): pwaforwp_frontend_enqueue('')
#1 /home/xxx/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /home/xxx/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home/xxx/public_html/wp-includes/script-loader.php(2294): do_action('wp_enqueue_scri...')
#4 /home/xxx/public_html/wp-includes/class-wp-hook.php(287): wp_enqueue_scripts('')
#5 /home/xxx/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#6 /home/xxx/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#7 /home/xxx/public_html/wp-includes/general-template.php(2884): do_action('wp_head')
#8 /home/xxx/public_html/wp-content/themes/bridge/header.php(28): wp_head()
#9 /home/xxx/public_html/wp-includes/template.php(723): require_once(' in /home/xxx/public_html/wp-content/plugins/pwa-for-wp/admin/common-function.php on line 101

**Comment by AlexValois** [comment]
Same for me with Version 1.7.11. I had to desactivate to get my website working again.

**Comment by dnikola** [comment]
> Same for me with Version 1.7.11. I had to desactivate to get my website working again.

revert back to 1.7.10 
https://downloads.wordpress.org/plugin/pwa-for-wp.1.7.10.zip

**Comment by ajeetku** [comment]
Minor update pushed 1.7.11.1

**Comment by AlexValois** [comment]
Thanks dnikola. I have just installed 1.7.11.1 and it works fine.
Thanks ajeetku :) Quick fix!

**Comment by dnikola** [comment]
Yes, quick fix.

Thanks
