### ISSUE TITLE
Extensions are showing require pro even after the extension manager is activated with a key.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/pwa-for-wp#381]
https://secure.helpscout.net/conversation/1152932300/126565?folderId=3243584

https://secure.helpscout.net/conversation/1153952195/126837?folderId=3243584

https://monosnap.com/direct/FQFcnnJD3UzdtEebkTaTAjemkBYLqn

**Comment by ajeetku** [comment]
Pushed in version 1.7.14
