### ISSUE TITLE
The user should redirect to the "Extension Manager" section after clicking on the "Premium Features" if he is using the "PWA extension Manager"

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#384]
Ref: https://secure.helpscout.net/conversation/1147819286/125261?folderId=2770545

If the user is using the "PWA Exnsiona Manager" and if he clicks on the premium features option, then he should redirect to the "Extension Manager" section where the extensions are available in spite of showing the place to enter the license key.

The place to enter the license key should only show if the user is using the PWA one or extensions like CTA for PWA.

**Comment by ajeetku** [comment]
Pushed in version 1.7.14
