### ISSUE TITLE
If the "PWA Extension Manager" is enabled without the "PWA FOR WP & AMP" then its giving fatal error

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#387]
Fatal error: Uncaught Error: Call to undefined function pwaforwp_list_addons() in E:\PHPXAMPP\htdocs\AMPWP\wordpress\wp-content\plugins\pwa-pro-extension-manager\pwa-pro-extension-manager.php:399 Stack trace: #0 E:\PHPXAMPP\htdocs\AMPWP\wordpress\wp-content\plugins\pwa-pro-extension-manager\pwa-pro-extension-manager.php(619): PWAFORWPPROExtensionManager->get_all_plugins_addon_list() #1 E:\PHPXAMPP\htdocs\AMPWP\wordpress\wp-includes\class-wp-hook.php(288): PWAFORWPPROExtensionManager->plugin_page_plugin_heading(Array) #2 E:\PHPXAMPP\htdocs\AMPWP\wordpress\wp-includes\plugin.php(206): WP_Hook->apply_filters(Array, Array) #3 E:\PHPXAMPP\htdocs\AMPWP\wordpress\wp-admin\includes\class-wp-list-table.php(403): apply_filters('views_plugins', Array) #4 E:\PHPXAMPP\htdocs\AMPWP\wordpress\wp-admin\plugins.php(621): WP_List_Table->views() #5 {main} thrown in E:\PHPXAMPP\htdocs\AMPWP\wordpress\wp-content\plugins\pwa-pro-extension-manager\pwa-pro-extension-manager.php on line 399

**Comment by ajeetku** [comment]
Pro: 8e96bbf

**Comment by ajeetku** [comment]
Released in pro version 1.5
