### ISSUE TITLE
Need to enhance installation banner.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/pwa-for-wp#388]
The user is using Farsi language along with WPML plugin on his site.

We need to translate the installation banner content when language changes & we need to check the position of the " X " icon placed from right to left when the user uses RTL scripts on site.

Ref Ticket: https://secure.helpscout.net/conversation/1150621792/125942?folderId=3126461

**Comment by ajeetku** [comment]
https://monosnap.com/file/pzTFQ8uc4dOhRUcpxuW3CqwVEei89c

**Comment by ajeetku** [comment]
Released a new plugin for https://pwa-for-wp.com/extensions/multilingual-compatibility-for-pwa/
Pushed in Version 1.7.34
