### ISSUE TITLE
Need to add the feature"reuse campaigns " in the push notification .io

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/pwa-for-wp#392]
Suggestion from the user: Something that might be a nice enhancement would be to reuse campaigns already created without retyping the information or to be able to create and save them for future use even without sending them at the time of creation. Obviously a scheduler would be helpful also as would the ability to have some level of targeting the subscribers.

ref: https://secure.helpscout.net/conversation/1162565155/129307?folderId=3575684

**Comment by JNAzeem** [comment]
ref: https://secure.helpscout.net/conversation/1270737337/151784?folderId=3953286

**Comment by Sanjeevsetu** [comment]
It has been moved to actual push-notification repository. ref: https://github.com/ahmedkaludi/push-notification/issues/127
