### ISSUE TITLE
 An error is being shown in light house report for push notification.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/pwa-for-wp#394]
Screenshot: https://monosnap.com/file/VvSWRFWKz7etuf88fOBauPNwWJIDwJ
Page URL: https://bitcoin-casino-no-deposit-bonus.com/
Generated report: https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fbitcoin-casino-no-deposit-bonus.com%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext

**Comment by ajeetku** [comment]
PN Released in version 1.12
