### ISSUE TITLE
On android and AMP version if you click on the bell it redirects you to non-amp website but desktop version (not responsive).

### ISSUE THREAD

**Issue by LaxmiBhavani-98** [ahmedkaludi/pwa-for-wp#396]
Ref : https://secure.helpscout.net/conversation/1124285253/119801?folderId=3611365

https://monosnap.com/file/WfKp2G4m6fHoGz6NF9XKYmaK0b9PhC

**Comment by ajeetku** [comment]
PN: 5843db4

**Comment by ajeetku** [comment]
Released in PN version: 1.11
