### ISSUE TITLE
Add To Homescreen" popup is not showing on AMP in first time

### ISSUE THREAD

**Issue by LaxmiBhavani-98** [ahmedkaludi/pwa-for-wp#397]
Ref : https://secure.helpscout.net/conversation/1124285253/119801?folderId=3611365

https://monosnap.com/file/R5V0k7Gsuh7ttikImFcRlId5eN7aYz

**Comment by ajeetku** [comment]
commit b3f6d4e

**Comment by ajeetku** [comment]
Pushed in version 1.7.15
