### ISSUE TITLE
Need to create an option to disable the automatic add to home screen pop

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/pwa-for-wp#398]
https://secure.helpscout.net/conversation/1160399843/128698?folderId=2632030

One of the use cases of the user is:He sell a membership product on my website and the customer gets access to a membership area after purchase. He don't want the user to get any "add to home" prompt on the landing page or on the checkout page. In the membership area the user gets a video in which he is guided how to install the PWA.

**Comment by ajeetku** [comment]
Pushed in version 1.7.14
