### ISSUE TITLE
 WPML Compatibility with PWA plugin

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/pwa-for-wp#402]
WPML Compatibility with PWA plugin:

when we are changing the language by using the WPML plugin the server worker is not working properly. for example if we are changing the english to french language the service worker still coming form the english website.

Ref: https://secure.helpscout.net/conversation/1164160518/129685?folderId=1060556

**Comment by ajeetku** [comment]
Released a new plugin for https://pwa-for-wp.com/extensions/multilingual-compatibility-for-pwa/
Pushed in Version 1.7.34
