### ISSUE TITLE
Need to create a shortcode and a function :- if is PWA.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/pwa-for-wp#405]
https://secure.helpscout.net/conversation/1175738044/132042?folderId=3243584
In this the content will be only shown when the website is visited through PWA.

**Comment by ajeetku** [comment]
Added a class only for PWA app content "pwaforwp-app-contents"

**Comment by ajeetku** [comment]
Released in 1.7.23
