### ISSUE TITLE
Need  to convert &amp; to & character in PWA site title in manifest

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/pwa-for-wp#406]
In manifest when we use "&" in the site name or site short name its convert to "&amp;".
now we need to convert as it is here on manifest.json also

REF:https://secure.helpscout.net/conversation/1171568925/131101?folderId=3528427

REF screenshot:(https://prnt.sc/so46l6)

**Comment by ajeetku** [comment]
Pushed in PWA version 1.7.14.1
