### ISSUE TITLE
"Show on Desktop CTA" and "Show CTA banner without scroll" option in cta are working without enabling those options in amp version

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/pwa-for-wp#408]
https://secure.helpscout.net/conversation/1178151122/132460?folderId=2632030

Even though they are disabled but, in amp version, cta is displaying on desktop and initial load it is displaying.

Sometimes in non-amp also cta displays without scroll. 

Please see this video it is clearly shown: https://monosnap.com/file/XhUQoczunVPeY9bcwLmkW67IK8fGol

- [ ] Need to improve this name for more understandable and need to had help tool tip for this option Show on Desktop CTA

- [ ]  Need to improve this name for more understandable and need to had help tool tip for this option Show cta banner without scroll.

https://www.viaggi-usa.it/fly-and-drive-usa/amp/

**Comment by ajeetku** [comment]
Released in version CTA: 1.8.6
