### ISSUE TITLE
Integration with the pushnami pushnotification 

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/pwa-for-wp#409]
REF:https://secure.helpscout.net/conversation/1178959221/132580?folderId=3528427

**Comment by RobertDaleSmith** [comment]
Feel free to ping me anytime if I can help add support. I pulled this repository and started a new branch attempting to add 3rd-party support for Pushnami. Trying to wrap my head around how this plugin works now.

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/pwa-for-wp/pull/413

**Comment by ajeetku** [comment]
f410fa0

**Comment by ajeetku** [comment]
Released in 1.7.24 
on the place of #513, this ticket has pushed
