### ISSUE TITLE
iOS splash screen issue

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/pwa-for-wp#410]
Need to resolve iOS splash screen solution with multiple iOS devices.

https://5cb6d3a94c1b367b05843b5f--crossyroad.netlify.app/

**Comment by TMsravan** [comment]
Another user with the same issue: 
https://secure.helpscout.net/conversation/1197376474/136409?folderId=2632030

**Comment by TMsravan** [comment]
Another user with the same issue: https://secure.helpscout.net/conversation/1212230902/138834?folderId=2632030

**Comment by ajeetku** [comment]
Released in version 1.7.17
