### ISSUE TITLE
Status showing incorrect data in PWA main settings 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/pwa-for-wp#414]
Status showing incorrect data in PWA main settings 

https://monosnap.com/file/4kt5DWsAQfDiv9QqQRDmjvb0wcx5cj

Please discuss with me before working on this ticket.

**Comment by MohammedKaludi** [comment]
Improvement required: https://monosnap.com/file/e8RvS0bICPpqndypFIPgdDjr4n06KU

**Comment by MohammedKaludi** [comment]
Checkbox and messaging is behaving weirdly https://monosnap.com/file/e8RvS0bICPpqndypFIPgdDjr4n06KU

**Comment by ajeetku** [comment]
Released version 1.7.15
