### ISSUE TITLE
Need improvement in PWA to APK extension

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/pwa-for-wp#415]
1. **Package id** needs some helping text, what it does and what to add in it.

2. Need to improve the message, while and after generating the APK.
2.1.  While generating: 
https://monosnap.com/file/lJMT0ncIGzq8tKNmtJ6C2OcU1S1vs2 
It should be, Please wait while we generate the APK file for you. Do not close the window until the APK is generated.
2.2. This is after it is generated: 
https://monosnap.com/file/LwvfWqAGV0RHAovRFBYjefY2vmXHnr
The message should be: Congratulations, the APK file is successfully generated. Click Here to Download.

3. Change text  from Previous generate APK to "Previously generated APK"

**Comment by ajeetku** [comment]
Pushed in PWA to APK 0.5
