### ISSUE TITLE
Popup height issue in Sub settings

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/pwa-for-wp#416]
https://monosnap.com/file/c1O2vfwUKjsi3nJfCMv7HhBVpJPdOt

also need to style footer where it has "Save" button

**Comment by MohammedKaludi** [comment]
Need to use this css:
@media only screen and (max-width: 1200px) {
  .pwaforwp-main-wrapper {
    width:95%;
  }
}

**Comment by ajeetku** [comment]
We changed the popup design for every features options

**Comment by ajeetku** [comment]
Released in version 1.7.16
