### ISSUE TITLE
APP icon image for ios is taking the from the wp-customization settings

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/pwa-for-wp#423]
For infomation user is using the divi theme.

REf: https://monosnap.com/file/Kb7dMKWHoNVn7Hq6PUYEAFINr7O0IU

APP icon image in ios is taking from the wp-customization. But in Android it is working fine. Image is taking from the PWA settings.

https://secure.helpscout.net/conversation/1160399843/128698?folderId=2632030

https://app.foreverfitchallenge.club/

Ref: 

in IOS:

![image](https://user-images.githubusercontent.com/46995400/83745103-ae607780-a67a-11ea-8961-10c6edd414ca.png)

In Android : 
![image](https://user-images.githubusercontent.com/46995400/83745689-8cb3c000-a67b-11ea-9133-b5e4f2b2c82b.png)

https://app.foreverfitchallenge.club/

https://secure.helpscout.net/conversation/1160399843/128698?folderId=1060556

**Comment by ajeetku** [comment]
The theme also generating apple icons, which are overwriting the PWA app icon.

**Comment by ajeetku** [comment]
closing this ticket
