### ISSUE TITLE
CTA Banner should not load above the website header

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/pwa-for-wp#424]
CTA Banner should not load above the website header, First cta banner should be the website header.

The Use case header is: website Hedear is not visible when the cta banner is present.

Please see this video it is clearly shown: https://monosnap.com/file/PgDHRP1kQjYhGXrnRYrUMhTWjC7nV6

**Comment by ajeetku** [comment]
CTA: 3c55920

**Comment by ajeetku** [comment]
Released in CTA 1.8.5
