### ISSUE TITLE
CTA banner is displying even the cta sticky bar opiton is disabled

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/pwa-for-wp#425]
CTA banner is displaying even the cta sticky bar option is disabled,

Use case when the main option is enabled and the https://monosnap.com/file/LJrjDAwAWZTVF5JoBj1xI5FJkKxNrl

And the internal option is disabled.
REf: https://monosnap.com/file/HmeqodGBio4hZd4GHPBrgb3922fHqe

https://secure.helpscout.net/conversation/1160399843/128698/

![image](https://user-images.githubusercontent.com/46995400/83761022-600ba280-a693-11ea-943d-54f98c0da6c0.png)

**Comment by ajeetku** [comment]
CTA : e5edae6

**Comment by ajeetku** [comment]
Released in CTA 1.8.5
