### ISSUE TITLE
Compatibility with the Translatepress plugin

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/pwa-for-wp#428]
Need to make compatibility with the TranslatePress - Multilingual plugin(https://wordpress.org/plugins/translatepress-multilingual/).

PWA is working when the default language is selected. But when we change language then it's not working.

Ref: https://secure.helpscout.net/conversation/1185063722/134137?folderId=3257665

**Comment by ajeetku** [comment]
Released in Addon Multilingual Compatibility for PWA  version 1.2
