### ISSUE TITLE
Need to update the author information from all the extensions.

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/pwa-for-wp#430]
https://monosnap.com/file/v68Jav0zdUpwi0dM6wfdQZ5BxLDQxl

The info should be: 
Name: PWAforWP Team
link: https://pwa-for-wp.com/

- [x]   Call to Action for PWA

- [x] Data Analytics for PWA

- [x] Loading Icon Library for PWA

- [x] Pull to Refresh for PWA

- [x] PWA Pro Extension Manager

- [x] PWA to APK Plugin

- [x] Scroll Progress Bar for PWA

**Comment by ajeetku** [comment]
updated on all plugins for the latest updates
