### ISSUE TITLE
Iniciar sesion en la versión movil no funciona

### ISSUE THREAD

**Issue by Conka242** [ahmedkaludi/pwa-for-wp#435]
En la versión móvil una vez creada la app no funciona y no permite realizar el login de los usuarios.
Prueba: https://academia.alianzapps.com/

**Comment by ahmedkaludi** [comment]
How do we test this issue?

Can you make a video to show the issue? So I can understand and recreate the issue?

**Comment by ahmedkaludi** [comment]
GitHub is for verified and recreatable bugs, our team is still there, Just create a ticket for via website
