### ISSUE TITLE
Local video is not caching

### ISSUE THREAD

**Issue by LaxmiBhavani-98** [ahmedkaludi/pwa-for-wp#444]
Ref : https://secure.helpscout.net/conversation/1139376003/123466?folderId=3611365

After playing video for 2 to 3 min, internet is not working then when video played from starting, it's not playing.
https://monosnap.com/file/q6luxPJBzLXDZQpEW9mgD07tmg7nb5

**Comment by ahmedkaludi** [comment]
https://www.cienciasinternas.com/miguru/

**Comment by ajeetku** [comment]
Released in 1.7.22
