### ISSUE TITLE
Using Standalone mode but when users click on the blog it opens in a minimal browser – as it is an external URL. Need to make blog open in standalone mode.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/pwa-for-wp#449]
User uses Standalone mode but when users click the blog it opens in a minimal browser – as it is an external URL. He would like us to modify the scope parameter (link: https://web.dev/add-manifest/#scope) so that the blog also opens in standalone mode.

ref: https://secure.helpscout.net/conversation/1205910604/138021?folderId=3678830

**Comment by ajeetku** [comment]
Currently, multiple domains are not possible to show in standalone mode. And cannot set multiple scopes in PWA.
So, closing this ticket.
