### ISSUE TITLE
Issue with 'X' button of custom add to home screen banner.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/pwa-for-wp#450]
While we click on the 'X' button of custom home screen banner it is requesting to download/install instead of closing the banner.

Ref Video: Attached in the below ticket.

Ref Ticket: https://secure.helpscout.net/conversation/1196322197/136257?folderId=3126461#thread-3477741515

**Comment by ajeetku** [comment]
Released in 1.7.17.1
