### ISSUE TITLE
User want to store Forms data in offline mode.(Caldera forms)

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/pwa-for-wp#451]
User is using the caldera forms plugin https://secure.helpscout.net/conversation/1217041923/139886?folderId=3243584
visit the users ticket and check the note for the URL.

**Comment by ajeetku** [comment]
Released this feature in https://pwa-for-wp.com/extensions/offline-forms-for-pwa-for-wp/
