### ISSUE TITLE
Need to change the UI of the adding the splash screen automatically for the IOS

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#452]
Ref: https://secure.helpscout.net/conversation/1219652231/140746/

If the user is currently adding the splash screen for the IOS using the automatic option then after generating the splash screen when the user refreshes the page, the PWA option panel is again not showing anything that the user has selected.

**Comment by ajeetku** [comment]
Released in pwa version  1.7.20
