### ISSUE TITLE
The APK app generated should not show the loading bar on the top.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/pwa-for-wp#457]
https://secure.helpscout.net/conversation/1222182269/141387?folderId=3243584

It gives a feeling that we are visiting the website in a browser.

https://prnt.sc/tjn0qe

**Comment by amer07** [comment]
One more:https://secure.helpscout.net/conversation/1232615613/143555?folderId=2770543

Screenshot:https://prnt.sc/tn0v05

**Comment by akashagrjsr** [comment]
One more user reported for this:
https://secure.helpscout.net/conversation/1248859701/147327?folderId=2770545

Screenshot: https:://sigarammart.com/images/pwa.jpg

**Comment by mysecretlifeadmin** [comment]
Good morning @ahmedkaludi I have same issue  https://prnt.sc/tyvlwc 
Can you please help? thank you
Manuela

**Comment by ahmedkaludi** [comment]
This has been fixed in https://pwa-for-wp.com/2020/08/17/pwa-to-android-app-apk-version-0-8/

**Comment by mysecretlifeadmin** [comment]
Thank you @ahmedkaludi this evening I will upgrade my APK
I appreciate your help
