### ISSUE TITLE
Need to provide option to switch default cache strategy for the user if using the login in the front end

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#461]
Ref: https://secure.helpscout.net/conversation/1231317133/143261?folderId=2770545

If the user has a login page in the frontend and he selects the "Default Cache Strategy" as "Cache First" then it automatically conversing into Network first after some time.  User wants to use the Cache first strategy.

**Comment by ajeetku** [comment]
Released in PWA version 1.7.20
