### ISSUE TITLE
Need to give the feature to change the position of the push notification bar

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#471]
Ref: https://secure.helpscout.net/conversation/1239439534/145060?folderId=2770545

Screenshot: https://prnt.sc/tr2fre

The push notification bar is hiding behind the "Add To Home Screen Banner" therefore the user is not able to see it.

**Comment by ajeetku** [comment]
Pushed in PN 1.13
