### ISSUE TITLE
The PWA CTA close button is not working

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#472]
Ref: https://secure.helpscout.net/conversation/1239439534/145060?folderId=2770545

Screenshot: https://prnt.sc/tr42ix

The PWA CTA close button is not working. When the user clicks on it nothing action is happening. The issue is also occurring on the local.

Need to add the below code in calltoaction-for-pwa.js

var crossButton = document.getElementsByClassName("pwaforwp_add_home_close")
  for(i=0; i<crossButton.length; i++ ){
    crossButton[i].addEventListener("click", function(){
      this.parentNode.style.display='none';
      document.cookie = "pwaforwp_prompt_close="+new Date();
      document.getElementsByTagName("html")[0].style.marginTop = 0;
    })
  }

**Comment by ajeetku** [comment]
Fixed in CTA 1.8.7
