### ISSUE TITLE
iPhone 7 iOS 13.5.1 Safari - Favicon is using the default one

### ISSUE THREAD

**Issue by Anticosti** [ahmedkaludi/pwa-for-wp#473]
Greetings, 

On a vanilla site:
**01.** I configured the default Site Icon at:
Appearance / Site Identity;
So far so good. The Favicon appears everywhere.
**02.** I installed PWA for WP Version 1.7.18.1
**03.** I edited the necessary files for App Icon and App Splash Screen Icon
Defaults being:
wp-content/plugins/pwa-for-wp/images/logo.png (192px x 192px)
wp-content/plugins/pwa-for-wp/images/logo-512x512.png
I swapped these for my own files.
**04.** Go back to my iPhone;
**05.** Clear Safari cache;
**06.** Clear the site's Favicon;
**07.** Reload the site in Safari;
Result: I lost my custom Favicon (site identity). The Favicon is now the one from:
/wp-content/plugins/pwa-for-wp/images/logo.png (DEFAULT APP)
Same result if I delete all PWA for WP files

I just don't understand why it leaves it's own icons even after deleting the plugin and clearing all the caches CDN and everywhere?

Thank you.

**Comment by ajeetku** [comment]
@Anticosti please check once we did these changes in 1.7.19 #483, please update and test once on the latest version.

**Comment by Anticosti** [comment]
@ajeetku Thanks you for the update. I can't reproduce anymore. You may close this issue. Take care!

**Comment by ajeetku** [comment]
Sure thanks for the confirmation
