### ISSUE TITLE
Make FCM push notification use the Google Firebase scheme

### ISSUE THREAD

**Issue by VaiTon** [ahmedkaludi/pwa-for-wp#477]
At the moment the service worker uses the `data` property, while firebase sends the notification content inside the `notification` property. When a notification is sent via firebase console it is rendered as "undefined" by the service worker.

**Comment by ahmedkaludi** [comment]
@VaiTon Github is for tested and re-creatable bugs, for support please go to https://pwa-for-wp.com/contact-us/
