### ISSUE TITLE
Feature request: Back button

### ISSUE THREAD

**Issue by Anticosti** [ahmedkaludi/pwa-for-wp#488]
An integrated back button to the UI, is the only feature missing to every PWA out there. Wish PWA for Wordpress would offer this possibility.

Thanks.

**Comment by Anticosti** [comment]
Is there any ETA for this long needed feature?
Thanks!

**Comment by Anticosti** [comment]
?

**Comment by ajeetku** [comment]
https://pwa-for-wp.com/2021/08/03/addon-navigation-bar-for-pwa-version-1-2/
Released in version 1.2
