### ISSUE TITLE
Need to add a few Offline notice features to the app

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/pwa-for-wp#489]
Adding features that are similar to the Call to Action banner but for the PWA installed app, it should be able to tell the user they don't have an internet connection and inform them (via a button for a popup?) what services are/are not available, as well as that the data they see is cached/old.
Link:
https://secure.helpscout.net/conversation/1252720496/148194?folderId=3514643

**Comment by ajeetku** [comment]
Released in 1.7.28
