### ISSUE TITLE
The Spalsh icon size gets increasing in the APK

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#491]
Ref: https://secure.helpscout.net/conversation/1252381260/148144/

Screenshot:
Normal PWA: https://prnt.sc/tzedk8
APK:https://prnt.sc/tzedvt

**Comment by mysecretlifeadmin** [comment]
Good morning @ahmedkaludi  do you have any idea how long it will take to assign and solve this ticket?
I would like to fix this issue before to launch my App with advertisement.
Thank you for your reply.
kind regards,
Manuela

**Comment by ajeetku** [comment]
@MSLadmin we have resolve the issue and release it in version 1.1. 
Please check on updated version

**Comment by ajeetku** [comment]
Pushed in PWA to APK - version 1.1
