### ISSUE TITLE
Need to wrap all the texts of the PWA plugin in the text domain

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#493]
Ref: https://secure.helpscout.net/conversation/1251806260/147939?folderId=2770545

We need to wrap all the texts in the texts of our plugin in the text domain so that it gets translated properly.

For example one screenshot: https://i.imgur.com/fct6lXn.png

The user wants all the text in the Portuguese format.

Ref URLs:
https://developer.wordpress.org/themes/functionality/internationalization/
https://developer.wordpress.org/themes/functionality/internationalization/#how-to-internationalize-your-theme
https://developer.wordpress.org/themes/functionality/internationalization/#add-text-domain-to-strings

**Comment by ajeetku** [comment]
Released in 1.7.19
