### ISSUE TITLE
The loader icon are not showing if the "Deep" theme is active

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#494]
Ref: https://secure.helpscout.net/conversation/1251806260/147939?folderId=2770545

If the "Deep" theme is active then the loader icon are not showing. It gets merged. The issue also occurs on the local.

Screenshot: https://prnt.sc/u0yw17

**Comment by ajeetku** [comment]
Released in version "loading icon library" 1.4
