### ISSUE TITLE
Option to style: Release to refresh | Refreshing

### ISSUE THREAD

**Issue by Anticosti** [ahmedkaludi/pwa-for-wp#495]
Would be so great to be able to style **_Release to refresh_** and **_Refreshing_** : font-family (color; size; padding; ...) and backgound (color; opacity; padding; ...)

Thanks!

**Comment by ajeetku** [comment]
f1ac571

**Comment by ajeetku** [comment]
PTR Version 1.6 released

**Comment by Anticosti** [comment]
I am using Pull to Refresh for PWA Version 1.6 and I still don't see the changes

**Comment by ajeetku** [comment]
@Anticosti please connect us on https://pwa-for-wp.com/contact-us/
