### ISSUE TITLE
Data Analytics for PWA slows down Backend

### ISSUE THREAD

**Issue by Anticosti** [ahmedkaludi/pwa-for-wp#506]
I am on a Litespeed server with Litespeed Cache plugin, using Oxygen Builder.
I was encountering a real slow backend issue.
I soved this by disactivating _**Memcache**_ and _**Data Analytics for PWA**_
Hope this can be of some help.

**Comment by ahmedkaludi** [comment]
@Anticosti Github is for tested and re-creatable bugs, for support please go to website and send us a ticket via contact  page.
