### ISSUE TITLE
PWA for html

### ISSUE THREAD

**Issue by medilef** [ahmedkaludi/pwa-for-wp#51]
Hi, is there any shortcode from the plugin to add PWA in my php or html pages (non wordpress).
Thanks

**Comment by Sanjeevsetu** [comment]
Hi, You can't use this plugin outside wordpress but yes there is a way to make your website pwa. For that you need to do custom development on your website.

**Comment by ahmedkaludi** [comment]
@medilef Please contact us on team@magazine3.com for the custom development.
