### ISSUE TITLE
PWA plugin causes crash to my site

### ISSUE THREAD

**Issue by pallomeri** [ahmedkaludi/pwa-for-wp#512]
Hello,

My website https://pallomeri.net crashed this morning. My webhosting is located to Siteground and they support said that the reason why my site get down is because of PWA for WP plugin. I can't access to phpMyAdmin or WP-Admin so it makes quite hard to remove plugin correctly. I deleted plugin's folder from the wp-content/plugins and then three js and json files from the file root.

After that SG's support says that your plugin creates some kind of service worker which causes this error? Is there something more files what should I remove or change so I get rid of the whole plugin?

THANKS!

**Comment by Anticosti** [comment]
Your account panel at SG should let you access phpMyAdmin, without any problem. You then will have to search and delete each pwa option in the option table. Do a database backup first.

**Comment by pallomeri** [comment]
OK. Thanks. The problem is so the phpMyAdmin is stuck as well and I can't reach it. I try to figure out with SG support how to deal this.

**Comment by ahmedkaludi** [comment]
@pallomeri I'm sorry to hear that, can you please contact us via https://pwa-for-wp.com/contact-us/ and our team will fix this issue for you
