### ISSUE TITLE
Need to compatibility with Webpushr Plugin

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/pwa-for-wp#513]
Reference: https://wordpress.org/support/topic/webpushr-integration/

**Comment by amer07** [comment]
Ref no:https://secure.helpscout.net/conversation/1272887523/152484?folderId=2770543

**Comment by sardarui** [comment]
Another User requesting Webpushr Compatibility:
https://secure.helpscout.net/conversation/1278171039/153526?folderId=3126461

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/pwa-for-wp/pull/413

**Comment by ajeetku** [comment]
Released in 1.7.24

**Comment by ajeetku** [comment]
opening this ticket some confusion with #409
so opening this ticket

**Comment by ajeetku** [comment]
Released in 1.7.25,
Minor changes added release will be upcoming update
