### ISSUE TITLE
Offline pre-caching issue:  gravity form wizard is not working

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/pwa-for-wp#516]
gravity Form works fine online, but when offline it says "site can't be reached"
Ref: https://secure.helpscout.net/conversation/1264495242/150513?folderId=3514643
Screengrab: https://monosnap.com/file/E0jVipOkvQ6FaJNMWzKs0h1BTzcOTL
[Gravityy form.zip](https://github.com/ahmedkaludi/pwa-for-wp/files/5186424/Gravityy.form.zip)

**Comment by akashagrjsr** [comment]
One more user is facing the issue:
https://secure.helpscout.net/conversation/1284914628/154972?folderId=2770545

**Comment by About2git** [comment]
I am too facing the same issue…

**Comment by ajeetku** [comment]
@About2git, please contact to support team

**Comment by ajeetku** [comment]
@akashagrjsr #539 has created for this issue

**Comment by akshaywali** [comment]
update pushed in Offline Forms for PWA for WP 1.8
