### ISSUE TITLE
Need to make an option that would let the user add a custom icon for the notifications that are sent out.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/pwa-for-wp#517]
In Progressive Web App's, when we push a notification to the mobile device; we get Chrome's default icon in the Notification System Tray. 

Need to make an option that would let the user add a custom icon.

Reference: https://secure.helpscout.net/conversation/1275512141/153085?folderId=3514643

**Comment by ajeetku** [comment]
Released in pwaforwp 1.7.23
