### ISSUE TITLE
Homepage goes blank: When PWA, push notification and Auto optimize are activated.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/pwa-for-wp#518]
Homepage goes blank: When PWA, push notification and Auto optimize are activated.

reference: https://secure.helpscout.net/conversation/1266600470/150966?folderId=3514643

**Comment by techzotezo** [comment]
Any solution found? I am really waiting to fix this issue...to make it live...

**Comment by techzotezo** [comment]
Any update?

**Comment by ajeetku** [comment]
Locally not recreated: PWA for wp+ pusnotification+ autoptimize
communication with user

**Comment by ajeetku** [comment]
Check with the user side all active plugins, the issue not re-occurred, for now closing this ticket.
Open a ticket if you found the issue.
