### ISSUE TITLE
Issue in ios device safari browser, In Form date picker fields  when we click on next month in it then it Causing Page to Refresh, 

### ISSUE THREAD

**Issue by ghost** [ahmedkaludi/pwa-for-wp#523]
https://secure.helpscout.net/conversation/1272916661/152489?folderId=2632030

The form is present in this below URL:

https://portal.claytonstowing.com.au/hr-forms/leave-application/

The issue is shown in this video: 
https://wetransfer.com/downloads/0087dca1dbab58951a46e440bfd14f4c20200908065404/f15f7d

The issue appears only ios device.

**Comment by ajeetku** [comment]
issue related to specific js  library

**Comment by Sanjeevsetu** [comment]
We have released too many version since this issue. It might have been fixed. Please try latest version and let us know
