### ISSUE TITLE
If the Offline Google analytics option in the PWA option panel then showing workbox console error showing

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#524]
Screenshot: https://prnt.sc/uh2f6z

Ref: https://secure.helpscout.net/conversation/1251806260/147939?folderId=2770545

**Comment by ajeetku** [comment]
This issue occurs because of adblocker, that's the cause of the whole service worker is blocked. Added fix to avoid the error.

**Comment by ajeetku** [comment]
Fix applied 
released in current version 1.7.22
