### ISSUE TITLE
If the scroll to progress bar plugin is active then getting the 404 console error

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#525]
Ref: https://secure.helpscout.net/conversation/1251806260/147939?folderId=2770545

Screenshot: https://prnt.sc/uh1q94

**Comment by ajeetku** [comment]
The issue came because of non exists URL on the preaching URLs list.
these URL always send 404 headers, resolved after clear the precaching list.
