### ISSUE TITLE
The plugin breaks my website

### ISSUE THREAD

**Issue by bzoum** [ahmedkaludi/pwa-for-wp#527]
I write here because I cannot get any support from you. You don't answer to my emails.

My issue is that your plugin triggers the firewall of my hosting provider which then blocks all the script/plugin of my website.
I was able to decrease the iteration of the bugs by selecting this option:

"PWA alternative method | Enable(check) it when PWA with OneSignal or root permission functionality not working because of Cache"

I don't understand why. I would like you to answer my emails.

Please tell me if you don't support anymore this plugin.

Thank you.

**Comment by ajeetku** [comment]
@bzoum bzoum Sorry for this issue, we can resolve this issue immediately. Can you please tell me your reference ticket no.
so I can find and reply you.

**Comment by ahmedkaludi** [comment]
Github is for tested and re-creatable bugs, for support please go to https://pwa-for-wp.com/contact-us/
