### ISSUE TITLE
AMP Pages/post (amp by Automattic) is not loading the content, when Loading Icon Library for PWA is enabled

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/pwa-for-wp#528]
Use: when Loading Icon Library for PWA functionality is enabled amp page/post is not showing the content it is keep on loading.

Ref: https://monosnap.com/file/fIah63g7DBPaSTXKuxIJGdwIfYbvbx

https://secure.helpscout.net/conversation/1282352698/154366?folderId=2632030

AMP setting options view:  https://monosnap.com/file/AkRTHK0u0edk8nZpC7zRVMbcVkzhGd

**Comment by ajeetku** [comment]
Released in PWA version 1.7.21
