### ISSUE TITLE
Need to add support of sending push notification to users when the order status changed.

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/pwa-for-wp#531]
User wants to send push notifications to customers when the order status changes thebelow is plugin which is used for changing the status of the order.

Ref plugin:https://wordpress.org/plugins/delivery-drivers-for-woocommerce/#:~:text=Delivery%20Drivers%20for%20WooCommerce%20offers,Time%20saved%20is%20money%20earned

Ref:https://secure.helpscout.net/conversation/1287110676/155313?folderId=3575684.

**Comment by lgdelai** [comment]
Very Nice 👍
Thanks.

**Comment by ajeetku** [comment]
PN Released in version 1.14

**Comment by lgdelai** [comment]
Hello  @ahmedkaludi 

Do you mean that the feature I requested has been implemented?

Where do I find instructions for setting up the feature?

Thankful.

**Comment by ajeetku** [comment]
Yes in pushnotification plugin we have added this feature, when order status will change it will send the notification
