### ISSUE TITLE
Need to create an option to show the pop-up after some 'x' days again .

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/pwa-for-wp#532]
When the customer makes the select the NO in the pop-up banner of the  push notification for the first time. So we need to create an option to show pop-up again for X days .So that notification will be shown to them again.

Ref:https://secure.helpscout.net/conversation/1288944696/155581?folderId=3575684.

**Comment by ajeetku** [comment]
Released in push-notification 1.22
