### ISSUE TITLE
Need to create a option for loader background color change(Loader).

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/pwa-for-wp#533]
Case 1:https://secure.helpscout.net/conversation/1283556220/154686?folderId=2770543

User scenario: if we want to refresh the page it defaults  shows white background, but the user need change back color because he loader icon looks good on the back background like this(https://prnt.sc/umc0xu)
Option:https://prnt.sc/umc18g

**Comment by ajeetku** [comment]
Released in version 1.7.21
