### ISSUE TITLE
Issue with the Loading Icon alignment.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/pwa-for-wp#535]
By default loader Icon is placed sightly left - Need to align this in the center.

Ref Screenshot: https://prnt.sc/uo9whq
Ref URL: https://expo.reflectionsonpeace.org
Ref Ticket: https://secure.helpscout.net/conversation/1292161212/156010/

**Comment by ajeetku** [comment]
Released in PWA version 1.7.21
