### ISSUE TITLE
Need to hide  add to home CTA bar in the IOS chrome browser and the MAC os Safari browser

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#537]
Ref: https://secure.helpscout.net/conversation/1293751726/156358?folderId=2770545

As the CTA bar is will not function properly for the MAC Safari browser and the IOS chrome browser because the MAC and IOS are not supporting it. So, we need to give an option to hide the CTA bar on the given devices for particular browsers.

Screenshot:
1. https://prnt.sc/up3nxl
2. https://prnt.sc/up3p3i

**Comment by ajeetku** [comment]
For the IOS Chrome browser, we have to show instructions: how to add the PWA app
