### ISSUE TITLE
Need to add customized navigation tab bar in PWA.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/pwa-for-wp#541]
One of our users is requesting to add the navigation tab bar in PWA.

Please check the below screenshot of the exact requirement:
1) https://prnt.sc/uwkf0w
2) https://prnt.sc/uwkerl

The user requesting icons for home, contact us, about in conversation as a reference.

Ref URL: https://secure.helpscout.net/conversation/1278171039/153526?folderId=3126461#thread-3748112888

**Comment by ajeetku** [comment]
Released in version 1.7.33
