### ISSUE TITLE
Need to create a new feature: That would let us push notification to only a selected users.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/pwa-for-wp#542]
What a user needs is a way to send a notification to a selected user and not broadcast to all users. Client wants to send a user a message stating that they have new information waiting for them on the website.

like push notifications to the messages, one receives on their phone informing of something new.

**Comment by Sanjeevsetu** [comment]
This feature is now available on https://wordpress.org/plugins/push-notification/ pro version.
