### ISSUE TITLE
Issue with the App Icon varies with screensize of the devices.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/pwa-for-wp#544]
User's scenario:
The user is placing both App Icon and splash screen Icon differently and trying to install the app on the home screen - for the small screen mobile's, App Icon is showing perfectly. but for the large screen mobile's, App Icon is fetching splash screen's Icon.

So App icon needs to be the same for both large & small screen mobiles(showing perfectly in iPhone devices).

We can check the same issue in the BrowserStack:
URL: https://breaddiction.com/
Small device like: Galaxy S4 (Screenshot: https://prnt.sc/v2uxlx)
Large device like: Oneplus 7 (Screenshot:https://prnt.sc/v2uz54)

Ref Ticket: https://secure.helpscout.net/conversation/1310353855/159431/

**Comment by ajeetku** [comment]
Changes are done on the server
