### ISSUE TITLE
Need to add feature to change the time zone for the pushnotifications.io

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#546]
Ref: https://secure.helpscout.net/conversation/1313500692/160166?folderId=2770545

Screenshot:
 https://prnt.sc/v3hutr
https://prnt.sc/v3hvhm

The user wants to change the timezone for the Kuala Lumpur, Malaysia.

**Comment by ajeetku** [comment]
Changes applied to Push-notification server
