### ISSUE TITLE
Add to home screen appearing button, even after install it.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/pwa-for-wp#549]
Ref: https://secure.helpscout.net/conversation/1314607862/160302?folderId=2770543

If you app after install via add to home screen, and still menu download button shows on pwa app.

Screenshot:https://monosnap.com/file/eQjoKTFEAHCFR0QYT6I0OUgpy0cBw9

**Comment by ajeetku** [comment]
CTA: 262c89f

**Comment by ajeetku** [comment]
Resolved in  CTA 1.8.8
