### ISSUE TITLE
Add some more designs for the push notification popup

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/pwa-for-wp#550]
Need to Add some more designs for the push notification popup to look more attractive for example(https://prnt.sc/v7s939).

Ref:https://secure.helpscout.net/conversation/1320243499/161436?folderId=3575684

**Comment by Sanjeevsetu** [comment]
Related #https://github.com/ahmedkaludi/push-notification/issues/76 and It will come in next push-notification version 1.34
