### ISSUE TITLE
Need to create an option in the push notification to schedule a push notification for a specific date/time

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/pwa-for-wp#557]
Need to create an option in the push notification to schedule a push notification for a specific date/time.

Ref: https://secure.helpscout.net/conversation/1344097397/166044?folderId=3575684

**Comment by Sanjeevsetu** [comment]
Schedule a push notification is now available in Push Notifications for WP & AMP. https://wordpress.org/plugins/push-notification/
