### ISSUE TITLE
Add .po and pot file to translate the text of pull to refresh

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/pwa-for-wp#559]
Translate text of pull to refresh plugin

**Comment by akashagrjsr** [comment]
Ref:https://secure.helpscout.net/conversation/1358816874/168635?folderId=2770545

This user requested this. The user wants to translate the "Pull down to refresh" and the "Release to refresh" in the French language.

**Comment by ajeetku** [comment]
d6ddb6b, 37497c0

**Comment by ajeetku** [comment]
PTR Version 1.6 released
