### ISSUE TITLE
Need to add an expire date for the cookies.

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/pwa-for-wp#560]
Need to add an expiration date for the cookies. Because when we allow the notification for the first time the cookies are created. but when we open the same website in the same browser it is asking for the notification again it is happing because cookies are has removed(https://prnt.sc/vy0e1o.)and the cookies are in the session state. So that reason why the notification is asking again. If we create an expiration date for the cookies will stay till that certain time.

Ref: https://secure.helpscout.net/conversation/1329827682/163729?folderId=3575684

**Comment by ajeetku** [comment]
PN : 49257bc

**Comment by ajeetku** [comment]
Released in PN version 1.15
