### ISSUE TITLE
The change in the package id of PWA APK is not reflecting in the assetlinks.json file

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#562]
Ref: https://secure.helpscout.net/conversation/1367696527/170623?folderId=2770545

When the user is changing the package id (https://prnt.sc/w56z6o) from the setup and generating the APP, then package id name is not reflecting in the assetlinks.json  file

**Comment by ajeetku** [comment]
Released in 1.2 PWA to APK
