### ISSUE TITLE
Need to add prefetch with manifest in HTML pages

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/pwa-for-wp#564]
Prefetches URLs to the links (using <link rel=prefetch> or XHR). Provides some control over the request priority (can switch to fetch() if supported).

WordPress ref: https://wordpress.org/support/topic/purpose-header-missing/
Ref: https://github.com/GoogleChromeLabs/quicklink

**Comment by ajeetku** [comment]
Released in 1.7.28
