### ISSUE TITLE
Need to implement file upload feature support in the PWA "Offline Forms for PWA for WP "

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#565]
Ref: https://secure.helpscout.net/conversation/1382367337/172900?folderId=2770545

We need to implement the file upload support in the "Offline Forms for PWA for WP " plugin. When the user is submitting the form added through the Gravity form plugin then the form is not submitting.

Reference video:
https://drive.google.com/file/d/1KCOIA9WQzQvsQW88ODjN1yN5xKKDScUd/view?usp=sharing

Link: https://offline.dcnsafe.com/

**Comment by sardarui** [comment]
Another User facing the same issue.

Ref Ticket: https://secure.helpscout.net/conversation/1507064035/195311?folderId=3126461

**Comment by ajeetku** [comment]
Released in OF 1.2
