### ISSUE TITLE
Add quick action feature for PWA

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/pwa-for-wp#566]
User gets a quick access to module in App without open the app by holding a tap on the app icon.

WordPress Ref: https://wordpress.org/support/topic/feature-app-shortcuts/

https://web.dev/app-shortcuts/

**Comment by Sasirekhamarella** [comment]
A user wants to Update the Apps with the Shortcuts Function.

Ref ticket: https://wordpress.org/support/topic/shortcuts-3/#post-14258431

**Comment by ajeetku** [comment]
Released in version 1.7.33
