### ISSUE TITLE
The loading icons are not loading at users end

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#568]
Ref: https://secure.helpscout.net/conversation/1401110591/176337?folderId=2770545

After adding the below CSS code in the plugin, the issue got fixed.

.pwaforwp-loading-wrapper{
 z-index: 9999999;
}

**Comment by Anticosti** [comment]
Nice fix. Thanks. Now what about fixing the background transparency color?
I tried adding this:
background-color: rgba(0,0,0,0.6)!important;
not working :(

**Comment by Anticosti** [comment]
![Capture d’écran, le 2021-01-24 à 00 11 49](https://user-images.githubusercontent.com/5446224/105621740-de5eb580-5dd8-11eb-93ef-5cd570582fe8.png)

**Comment by ajeetku** [comment]
@Anticosti will create another ticket for it https://github.com/ahmedkaludi/pwa-for-wp/issues/575

**Comment by akashagrjsr** [comment]
one more user is facing this issue: https://secure.helpscout.net/conversation/1434149978/182124?folderId=2770545

**Comment by ajeetku** [comment]
Released in 1.7.29
