### ISSUE TITLE
Need to create an option to show the Pop-up after the "Nth " seconds.

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/pwa-for-wp#570]
Need to create an option to show the Pop-up after the "Nth " seconds.

This option is will help the user to set up a time for displaying the pop-up banner. This feature is available in the "Webpushr.com" plugin (https://prnt.sc/xyinaa).

Ref:https://secure.helpscout.net/conversation/1408918245/177647?folderId=3575684.

**Comment by ajeetku** [comment]
Released in push-notification 1.22
