### ISSUE TITLE
Need to create an option to display the banner  after the nth page view.

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/pwa-for-wp#571]
Need to create an option to display the banner after the nth page view.

The option " Show after nth page view " helps the user to set up the. banner after nth pages view. For example 
If I select n=2 it will show a notification option to the user after 2 pages first he visited that page and second (current page). This feature is available on webpushr.com(https://prnt.sc/xyiwsj).

Ref:https://secure.helpscout.net/conversation/1408918245/177647?folderId=3575684

**Comment by ajeetku** [comment]
Released in push-notification 1.22
