### ISSUE TITLE
Need to add the different markups for the regular icons and the maskable icons

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#573]
Ref: https://secure.helpscout.net/conversation/1387838996/174073?folderId=2770545

We are currently adding the anymaskable attribute for the "regular and maskable icons".

Screenshot: https://prnt.sc/y9bw7k

but we need to add the "any" and "maskable" attributes separately like this:
{
  …
  "icons": [
    …
    {
      "src": "path/to/regular_icon.png",
      "sizes": "196x196",
      "type": "image/png",
      "purpose": "any"
    },
    {
      "src": "path/to/maskable_icon.png",
      "sizes": "196x196",
      "type": "image/png",
      "purpose": "maskable" // <-- New property value `"maskable"`
    },
    …
  ],
  …
}

Ref: https://web.dev/maskable-icon/

**Comment by ajeetku** [comment]
Released in 1.7.29
