### ISSUE TITLE
Add option to select loader background color

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/pwa-for-wp#575]
Request from user to add a background of the loader; currently its white color blank (already presents): **Need to add color picker alpha options**
Ref: https://github.com/ahmedkaludi/pwa-for-wp/issues/568#issuecomment-766293087

**Comment by Anticosti** [comment]
Please add the the possibility to control alpha for the background color.
Thank you!

**Comment by ajeetku** [comment]
Released in PWA version 1.7.30
