### ISSUE TITLE
Add an option to select “apple-mobile-web-app-status-bar-style” property based on user requirement

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/pwa-for-wp#580]
WordPress ref: https://wordpress.org/support/topic/status-bar-on-ios/

**Comment by ikihi** [comment]
Hi… unfortunately I have exactly that issue, and in my site it is a problem…

What happens, is that I have a toolbar on top of my site. and with the transparency of the iPhone toolbar, I can see how my page goes up in the back of the toolbar, but it shows again in the transparent layer…

It looks horrible

Was that effect made on purpose? Or is a mistake…

Hopefully you guys can come out with a new release soon!

I will really appreciate it…

And thanks in advance…

In the meantime, is there a way to download somewhere the previous version of the plugin… to go back one step?

**Comment by ajeetku** [comment]
@ikihi Sorry for the inconvenience, we just want to give a more attractive look to PWA APP like native APPs have option where tools bar also in the same color.

we make it in the proper way and optional on user selection. in next update
Thank you for your cooperation.

**Comment by ikihi** [comment]
I love your plugin, and honestly i think is the best out there for PWA... it just has all the needed tools...

This new version was really good idea and with exiting couple of new features, like to be able to set a biger icon for the android splash screen

the issue on the iphone, is that it didn't matter what way I set the plugin to look in the phone (fullscreen, standalone, etc) they all had the same issue on top of the screen... so my page with the toolbar looked terrible

So it will be great if that becomes optional....

But great job!!

love it...

**Comment by ajeetku** [comment]
Released in PWA version 1.7.30

**Comment by ikihi** [comment]
Excellent!!!!!! is perfect again..!

Thanks ajeetku
