### ISSUE TITLE
OneSignal compatibility issue.

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/pwa-for-wp#581]
OneSignal compatibility issue. One signal pop-up is not working when PWAforWP is enabled.
 -> Admin-ajax.php with GET parameter calling unnecessary when both one signal and PWA is activated.

Ref screenshot1: https://prnt.sc/10b4bzh 
Ref screnshot2: https://prnt.sc/10b4cl1

Ref: https://secure.helpscout.net/conversation/1433706254/182072?folderId=3575684

**Comment by ajeetku** [comment]
Released in PWA version 1.7.30
