### ISSUE TITLE
Need enhancement in the Woo-commerce push notification Regarding the order status

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/pwa-for-wp#585]
Need enhancement in the Woo-commerce push notification Regarding the order status

Need to create an option where we can select the subscribers for whom we want to send a notification of order change  also 
we need to create an option where order change notification should go to admin only.

Ref: https://secure.helpscout.net/conversation/1446182390/184378?folderId=3575684

**Comment by ajeetku** [comment]
Released in PN 1.18
