### ISSUE TITLE
Issue is BuddyPress for PWA for WP extesnion is not working at user end.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/pwa-for-wp#588]
User is having a perfect setup with BuddyPress for PWA for WP along with the PWA and Pushnotification but the thing is Buddypress notification is not receiving, there is a 3rd party plugin conflicting issue at the user end, and here is the list of plugins at user end.

- Asset CleanUp : Page Speed Booster
- BP Better MessagesBuddyPress
- Elementor
- Image optimization service by Optimole
- Nextend Social Login
- Smash Balloon Instagram FeedYoast SEO

We need to work on this and try to resolve this issue in the next update.

Ref Ticket: https://secure.helpscout.net/conversation/1448314799/184824/

**Comment by ajeetku** [comment]
Released in BuddyPress for PWA for WP 1.2 version
