### ISSUE TITLE
How to setup PWA for Multisite

### ISSUE THREAD

**Issue by Usama-Aslam** [ahmedkaludi/pwa-for-wp#589]
I have wordpress site with url something like this
**www.example.com/ShopA
www.example.com/ShopB**

How to Configure PWA plugin separate for each shopA with separate starturl for both.

**Comment by ajeetku** [comment]
@Usama-Aslam you can activate PWA for both site separately or with whole network. Its will manage automatically.
if you face any issue, please contact us on https://pwa-for-wp.com/contact-us/

**Comment by ajeetku** [comment]
Closing this ticket
