### ISSUE TITLE
Chrome has improved the PWA offline detection 

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/pwa-for-wp#591]
https://developer.chrome.com/blog/improved-pwa-offline-detection/

Need to change the caching strategy for offline caching

**Comment by laharikakuna** [comment]
Another user also encountering the same issue.

Ref screenshot: https://prnt.sc/10pmdx6

Ref URL: https://guides-guide.org/

Ref: https://secure.helpscout.net/conversation/1456714821/186628?folderId=3575684

**Comment by ajeetku** [comment]
Apparently, due to issues with the new installability check, the Chrome team decided to call off the change for now:  [updated blog post](https://developer.chrome.com/blog/improved-pwa-offline-detection/)

The warning will be removed around Chrome v90.
--------------------------------------------------------------------------

**Comment by ajeetku** [comment]
closing the issue of this ticket is resolve by chrome
