### ISSUE TITLE
Issue with the Save settings 

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/pwa-for-wp#592]
Here is the User scenario in detail:

When the user sets "background-color & theme color" and clicks on the save button, the user is prompted with the success message but the values for background-color & theme color are not been saved.

Issue setting screenshot:  https://prnt.sc/10mcvbm
user issue URL: https://wordpress.org/support/topic/issue-with-spash-screen-settings/

**Comment by laharikakuna** [comment]
Another user also encountering a similar issue:

when the user has set up the background color for the banner in the "Custom home screen banner" block and clicks on the save changes button. The user is receiving the prompt with "settings saved" but when we refresh the options panel the setting which has been made are not reflecting.

Ref screenshot:https://prnt.sc/10u8ywj

Ref: https://secure.helpscout.net/conversation/1460669829/187332?folderId=3575684.

**Comment by ajeetku** [comment]
Released in PWA for WP version 1.7.31
