### ISSUE TITLE
The "APK not created try later" error occurring while generating new APK

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#593]
Ref: https://secure.helpscout.net/conversation/1376491872/171841?folderId=2770545

Screenshot: https://prnt.sc/10plybt

When the user is going to create the new APK, he is getting the error message "APK not created try later". The issue is only at user's end.

**Comment by ajeetku** [comment]
Closing, The issue is resolved on the user site.
