### ISSUE TITLE
The splash icon is not generating for the IOS device

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#596]
Ref: https://secure.helpscout.net/conversation/1458629083/186948?folderId=2770545

When the user is generating the splash screen with the automatic setup, the only background color is coming, the splash screen image is not generating.

When we click on any splash screen image it is not redirecting to the correct image URL
view-source:https://extranet.izb.org.pl/

URL: https://extranet.izb.org.pl/

The issue is very strange and happening due to some JS conflict. 
Screenshot: https://prnt.sc/10tcn94

The issue is not occurring on our local.

**Comment by ajeetku** [comment]
283357a related to this ticket

**Comment by ajeetku** [comment]
Released in PWA for wp version 1.7.31
