### ISSUE TITLE
Call to action is not working and offline content not present

### ISSUE THREAD

**Issue by petrone7** [ahmedkaludi/pwa-for-wp#599]
Hello, 
I am having a lot of problems with the call to action in my site https://test.rozzenmx.com/app/ where we have the CTA and pwa for wp plugins but none of the call to actions are showing (sticky bar, menu or shortcode). It seems that all the components are in the page but all are with the style "display none" (attached). 
We are getting a console error with a 400 response in the admin-ajax.php call (attached) and also I noticed that chrome is not allowing anymore the bar for installation if not offline content is present but I don't know how to resolve this.
Also, when I try to set the background color and theme color in the settings, this is not saved and still shows that this items are ' ' in console and in the manifest.json (attached) 
Same thing with the loader, after a while of changing some settings the colors of the loader are set back to default. 

Hope you can help and thanks in advance

![ManifestNotSaving](https://user-images.githubusercontent.com/62819209/113614919-cc8b6100-9618-11eb-89c3-cd43507520b0.JPG)
![adminajaxErr](https://user-images.githubusercontent.com/62819209/113614921-cd23f780-9618-11eb-89e8-5a07f0ad0952.JPG)
![elementsDisplayNoneErr](https://user-images.githubusercontent.com/62819209/113614922-cdbc8e00-9618-11eb-9386-9976f6a46911.JPG)

**Comment by ajeetku** [comment]
please contact us on https://pwa-for-wp.com/contact-us/

**Comment by petrone7** [comment]
I had, 2 times! I’ll try again now

**Comment by ahmedkaludi** [comment]
@petrone7 did you ever get any help from our team?

**Comment by petrone7** [comment]
Hello! I did, thank you very much.
They created an issue here, with the following URL: https://github.com/ahmedkaludi/pwa-for-wp/issues/603
It seems that you guys are working on it, but still is not solved.
Thank you

**Comment by ajeetku** [comment]
@petrone7 are you still getting issue with OneSignal because this issue has fixed(#603).

**Comment by ahmedkaludi** [comment]
Github is for verified issues. 

For Technical issues, contact our support team.

**Comment by petrone7** [comment]
It was a verified issue https://github.com/ahmedkaludi/pwa-for-wp/issues/603 , and you solved it.
Thank you
