### ISSUE TITLE
Users are Requesting to Add push notifications feature too in PWA

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/pwa-for-wp#6]
Desc: What is the benefit if someone installs PWA except offline access? Can we send them to push notifications? If yes then how?

Ref: https://secure.helpscout.net/mailbox/cfb9786cbb6b9b7c/2169251/

**Comment by ahmedkaludi** [comment]
Push Notification through Firebase https://wordpress.org/support/topic/push-notifications-via-firebase/
