### ISSUE TITLE
CTA is not working with OneSignal

### ISSUE THREAD

**Issue by AnupriyaSurapaneni** [ahmedkaludi/pwa-for-wp#603]
When both Push notifications using OneSignal and CTA of PWAforWP are configured, CTA is not displayed.
Code is shown in inspect elements but without any banner on the page. Reference, https://prnt.sc/11bu8db
Ticket - https://secure.helpscout.net/conversation/1475702801/189847?folderId=4074390
FTP and Logins available in the ticket.

**Comment by ajeetku** [comment]
Released in PWA for WP version 17.31
