### ISSUE TITLE
APK file not generating with the site is of type Arabic language

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/pwa-for-wp#604]
Ref: https://secure.helpscout.net/conversation/1455781101/186443?folderId=2632030

https://almazaad.today/111-2/

Getting error as: 
APK not created try later.
ErrorDetails: Error generating app package: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters

![image](https://user-images.githubusercontent.com/46995400/114855488-a8433780-9e03-11eb-9c5f-ab36dec3b54b.png)

**Comment by ajeetku** [comment]
Issue resolved on the server-side

**Comment by ajeetku** [comment]
Closing this ticket
