### ISSUE TITLE
[feature]

### ISSUE THREAD

**Issue by vontainment** [ahmedkaludi/pwa-for-wp#605]
I think a good feature to add would be the ability to add code to the manifest and to the service worker. Like a box we can just put custom code in that will be added to the files. So we can add features like the app icon menus to the manifest and so forth.

**Comment by ajeetku** [comment]
@vontainment we already have filters, you can use them, and your custom features in PWA. For manifest use this `pwaforwp_manifest` filter. and for Service Worker use `pwaforwp_sw_js_template` this filter 

I hope this information will work for you

**Comment by vontainment** [comment]
Are these used in themess functions.php

**Comment by ajeetku** [comment]
please connect us on https://pwa-for-wp.com/contact-us/ for more assistance. team will help you
Closing these ticket for now
