### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Anticosti** [ahmedkaludi/pwa-for-wp#610]
Love his plugin but when comes the time to work in bilingual mode...
Wish you could let us translate these messages:

- Welcome!
- Install
- Install this (My Site) on your iPhone {{ICON_INSTALL}} and then {{bold}} Add to Home Screen {{/bold}}
- Release to refresh
- Refreshing...

I use LocoTranslate

**Comment by ajeetku** [comment]
Released in CTA version 1.8..9
