### ISSUE TITLE
google tag manager not detecting data analytics

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/pwa-for-wp#612]
Ref ticket: https://wordpress.org/support/topic/not-load-google-tagmanager-2/?loggedout=true

**Comment by kumawatvikas** [comment]
![image](https://user-images.githubusercontent.com/63947976/232781728-e7fa7ea1-88cd-4043-93f8-717e03540ab6.png)

it is currently working.

**Comment by kumawatvikas** [comment]
There is no issue found while testing, so closing this ticket.
