### ISSUE TITLE
Naming convention for the extensions 

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/pwa-for-wp#624]
Naming convention for the extensions 

Use case: https://secure.helpscout.net/conversation/1538430265/201417?folderId=2632030

**Comment by ajeetku** [comment]
- [ ] data analytics for pwa
- [ ] scroll progress bar for pwa
- [ ] pull to refresh for pwa
- [ ] call to action for pwa 
- [ ] buddypress for pwaforwp
- [ ] offline forms for pwa for wp
- [ ] quick action for pwa
- [ ] pwa to apk plugin 
- [ ] navigation bar for pwa
- [ ] PWA pro extension manager
- [ ] loading icon library for pwa
- [ ] multilingual compatibility for pwa

**Comment by ajeetku** [comment]
Author: _PWAforWP Team_ With Release
- [ ] data analytics for pwa
- [ ] scroll progress bar for pwa
- [ ] pull to refresh for pwa
- [ ] call to action for pwa 
- [ ] buddypress for pwaforwp
- [ ] offline forms for pwa for wp
- [ ] quick action for pwa
- [ ] pwa to apk plugin 
- [ ] navigation bar for pwa
- [ ] PWA pro extension manager
- [ ] loading icon library for pwa
- [ ] multilingual compatibility for pwa

**Comment by ajeetku** [comment]
All addons are released with the author
