### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by ikihi** [ahmedkaludi/pwa-for-wp#632]
Hi!

Will it be possible to have a back up button (android has a natural button, but IOS doesn't have one)

why I think this will be very useful?

Well in reality what we are tryng to do here is to convert a website in to an app, but still a website...

in my case, I have for example a Buddy press base site

lets say i want o dive in to the profiles of some of the users, starting in the members directory page... each time i get inside a profile to go back to the members directory I have to go up to the main menu, open the tab that contains that tab and click in there

with a back button will be just one clik away

so I think foe our favorite PWA (as this is the one we are using) and love it by the way.... will be super useful to have that button...

Cheers!!!

**Comment by ajeetku** [comment]
https://pwa-for-wp.com/2021/08/03/addon-navigation-bar-for-pwa-version-1-2/
Released in version 1.2
