### ISSUE TITLE
The user's favicon icon is being overridden by the app icon (in iPadOS Chrome) and splash (in iPadOS Firefox)

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/pwa-for-wp#633]
Reference Ticket: https://secure.helpscout.net/conversation/1562344641/205197/

The user's favicon icon is being overridden by the app icon (in iPadOS Chrome) and splash (in iPadOS Firefox) set in the plugin. Need to create a filter to override this function for the favicon icon.

**Comment by ajeetku** [comment]
Released in version 1.7.35
