### ISSUE TITLE
Need to add feature to customize icons size and color on our Navigation Bar addon for pwa.

### ISSUE THREAD

**Issue by kupveja** [ahmedkaludi/pwa-for-wp#634]
Need to add feature to customize icons size and color on our Navigation Bar addon for pwa. 
screenshot - https://prnt.sc/1aiff9c

ref - https://secure.helpscout.net/conversation/1562065156/205149?folderId=4459751

**Comment by ajeetku** [comment]
released in Addon: Navigation bar version 1.1
