### ISSUE TITLE
To create an option for zoom in & zoom out in PWA  

### ISSUE THREAD

**Issue by sanjaydadwani** [ahmedkaludi/pwa-for-wp#636]
Please create an option for zoom in & zoom out in PWA, so that a user can enable or disable this option as per his requirement.
Ticket URL: https://secure.helpscout.net/conversation/1569816420/205995?folderId=4753923

**Comment by ajeetku** [comment]
Use html tag to achive enable this zoom feature <meta name="viewport" content= "width=device-width, user-scalable=no">

Closing this ticket as the user has no response, Feel free to open if the issue reoccurs
