### ISSUE TITLE
Getting "untitled" instead of the app title name in iOS

### ISSUE THREAD

**Issue by kupveja** [ahmedkaludi/pwa-for-wp#638]
While getting the alarm notification on the PWA app on iOS and after clicking the notification, instead of the title app name, user is getting the " untitled " on the left top of the screen which is basically a feature to go back to the previous application.
ref screenshot - https://prnt.sc/1c4qm5s
ref video - in the ticket
ref possible solution - https://stackoverflow.com/questions/41686471/my-iphone-says-my-web-app-is-untitled-when-it-is

ref - https://secure.helpscout.net/conversation/1569493326/205974?folderId=4459751

**Comment by ajeetku** [comment]
Released in Version 1.7.36
