### ISSUE TITLE
Need to Add compatibility of qtranslate/qtranslate-xt in multilingual extension

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/pwa-for-wp#639]
Need to Add compatibility of qtranslate/qtranslate-xt in multilingual extension

Reference URL: qtranslate-x
https://wordpress.org/plugins/qtranslate-x/
qtranslate-xt
https://github.com/qtranslate/qtranslate-xt

Reference Ticket URL: https://secure.helpscout.net/conversation/1588872377/208384?folderId=4409869

**Comment by ajeetku** [comment]
released in 1.3 multilingual addon
