### ISSUE TITLE
Error in browser console Due to addition of slash in the URL

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/pwa-for-wp#64]
Ref: https://secure.helpscout.net/conversation/731866324/45296?folderId=1680016

**Comment by Sanjeevsetu** [comment]
Another user has same issue.

https://wordpress.org/support/topic/trailing-slash-causing-error/

**Comment by davideprevosto** [comment]
Hi there, I suppose issue could be related to `function pwaforwp_front_url()`.

You return `trailingslashit($link);`

And (for example) then you wrote:

```
$url = pwaforwp_front_url();    
	if($src[1]==$url){
		return 'href="'.$url.'/'.PWAFORWP_FILE_PREFIX.'-manifest.json"';
	}else{
		return 'href="'.$url.'/'.PWAFORWP_FILE_PREFIX.'-manifest.json"';
	}
```

Look at the .'/'.
