### ISSUE TITLE
Need to add the feature to send notification to the users via Email in Buddypress for PWA for WP extension.

### ISSUE THREAD

**Issue by kupveja** [ahmedkaludi/pwa-for-wp#641]
Need to add the feature to send notification to the users via Email.

screenshot -https://prnt.sc/1lordgi

reference - https://secure.helpscout.net/conversation/1594392294/209112?folderId=4459751

**Comment by ajeetku** [comment]
Features added in Commit f8dd394 BPPN addon BuddyPress for PWA for WP

**Comment by ajeetku** [comment]
Feature released in version 1.3 addon : "BuddyPress for PWA for WP"
