### ISSUE TITLE
Getting "untitled" instead of the app title name in iOS

### ISSUE THREAD

**Issue by kupveja** [ahmedkaludi/pwa-for-wp#642]
While getting the alarm notification on the PWA app on iOS and after clicking the notification, instead of the title app name, user is getting the " untitled " on the left top of the screen which is basically a feature to go back to the previous application.
ref screenshot - https://prnt.sc/1c4qm5s
ref video - in the ticket

ref ticket - https://secure.helpscout.net/conversation/1569493326/205974?folderId=4459751

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/pwa-for-wp/issues/638

**Comment by ajeetku** [comment]
This issue came on the latest version of iphones https://developer.apple.com/forums/thread/128646

**Comment by petrone7** [comment]
Hello! 
Do you have any solution for this issue? 
Thank you very much

**Comment by akshaywali** [comment]
As of **PWA for WP 1.7.54** , this is already fixed so closing this issue. if anyone face this issue again please open a new ticket
