### ISSUE TITLE
Need to be compatible with multilingual on runtime select the language in the PWA app.

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/pwa-for-wp#646]
Need to be compatible with multilingual on runtime select the language in the PWA app.

Ref : https://secure.helpscout.net/conversation/1602278139/209971?folderId=3575684

**Comment by Marghoob123** [comment]
PWA for WordPress "User selected language in WPML website"
 one more user is asking for same thing
https://secure.helpscout.net/conversation/1602229574/209957?folderId=5044124

**Comment by ajeetku** [comment]
released in 1.3 multilingual addon
