### ISSUE TITLE
Splashscreen is not appearing on ios11 

### ISSUE THREAD

**Issue by ghost** [ahmedkaludi/pwa-for-wp#648]
https://secure.helpscout.net/conversation/1597689644/209458?folderId=2632030

The splash screen is not appearing in the ios 11.

Issue occurring in our test site as well Ref: https://garage3.magazine3.com/app-instal-page/

https://fitwithmarine.com/

**Comment by akshaywali** [comment]
Issue is fixed in update 1.7.53 
**Ref Ticket** : https://github.com/ahmedkaludi/pwa-for-wp/issues/724  Splash screen icon is not working on IOS
