### ISSUE TITLE
Pre-Caching option is automatic get disabled 

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/pwa-for-wp#649]
Reference Ticket URL: https://secure.helpscout.net/conversation/1608146719/210669?folderId=4409869

The pre-Caching option is automatic get disabled if we select the manual option from the settings.
Reference Video: https://monosnap.com/file/Ved99tmLZ2d9fP83iICiVXm3JzZG8C

**Comment by ajeetku** [comment]
Released in version 1.7.37
