### ISSUE TITLE
Compatibility issue with Official AMP Transitional mode

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/pwa-for-wp#651]
Compatibility issue with Official AMP Transitional mode.
CTA not working in AMP
Reference Video: https://take.ms/hhXOS
Pre-Cached issue.
https://take.ms/nNoTX

Reference Ticket URL: https://secure.helpscout.net/conversation/1608146719/210669/

**Comment by ajeetku** [comment]
Released in version 1.7.38
