### ISSUE TITLE
Splash Screens is not working on iPhone 13 Pro.

### ISSUE THREAD

**Issue by sanjaydadwani** [ahmedkaludi/pwa-for-wp#658]
Splash Screens is not working on iPhone 13 Pro due to different screen dimensions.

Ticket URL: https://secure.helpscout.net/conversation/1647261070/214296?folderId=4753923

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/pwa-for-wp/issues/648
This issue is getting from iPhone 11

**Comment by akshaywali** [comment]
Issue is fixed in update 1.7.53 
**Ref Ticket** : https://github.com/ahmedkaludi/pwa-for-wp/issues/724  Splash screen icon is not working on IOS
