### ISSUE TITLE
Need to create a QR code that would install the PWA shortcut on Android or iPhone?

### ISSUE THREAD

**Issue by ankit644** [ahmedkaludi/pwa-for-wp#668]
Need to create a QR code that would install the PWA shortcut on Android or iPhone?
Helpscout link - https://secure.helpscout.net/conversation/1688130141/216953/

**Comment by Sanjeevsetu** [comment]
We already have this feature. Check out link . https://pwa-for-wp.com/extensions/qr-code-for-pwa/
