### ISSUE TITLE
When activating the Sticky Bar option and clicking on it, it can show the PWA popup in IOS(CTA)

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/pwa-for-wp#670]
Ref:https://secure.helpscout.net/conversation/1705080421/218205?folderId=2770543

 The issue for using Call To Action on Chrome for iOS.
When activating the Sticky Bar option and clicking on it, it can show the PWA popup
But it won't show up when I'm using the shortcode button
I thought the shortcode button should trigger the same event as the Sticky Bar did.

The video clip of the issue is in help scout.

**Comment by ajeetku** [comment]
Released in 1.8.10 CTA addon
