### ISSUE TITLE
Navigation Bar and Navigation labels are not working properly 

### ISSUE THREAD

**Issue by mohmmadasim** [ahmedkaludi/pwa-for-wp#673]
Reference ticket - https://secure.helpscout.net/conversation/1713297567/218958?folderId=5633920

The navigation bar icons and navigation label colors are not changing, and the navigation label is also not  working properly 

Also attached few screenshots from the test website 
1 . https://prnt.sc/2259ndy
2.  https://prnt.sc/2259qt2
3.  https://prnt.sc/225imx0

**Comment by ajeetku** [comment]
For user end issue css is overriding,  .pwaforwp-nav-menu-class li a img{width: 21px;}

for generalize solution discussion with user

**Comment by ajeetku** [comment]
Changes are released in 1.3 version of navigation bar
