### ISSUE TITLE
Device Orientation is not working through add to screen app.

### ISSUE THREAD

**Issue by shadab-ahmed23** [ahmedkaludi/pwa-for-wp#674]
Screen Orientation does not work through the app if changed the setting to "follow device orientation" but it works on the browser.

Reference ticket link: https://secure.helpscout.net/conversation/1713395677/218977?folderId=5658730

**Comment by ajeetku** [comment]
Closing this ticket, because this feature manage by option panel (Orientation[default: portrait])
