### ISSUE TITLE
User is requesting for a new feature 

### ISSUE THREAD

**Issue by mohmmadasim** [ahmedkaludi/pwa-for-wp#675]
Reference ticket -  https://secure.helpscout.net/conversation/1717990038/219347?folderId=5633920

user is requesting to make all the wording of the Call To Action extension (button text, popup text, etc) for all browsers instruction pages to be configured in multilanguage and also compatible with the WPML plugin

**Comment by ajeetku** [comment]
Added compatibility in CTA plugin and released
