### ISSUE TITLE
Pre-Caching option is automatic get disabled when we enable manual pre-caching.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/pwa-for-wp#678]
Ref:https://secure.helpscout.net/conversation/1725518381/219916?folderId=2770543

The pre-Caching option is automatic get disabled if we select the manual option from the settings.

**Comment by ajeetku** [comment]
Pre-caching has 2 options
1. automatic
2. Manual
if both options are closed in that case the complete feature is disabled. 
The current feature is working based on this. If none feature is enabled then the complete feature will be disbaled.

Closing this ticket with clarification. open these ticket if found the issue.
