### ISSUE TITLE
Loader not working properly 

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/pwa-for-wp#682]
When we enable loader and check the option only for PWA, it shows on both desktop and mobile whether the option of mobile or desktop checked or not.

Reference helpscout url -: https://secure.helpscout.net/conversation/1751783053/221979?folderId=5893230

**Comment by mariobarretta** [comment]
Hello,
is there some feedback about this bug? 
Thank You

**Comment by ajeetku** [comment]
Released in 1.7.42 PWA

**Comment by mariobarretta** [comment]
ThankYou 
i'll wait to receive update to can test
