### ISSUE TITLE
Offline submission didn't work

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/pwa-for-wp#685]
The offline submission didn't work with our product perfectly as expected but with some other product. 
https://secure.helpscout.net/conversation/1780734410/226793?folderId=2498305

**Comment by akshaywali** [comment]
Update pushed on https://github.com/ahmedkaludi/offline-forms-for-pwa-for-wp/commit/83c1cb9ebfaccc1226635276a3c70aa6bdd1b6ae

**Comment by akshaywali** [comment]
update pushed in Offline Forms for PWA for WP 1.8
