### ISSUE TITLE
Push notification (FCM push notification) are not working 

### ISSUE THREAD

**Issue by mohmmadasim** [ahmedkaludi/pwa-for-wp#689]
Ref; https://secure.helpscout.net/conversation/1755078611/222239?folderId=5633920

Push notification and Ultimate Members' notifications (FCM push notification)  are not working in the PWA and also  getting an error in the chrome console 

Reference screenshot: https://prnt.sc/svlUqQKEfOK8

**Comment by ajeetku** [comment]
Push in version 1.7.44
