### ISSUE TITLE
Not working for Multisite, multiple bugs found

### ISSUE THREAD

**Issue by techmagus** [ahmedkaludi/pwa-for-wp#69]
Hi,

  I think I figured out why the plugin isn't loading in a Multisite setup. One has to only look at the source apparently and the files generated by the plugin.

  Basically, it all comes down [1] incorrect domain name; and [2] incorrect filenames. Filenames not mentioned below that the plugin generated have a correct domain name and correct filename.

  I hope this is more than enough for this particular Multisite setup bug report.

  Thank you very much.

### view-source:https://jcsesecuneta.com/
`<link rel="manifest" href="https://jcsesecuneta.com//pwa-manifest.json" />`
comments:
1. **BUG:** double slash
2. **BUG:** it should be pwa-manifest-1.json; there is no "pwa-manifest.json" file in a multisite setup

`<script src="https://jcsesecuneta.com//pwa-register-sw.js" type="02da704670a9c27da53181e9-text/javascript"></script>`
comments:
1. **BUG:** double slash
2. **BUG:** it should be pwa-register-sw-1.js; there is no "pwa-register-sw.js" file in a multisite setup

### view-source:https://jcsesecuneta.com/tpl/
`<link rel="manifest" href="https://jcsesecuneta.com//pwa-manifest.json" />`
comments:
1. **BUG:** double slash
2. **BUG:** it should be pwa-manifest-2.json; there is no "pwa-manifest.json" file in a multisite setup

`<script src="https://jcsesecuneta.com//pwa-register-sw.js" type="b31106163fc57b4070e72cb0-text/javascript"></script>`
comments:
1. **BUG:** double slash
2. **BUG:** it should be pwa-register-sw-2.js; there is no "pwa-register-sw.js" file in a multisite setup

### view-source:https://techmagus.icu/
`<link rel="manifest" href="https://jcsesecuneta.com//pwa-manifest.json" />`
comments:
1. **BUG:** double slash
2. **BUG:** it should be pwa-manifest-6.json; there is no "pwa-manifest.json" file in a multisite setup
3. **BUG:** incorrect domain name, it should be https://techmagus.icu

`<link rel="manifest" href="https://jcsesecuneta.com//pwa-manifest.json" />`
comments:
1. **BUG:** double slash
2. **BUG:** it should be pwa-manifest-6.json; there is no "pwa-manifest.json" file in a multisite setup
3. **BUG:** it was already declared earlier
4. **BUG:** I'm suspecting this is a OneSignal declaration, OneSignal manifest was setup as "https://techmagus.icu/pwa-manifest-6.json" and yet here it shows "https://jcsesecuneta.com//pwa-manifes.json". The plugin is overriding OneSignal with an incorrect link.
5. **BUG:** incorrect domain name, it should be https://techmagus.icu

`<link rel="manifest" href="https://jcsesecuneta.com/pwa-push-notification-manifest-6.json">`
comments:
1. **BUG:** Incorrect domain name. It should be https://techmagus.icu
2. Correct filename

`<script type="3e81d23cceed41e833cfaf47-text/javascript" src='https://techmagus.icu/wp-content/plugins/pwa-for-wp/assets/pwa-push-notification-6.js?ver=1.0.5'></script>`
comments:
1. Correct domain name
2. Correct filename

`<script src="https://jcsesecuneta.com//pwa-register-sw.js" type="3e81d23cceed41e833cfaf47-text/javascript"></script>`
comments:
1. **BUG:** double slash
2. **BUG:** it should be pwa-register-sw-6.js; there is no "pwa-register-sw.js" file in a multisite setup
3. **BUG:** incorrect domain name, it should be https://techmagus.icu

### view-source:https://snoworld.one/
`<link rel="manifest" href="https://jcsesecuneta.com//pwa-manifest.json" />`
comments:
1. **BUG:** double slash
2. **BUG:** it should be pwa-manifest-6.json; there is no "pwa-manifest.json" file in a multisite setup
3. **BUG:** incorrect domain name, it should be https://snoworld.one

`<link rel="manifest" href="https://jcsesecuneta.com//pwa-manifest.json" />`
comments:
1. **BUG:** double slash
2. **BUG:** it should be pwa-manifest-6.json; there is no "pwa-manifest.json" file in a multisite setup
3. **BUG:** it was already declared earlier
4. **BUG:** I'm suspecting this is a OneSignal declaration, OneSignal manifest was setup as "https://snoworld.one/pwa-manifest-4.json" and yet here it shows "https://jcsesecuneta.com//pwa-manifes.json". The plugin is overriding OneSignal with an incorrect link.
5. **BUG:** incorrect domain name, it should be https://snoworld.one

`<link rel="manifest" href="https://jcsesecuneta.com/pwa-push-notification-manifest-4.json">`
comments:
1. **BUG:** Incorrect domain name. It should be https://snoworld.one
2. Correct filename

`<script type="11627d34e2874dda545ca335-text/javascript" src='https://snoworld.one/wp-content/plugins/pwa-for-wp/assets/pwa-push-notification-4.js?ver=1.0.5'></script>`
comments:
1. Correct domain name
2. Correct filename

`<script src="https://jcsesecuneta.com//pwa-register-sw.js" type="11627d34e2874dda545ca335-text/javascript"></script>`
comments:
1. **BUG:** double slash
2. **BUG:** it should be pwa-register-sw-4.js; there is no "pwa-register-sw.js" file in a multisite setup
3. **BUG:** incorrect domain name, it should be https://snoworld.one

Other details:
* Wordpress: 5.0.3
* Multisite: Yes
* PWA for WP: Version 1.0.5
* Network activated: Yes
* Tested non-network_activated: Yes, same result

Custom Multisite Domain Mapping plugin for Wordpress:
* WordPress MU Domain Mapping - Version 0.5.5.1 | By Donncha O Caoimh

If you need anything else, please do reply back. However, we can not provide server access (ftp, ssh). If there are files you need to check that are not available by browser access, please do tell and I'll upload those in this report.

Again, thank you very much.

(PS. Huge timezone difference if your team is in the Western hemisphere.)

Regards,

**Comment by Sanjeevsetu** [comment]
Hi @techmagus,

Thank you so much. 

Did you try with our latest 1.0.6. Here double slash errors wont come. 

**BUG: it should be pwa-register-sw-4.js; there is no "pwa-register-sw.js" file in a multisite setup**

Regarding above bug, We have debugged the issue and can see all the file names are coming with postfix (-blogid) (like pwa-register-sw-4.js ) but after appending to href it is being changed to  (pwa-register-sw.js) so "-4" is being removed after appending to link href so have may be some of your plugins do this please check it again and let us know.

**Comment by Sanjeevsetu** [comment]
Hi @techmagus,

We have fixed multisite issue. Please download code from git branch 1.0.7 as we have not update it on wordpress.org due to some more testing. there is still issue with cdn compatibility on multisite and we have raised a ticket (https://github.com/ahmedkaludi/pwa-for-wp/issues/71) so please disable that option and than it will work for you.

if you want to see what changes we made to work on multisite without cdn compatiblity you can track here https://github.com/ahmedkaludi/pwa-for-wp/issues/72

Hope this helps you

Thanks

**Comment by Sanjeevsetu** [comment]
Hi @techmagus,

We are happy that now pwa is working for you. The file name was being changed while appending to link href, this was because of CDN compatibility issue and we will fix it soon as we have already raised a ticket. 

Sure, We always welcome users input, We will sure let you know if we need anything from your side. At the same time if you have any issue, please let us know. 

Regards
Sanjeev
