### ISSUE TITLE
Need to fix Cache for Webpages on the Service Worker 

### ISSUE THREAD

**Issue by saurabhpandey542000** [ahmedkaludi/pwa-for-wp#692]
Here , the issue is when ever the person can logged in his website then he can said to be a login user
but whenever he switch into different pages  of this website then the UI shows that the user is  logged out
but when user refresh the page then it shows as  login user again
but can't shows it when ever the page is loading in the first time  
But he still logged in..

ticket ref ="https://secure.helpscout.net/conversation/1798490674/228328?folderId=6366263"

Short video of issue ---"https://drive.google.com/file/d/1bSk1cvW3lk2yNmKSYss7W7T5JH7m9g0L/view"

**Comment by ajeetku** [comment]
In service worker did changes for Network first, pushed in version 1.7.44
