### ISSUE TITLE
PWA to ios as a service

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/pwa-for-wp#693]
PWA to ios as a service

**Comment by kumawatvikas** [comment]
Ref : https://github.com/ahmedkaludi/pwa-to-ios-plugin/commit/816fcc1ed6c7acb00505f659c78345c0fac11a82

**Comment by akshaywali** [comment]
released in PWA for WP 1.7.76 / PWA PRO Extension 1.9.5
