### ISSUE TITLE
Option to add screenshots to the manifest

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/pwa-for-wp#694]
Related URL: https://www.stefanjudis.com/notes/how-to-define-progressive-web-app-pwa-screenshots-and-shortcuts/
Reference ticket: https://wordpress.org/support/topic/when-will-we-finally-get-native-screenshots/

**Comment by pradipshende** [comment]
In service worker added screenshots functionality for users, pushed in PWA for WP version 1.7.46
