### ISSUE TITLE
Getting Index DB init function undefined error in service worker file

### ISSUE THREAD

**Issue by DeheemB** [ahmedkaludi/pwa-for-wp#695]
pwa-sw.js:288 Uncaught ReferenceError: init is not defined

Reference  
https://secure.helpscout.net/conversation/1814983518/230854?folderId=6406114

Error Screenshot
https://prnt.sc/7PJQxhCtuDdE

**Comment by MohammedAkramU7** [comment]
Another user-facing same issue

Helpscout:-
https://secure.helpscout.net/conversation/1825393371/232802?folderId=5893563

**Comment by ajeetku** [comment]
Resolved in updated 1.7.44
