### ISSUE TITLE
Improvement when license is expired.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/pwa-for-wp#696]
1. Show an exclamation here when the license is expired https://prnt.sc/YSTN386gz8Tq
2. Checkout the scenario in the video https://monosnap.com/direct/DwCebUU4xB2VsLdkOnlT3bdN3MKVBf

**Comment by pradipshende** [comment]
In service worker added license expired icon, pushed in PWA for WP version 1.7.46
