### ISSUE TITLE
Need to add a functionality where user can hide or remove ''Add to home screeen'' banner from a particluar page.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/pwa-for-wp#699]
Need to add a functionality where the users can change its add to home screen from the home page to any other page.

Ref:https://secure.helpscout.net/conversation/1827892105/233507?folderId=6370795

**Comment by pradipshende** [comment]
In service worker added visibility functionality for users can hide or remove the "Add to home screen" banner from particular pages, pushed in PWA for WP version 1.7.45
