### ISSUE TITLE
While using BuddyBoss user cannot go back on the website after downloading the image.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/pwa-for-wp#702]
Ref Ticket: https://secure.helpscout.net/conversation/1853107674/238308?folderId=6406109

When the user tries to download the image through the PWA app which is generated by BuddyBoss then the image is downloaded but the page got blank and the user is unable to go back.

**Comment by ahmedkaludi** [comment]
Issue at debugging stage.
