### ISSUE TITLE
Latest update brought a jQuery, error which basically took down my website

### ISSUE THREAD

**Issue by krisbarton** [ahmedkaludi/pwa-for-wp#706]
Yesterday morning, I updated to Version: 1.7.46 and quickly found my website was borked. Just a blank white screen.

Knew it had to be the plugin update so when I checked the dev tools error logs it seemed to be caused by a logic check with jQuery.

I have no idea why that would be causing the issue now, as I deleted jQuery a long time ago and have never had it running with this.

I mean, in this day an age why even use jQuery? (but that's another argument).

This version obviously wasn't tested for those without jQuery installed.

I would've added a picture to demonstrate the issue, but obviously, I quickly deactivated the plugin and got my site back up working as a priority.

**Comment by ahmedkaludi** [comment]
@krisbarton 

That's strange, We haven't made changes any changes related to jQuery. 

Can you please help me re-create the issue once so that I can solve this?

We haven't faced this with other users.

**Comment by akshaywali** [comment]
This is issue is unable to recreate and as of version 1.7.50+ we are not using any jQuery for frontend.
