### ISSUE TITLE
Data Analytics is not working properly.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/pwa-for-wp#708]
Data Analytics is not working properly as it is not showing the number of PWA downloads.

Reference ticket: https://secure.helpscout.net/conversation/1869390569/240600?folderId=6406109

New Scenario after debugging: Data analytics is only showing the downloads which have been done from the PC and not from the smartphones

Conclusion: Need to debug properly.

**Comment by pradipshende** [comment]
Pushed in Data Analytics for PWA plugin version 1.5
