### ISSUE TITLE
In offline from Index DB is saving the data but not showing .

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/pwa-for-wp#709]
While using offline from Index DB is saving the data but not showing the data when we are online.
Ref:https://secure.helpscout.net/conversation/1860248201/239274?folderId=6370795

**Comment by sajandara** [comment]
After submitting the form in offline mode there will be an error saying "site can't be reached"

Ref Ticket: https://secure.helpscout.net/conversation/1885458014/242782/

Ref Screenshot: https://prnt.sc/jw9oJLhiDmkA
