### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading ‘length’)

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/pwa-for-wp#711]
Reference ticket: https://wordpress.org/support/topic/uncaught-typeerror-cannot-read-properties-of-undefined-reading-length/

**Comment by Sanjeevsetu** [comment]
This issue has been fixed in ticket https://github.com/ahmedkaludi/pwa-for-wp/issues/741
