### ISSUE TITLE
Call to Action pop up is not showing in Ipad  ( Safari browser ) except (Ipad mini)  ( User-specific issue)

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/pwa-for-wp#715]
The call to Action pop up is not showing on the Ipad  ( Safari browser ) except (iPad mini)
https://prnt.sc/Wh3NDlFuorKd

2) In IOS chrome when we try to click on Add to home screen banner then no steps are showing How to install CTA.

3) In Mac Safari CTA is showing which should not show.
https://prnt.sc/yrO0eHrchdw3

ref:(https://secure.helpscout.net/conversation/1840159007/235952?folderId=6370795))

**Comment by pradipshende** [comment]
This issue occurs only on an old version of the iPad, please update the iPad with the latest version
