### ISSUE TITLE
"Ultimate member" real-time notifications are not working in the PWA app

### ISSUE THREAD

**Issue by kupveja** [ahmedkaludi/pwa-for-wp#716]
User has enabled our " push notifications " extension. "Ultimate member" real-time notifications are not working in the PWA app.

Reference - https://secure.helpscout.net/conversation/1885641839/242824?folderId=4459751

**Comment by michael-newman** [comment]
"Ultimate Member" real-time notifications should also show as a number within the "red circle" app badge of the PWA app!
