### ISSUE TITLE
IOS Splash Screen Method is not working.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/pwa-for-wp#717]
The Ios Splash screen Method is not working when uploading the Image on the IOS Splash screen icon for Version 1.7.46

Ref video:https://www.awesomescreenshot.com/video/9059268?key=73ef2a941e677cb7ffddd73e4a184cb1

Ref;https://secure.helpscout.net/conversation/1893936642/243990?folderId=6370795

**Comment by sajandara** [comment]
Another user is facing a similar issue.

Ref ticket: https://secure.helpscout.net/conversation/1897335901/244449?folderId=6406109
