### ISSUE TITLE
Need to add  a option for the proper uninstallation of the plugin. 

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/pwa-for-wp#723]
Need to create an option from which we can remove the old setting and all data of the plugin after reinstalling the PWA plugin because if we delete the plugin and reinstall it then the old setting remains the same.

REF:https://magazine3.in/conversation/4980?folder_id=29

**Comment by pradipshende** [comment]
Pushed in PWA for WP & AMP plugin version 1.7.48
