### ISSUE TITLE
Splash screen icon is not working on IOS

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/pwa-for-wp#724]
The splash screen icon is not working on IOS.

Ref:https://magazine3.in/conversation/6140?folder_id=29

https://github.com/ahmedkaludi/pwa-for-wp/issues/717
After fixing the above issue, **The splash screen icon is not working on the IOS** this issue is generated.

**Comment by pradipshende** [comment]
We try but not find solution

**Comment by akshaywali** [comment]
update pushed in 1.7.53
