### ISSUE TITLE
Push notification enhanced notification

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/pwa-for-wp#728]
https://drive.google.com/file/d/1j7-c9XODRrucpz_zDKRpzZXQ99hs_p4Z/view?usp=sharing

**Comment by ahmedkaludi** [comment]
![image](https://github.com/ahmedkaludi/pwa-for-wp/assets/16532359/b3635c5d-a267-4e3b-a2a6-68d0ccee50f9)

**Comment by ahmedkaludi** [comment]
![image](https://github.com/ahmedkaludi/pwa-for-wp/assets/16532359/1c69c221-a724-4acc-b0c8-b40b655e97ad)

https://knowledgebase.webengage.com/docs/key-value-pairs-dynamic-app-experiences

**Comment by ahmedkaludi** [comment]
![E04A999F-5827-4483-B45D-E62F8822A94C](https://github.com/ahmedkaludi/pwa-for-wp/assets/16532359/11e82df5-eb8e-4191-a306-d127c25858c1)
![8ACB4298-820B-47F8-AF26-765BED9A648E](https://github.com/ahmedkaludi/pwa-for-wp/assets/16532359/f55f530d-498b-446d-b71f-6d287e82d7d1)

**Comment by Sanjeevsetu** [comment]
Related https://github.com/ahmedkaludi/push-notification/issues/86.
