### ISSUE TITLE
Need to add upload image option in offline forms for PWA.

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/pwa-for-wp#734]
The user wants to upload images (10-20 ) in offline form.

Requirement -: ( The form has 10 fields of images required and 2 other fields of images
and 4 fields text required and  19 other fields (text and radio button) that are not required )

Reference Ticket -: https://magazine3.in/conversation/15740?folder_id=23

**Comment by pradipshende** [comment]
push changes in Offline Forms for PWA for WP 1.6 version
