### ISSUE TITLE
Select Icon is not working in navigation menu

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/pwa-for-wp#736]
In posts, the select Icon button is not working while for pages, when selecting any Icon it is not uploading.

Reference ticket -: https://magazine3.in/conversation/20570?folder_id=23

Reference screenshot-: https://monosnap.com/direct/EXKcSnRIb0U6ziNzw5ltcpl9NyDnfL

**Comment by Sdaud1950** [comment]
This user also has the same issue.
Reference ticket: https://magazine3.in/conversation/26006?folder_id=29

**Comment by pradipshende** [comment]
Pushed in Navigation Bar for PWA plugin version 1.5
