### ISSUE TITLE
Errors appears when generating the APK 

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/pwa-for-wp#738]
Freescout:- 
https://magazine3.in/conversation/22442?folder_id=21

Description:-
While generating the APK it's loading and shows errors 500 and fatal errors in the previous tab.

Issue screenshot:-
https://prnt.sc/96nLi8uhMEVp
https://prnt.sc/iOQ-iJaQZuyK

**Comment by pradipshende** [comment]
Issue fixed in Node (Server) site

**Comment by MohammedAkramU7** [comment]
User facing same issue with latest version 1.7.49
