### ISSUE TITLE
Push notification is not working

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/pwa-for-wp#740]
Push notification is not sending subscribe popup. it is showing the error "Cannot instantiate firebase-messaging.js - be sure to load firebase-app.js first." in response.

Reference ticket -: https://magazine3.in/conversation/22727?folder_id=23

Reference screenshot -: 
![pushnotification](https://user-images.githubusercontent.com/78167698/181229496-c4b1b08d-876a-4111-9773-d801f2c90f0f.png)

**Comment by ahmedkaludi** [comment]
possibly similar #711

**Comment by Sanjeevsetu** [comment]
this issue has been fixed in ticket https://github.com/ahmedkaludi/pwa-for-wp/issues/741
