### ISSUE TITLE
While using push notification (FCM push notification), there is an error in the console.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/pwa-for-wp#741]
While using the push notification (FCM), there is an error in the Chrome Console. So it could not generate the service workers of the PWA.

Ref help scout.. https://magazine3.in/conversation/22720?folder_id=29 
Ref screenshot. https://prnt.sc/z_95n2OG54_G

Recreate steps.
1)PWA install
2)Push notification as FCM
3) Enter FCM Server API Key 
4) Enter the Config code.

**Comment by Sanjeevsetu** [comment]
Imran is still working on it. We are moving to next milestone

**Comment by akshaywali** [comment]
update pushed in 1.7.52
