### ISSUE TITLE
Data Analytics does not count the PWAs downloaded from the AMP version.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/pwa-for-wp#744]
PWA downloaded from the AMP version of the website is not recognized by Data Analytics.

Reference ticket: https://magazine3.in/conversation/27241?folder_id=27

**Comment by syedimran22** [comment]
Commit link : https://github.com/ahmedkaludi/data-analytics-for-pwa/commit/afa820085df85c2c563e46f98f37ad63b43c35a5
