### ISSUE TITLE
Improvement In pushnotification

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/pwa-for-wp#745]
- [ ] Need an option where subscribers can subscribe only for particular category updates or for all category updates.
Add categories and „all categories“ to the Popup (for subscription). The user can choose the categories, he wants to be messaged. Or he can choose „all categories"

- [ ] When I publish a new post in one category (or in many categories), it should send the post to all receipians, that checked the box at this categories in the popup before.

- [ ] need a checkbox on the post view in the backend, „send web push“ - so I can decide if I push the new post as a message, or not.

Reference Ticket URL: https://magazine3.in/conversation/22720?folder_id=4
Trello Ticket URL:  https://trello.com/c/YmnkjFwC/160-68-marcus-prem-pradip

**Comment by pradipshende** [comment]
Updated in Push Notification 1.24 version
