### ISSUE TITLE
Offline forms extension is not updating

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/pwa-for-wp#746]
There is an issue with Offline forms for PWAforWP, it is not updating. It asks for an update now and when we click on update now, it gets updated and after refreshing the page it goes back and asks for an update again.

There is a bug in code, where the stable version is 1.5 and so it is unable to get the 1.51.

Reference screenshots -: 
https://monosnap.com/file/JBWzhsjO2RWpHyfWaLs0YK5SZyDkMh
https://monosnap.com/file/16LSmNnWstFuWpKF5gNBI72ehYm613

Reference ticket -: https://magazine3.in/conversation/23992?folder_id=23

Reference screenshot -: 
![Uploading updatenow.png…]()

**Comment by pradipshende** [comment]
push changes in Offline Forms for PWA for WP 1.6 version
