### ISSUE TITLE
Data analytics not working (User Specific)

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/pwa-for-wp#750]
When we have activated Data Analytics for PWA and try to install any PWA, data analytics is not fetching data.

Reference ticket -:https://magazine3.in/conversation/29517?folder_id=23

**Comment by pradipshende** [comment]
We are waiting for client reply

**Comment by akshaywali** [comment]
Basically Data analytics is capturing install when user uses the installed app  for first time ,not just on install.

**Comment by akshaywali** [comment]
Update pushed Data Analytics for PWA 1.7
