### ISSUE TITLE
Subscribe to push notification appears again and again after subscribing it.(User Specific)

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/pwa-for-wp#751]
User using PWAforWP and our Pushnotification.io plugin.

- [x] The Push notification popup appears again and again after clicking it then again popup will appear if we click on another page or refresh the page.
Reference Video: https://monosnap.com/file/VwbuffmiiA0UPZO6FxeWd5n0N0jeQR

Trello Card: https://trello.com/c/LJ8dIog8/154-62-frank-mckenneypwa-and-pn
Freescout URL: https://magazine3.in/conversation/11624?folder_id=19

**Comment by pradipshende** [comment]
The issue occurred because of the BuddyPress extension plugin (extended profiles)

**Comment by Sanjeevsetu** [comment]
We are closing this ticket as this is not because of PWAforWP. If it comes due to PWAforWP we will reopen it

**Comment by akshaywali** [comment]
Update pushed at Push Notification 1.26 https://github.com/ahmedkaludi/push-notification/commit/caba1f3d41ff3344f47022efbb684de75d45325b
