### ISSUE TITLE
CTA banner is appearing on the desktop even if it is disabled. (Sticky bar)

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/pwa-for-wp#752]
CTA banner is appearing on the desktop even if the option is not enabled.

Ref ticket: https://prnt.sc/OSLbfjZul1gZ

Ref ticket: https://magazine3.in/conversation/45290?folder_id=27

**Comment by pradipshende** [comment]
Push changes in Call To Action For PWA 1.9.1 version
