### ISSUE TITLE
CTA banner is appearing in the PWA. (Sticky bar)

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/pwa-for-wp#754]
The Sticky bar is appearing in the PWA after installing it and it's a global issue.

Ref screenshot: https://prnt.sc/olfgoIzglVC7

Ref tickets: https://magazine3.in/conversation/45290?folder_id=27
https://magazine3.in/conversation/42953?folder_id=3

**Comment by pradipshende** [comment]
Push changes in Call To Action For PWA 1.9.1 version
