### ISSUE TITLE
Need to fix the pre launch issue on Google Play Console

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/pwa-for-wp#756]
When we publish the app, it throw an exception error. 

Reference ticket -: https://magazine3.in/conversation/48188?folder_id=23

![IMG_20220927_151500_540](https://user-images.githubusercontent.com/78167698/192493379-0ccc65b5-9907-4bc3-995c-27ff44c6fc61.jpg)
![IMG_20220927_151455_710](https://user-images.githubusercontent.com/78167698/192493392-73d31d6b-4dcf-4108-98f1-046c9d30b945.jpg)

**Comment by pradipshende** [comment]
We are waiting for client reply

**Comment by akshaywali** [comment]
This is issue is related to crashing of  APK  which is already fixed (APK generation library update) .
Also the user  has not responded and we are  unable to recreate the issue .So we will mark this ticket as completed.
