### ISSUE TITLE
Need to fix the pre launch error on Google play console

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/pwa-for-wp#757]
When we launch the app on Google Play Console, it throws an error exception error related to FLAG_IMMUTABLE.

Reference ticket -: https://magazine3.in/conversation/38539?folder_id=23

![Screenshot (757)](https://user-images.githubusercontent.com/78167698/192518328-543e8228-ef21-4fd8-a758-fc0864ff493f.png)

**Comment by akshaywali** [comment]
We have updated our APK generation library. So this is issue is already fixed as of NOV 7 2022 .

**Comment by akshaywali** [comment]
This is already fixed , if anybody faces this issue again please reopen this ticket or create a new ticket
