### ISSUE TITLE
When we add the video to our website when the PWA plugin is enabled, there is an error in the console.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/pwa-for-wp#760]
When we add the video to our website when the PWA plugin is enabled, there is an error in the console.

Error. Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Partial response (status code 206) is unsupported
    at pwa-sw.js:394:71 

Ref freescout ticket. https://magazine3.in/conversation/52961?folder_id=29

1. Ref screenshot https://prnt.sc/CtpUDwOwrfww
2. Ref screenshot  https://prnt.sc/LMksTpw_6ue4

Recreating Steps.
1. Install PWA
2. Create a Post
3. Add a video on the Post 
4. Check in the console.

**Comment by pradipshende** [comment]
Push changes in PWA for WP & AMP 1.7.51 version
