### ISSUE TITLE
Service worker syntax error(User Specific issue)

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/pwa-for-wp#762]
Ref ticket:- https://magazine3.in/conversation/52535?folder_id=21

Issue description:-
Server is not register and error show in application section "syntax line: 1, column: 1, syntax error" 

Issue screenshot:-
https://monosnap.com/direct/E0E2G8u4L39fgFz6dbeWvH7sAU4fXf

**Comment by pradipshende** [comment]
issue present in the client server
