### ISSUE TITLE
Formidable Forms offline submission not working.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/pwa-for-wp#764]
When we go through the offline form and submit the response after going offline, the page shows an error.

Ref screenshot.https://prnt.sc/kjxiO7O7qVLX 

Ref ticket. https://magazine3.in/conversation/56700?folder_id=29

**Comment by pradipshende** [comment]
Push changes in Offline Forms for PWA for WP 1.7 version
