### ISSUE TITLE
Rewrite rules are being flush on every page load

### ISSUE THREAD

**Issue by ebuzzz** [ahmedkaludi/pwa-for-wp#765]
The script `service-work/class-service-worker.php` has a method `pwaforwp_onesignal_rewrite` which is called every time a page is loaded when logged in as an admin. This results in rewriting the `.htaccess` file contents to disk. This is bad behavior and also results in errors when used in combination with WPML. For some reason, WPML adds the language to the RewriteBase, resulting in a duplicate Rewrite block. This is a known bug when plugins update the .htaccess file too often.

Also, the code for the method seems wrong:

```php
function pwaforwp_onesignal_rewrite(){
    flush_rewrite_rules();
    // Flushing rewrite urls ONLY on activation
    global $wp_rewrite;
    $wp_rewrite->flush_rules();
    add_rewrite_rule("onesignal_js/([0-9]{1,})?$", 'index.php?'.pwaforwp_query_var('sw_query_var').'=1&'.pwaforwp_query_var('sw_file_var').'='.'dynamic_onesignal'."&".pwaforwp_query_var('site_id_var').'=$matches[1]',>
    add_rewrite_rule("onesignal_js/?$", 'index.php?'.pwaforwp_query_var('sw_query_var').'=1&'.pwaforwp_query_var('sw_file_var').'='.'dynamic_onesignal'."&".pwaforwp_query_var('site_id_var').'=normal', 'top');
}
```

The comment _Flushing rewrite urls ONLY on activation_ seems to be a TODO in this case?

Calling the method `flush_rewrite_rules` internally calls `$wp_rewrite->flush_rules()`, so this code seems to do it twice!

The `pwaforwp_pushnami_rewrite` method has the same behavior, but adding this method to the init hook is disabled by an option, so it’s not triggered by default.

**Comment by ebuzzz** [comment]
For users not using ONesignal, it would fix it by adding the same check as for pushnami:

```php
                if(isset($settings['one_signal_support_setting']) && $settings['one_signal_support_setting']==1){
                    add_action( 'init',  array($this,'pwaforwp_onesignal_rewrite' ));
                }
```

**Comment by akshaywali** [comment]
pushed in update 1.7.57
