### ISSUE TITLE
The Option "Follow Device Orientation" is not working.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/pwa-for-wp#766]
The Option "Follow Device Orientation" is not working.

Ref ticket: https://magazine3.in/conversation/59474?folder_id=4

**Comment by icegrim** [comment]
Is there any solution to this situation? I'm having the same problem on my site: https://hipertales.ml/

**Comment by Sdaud1950** [comment]
Same issue with this user. https://magazine3.in/conversation/67026?folder_id=29

**Comment by akshaywali** [comment]
update pushed in 1.7.53
