### ISSUE TITLE
Escaping is missing in some place

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/pwa-for-wp#769]
D:\XAMPP\htdocs\magazine3\wp-content\plugins\pwa-for-wp\admin\common-function.php. Line ( 16, 17 )
D:\XAMPP\htdocs\magazine3\wp-content\plugins\pwa-for-wp\admin\settings.php. Line ( 196, 207, 226, 227, 357, 840, 849, 850, 881, 893, 917, 929, 941, 953, 965,  1565, 1702, 1991, 1992, 1993, 2282, 2865, 3238, 3245, 3252, 3259, 3266, 3273, 3280, 3292, 3316, 3328, 3340, 3352, 3364, 3376, 3388, 3434, 3439, 3545, 3549, 3553, 3988  )

**Comment by akshaywali** [comment]
update pushed in 1.7.52
