### ISSUE TITLE
Block theme 404

### ISSUE THREAD

**Issue by vontainment** [ahmedkaludi/pwa-for-wp#773]
In the PWA file with the setting for 404 page set to default it is set as the homepage. This causes a block theme with a 404 template to show the homepage instead. I think the default setting for the 404 page should be set to nothing so the 404 template will work.

**Comment by vontainment** [comment]
After further testing i found that if both the following are set as show blank not your domain name as it is currently block template 404 works. Either default 404 page in settings should blank the results or a block template options should be added. 
This should be a priority as it is a huge issue for SEO

const NOT_FOUND_CACHE_FILES = ['',];
and
const NOT_FOUND_PAGE = '';

**Comment by radiogyan** [comment]
Any update on this? I am still facing this issue. Thanks.

**Comment by vontainment** [comment]
once a 404 page is reached the rest are forwarded to home page and so are 410 so this plugin destroys SEO. even if set to netwrok only it still caches / as the 404 page and treats 410 as 404

**Comment by vontainment** [comment]
is there a way we can turn off the 404 caching adding something to function.php?
