### ISSUE TITLE
The shortcode for "Add to Home Screen" is not working for Android or desktop while using the push notification, and there are also errors in the console.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/pwa-for-wp#776]
1.The shortcode is added to install PWA while using the push notification, but the Add to Home Screen Banner option does not appear on Android and desktops.
Ref video.https://monosnap.com/direct/cQDGAClE1pTK3CqY2iCbPHNMIg3Jnw 

2. Also There is an error in the console while using the push notification.
Ref screenshot .https://prnt.sc/j2EXhqxgmeHl 

Ref ticket. https://magazine3.in/conversation/22720?folder_id=29

**Comment by He3556** [comment]
Hello i have this problem since last week. But the error was already mentioned 3 weeks ago. 
https://wordpress.org/support/topic/identifier-messaging-has-already-been-declared/    
I hope you will find a fix soon

**Comment by akshaywali** [comment]
Please update [Push Notifications](https://wordpress.org/plugins/push-notification/) plugin to 1.25.1 to fix the issue

**Comment by akshaywali** [comment]
This is issue fixed by updating to latest version of push notification plugin(1.25.1)  and PWA for WP(1.7.52+).
Make sure you clear the cache and then check . if any still find this issue you can create a new ticket or reopen this ticket
