### ISSUE TITLE
Offline forms throwing  error

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/pwa-for-wp#779]
The offline form is not functioning properly, and there are issues with submitting the form. 

Ref screenshot: https://prnt.sc/aeVzIDIdqrz5

Ref ticket: https://magazine3.in/conversation/77594?folder_id=29

**Comment by sajandara** [comment]
The user is facing the same issue.
https://magazine3.in/conversation/77307?folder_id=27

**Comment by akshaywali** [comment]
Update pushed on  https://github.com/ahmedkaludi/offline-forms-for-pwa-for-wp/commit/83c1cb9ebfaccc1226635276a3c70aa6bdd1b6ae

**Comment by akshaywali** [comment]
update pushed in Offline Forms for PWA for WP 1.8
