### ISSUE TITLE
When we add the shortcode to display "add to home button," it shows only on iOS, not on desktop. (" Priority issue")

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/pwa-for-wp#780]
When we add the shortcode to display the "add to home button" on the pages, the button is shown on IOS and Android devices but does not show on the desktop.

Ref screenshot of IOS where it shows. https://prnt.sc/yjVvYFgMmnka

Ref screenshot of the Desktop where it does not show. https://prnt.sc/-XO9-H1FmETr

Ref ticket. https://magazine3.in/conversation/22720?folder_id=29

**Comment by akshaywali** [comment]
Update pushed on https://github.com/ahmedkaludi/call-to-action-for-pwa/commit/0d8f6338af5bba40897d7884ce40491795629f23

**Comment by akshaywali** [comment]
update pushed in 1.7.54
