### ISSUE TITLE
 Loader not working properly with 1.7.53 version

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/pwa-for-wp#781]
Ref ticket:-
https://magazine3.in/conversation/73845?folder_id=21

Description:-
Loader icon color and background color doesn't change according to my set color, it shows the default color.

Issue screenshot:-
https://prnt.sc/lg8-YQEb7n1R

**Comment by akshaywali** [comment]
update pushed in 1.7.54
