### ISSUE TITLE
[iOS] Apple Finally Supports Push Notifications On Safari - Feature Request

### ISSUE THREAD

**Issue by renegademarketer** [ahmedkaludi/pwa-for-wp#782]
Per the article from Apple below, Safari 16.1 now supports web push. It seems to require special implementation but I'm hoping you can quickly add this to your plugin since this must be one of the most requested features of all PWAs. 

https://developer.apple.com/documentation/usernotifications/sending_web_push_notifications_in_safari_and_other_browsers

**Comment by kumawatvikas** [comment]
Its fixed in : https://github.com/ahmedkaludi/push-notification/issues/66

**Comment by Sanjeevsetu** [comment]
Hi @renegademarketer 

We have added support for IOS push notification. Please try our latest version and let us know?
