### ISSUE TITLE
Code Improvement as per WP guidlines

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/pwa-for-wp#787]
- [x] D:\XAMPP\htdocs\magazine3\wp-content\plugins\pwa-for-wp\admin\settings.php. Line: 223 to 230,  Need improvement
- [x] Before every foreach loop we must check variable is empty or not and it is array or object. To avoid possible warnings. check entire plugin eg D:\XAMPP\htdocs\magazine3\wp-content\plugins\pwa-for-wp\admin\settings.php. Line: 89
- [x] D:\XAMPP\htdocs\magazine3\wp-content\plugins\pwa-for-wp\admin\settings.php. Line: 154, 155, 184, 187, 191, 268, 3702, 3705, escaping is missing
- [x] D:\XAMPP\htdocs\magazine3\wp-content\plugins\pwa-for-wp\admin\settings.php. Line: 771, 794, 803, 811, 821, 831 have escaped a space which should not be there. eg esc_html__(' ','pwa-for-wp')
- [x] D:\XAMPP\htdocs\magazine3\wp-content\plugins\pwa-for-wp\admin\settings.php. Line: 3929 and 3281 sanitization is missing. before every update_option we must sanitize a variable values. if it is array sanitize their respective values.
- [x] Inside Function pwaforwp_include_visibility_setting_callback, escaping is missing for most of options.
- [x] After every new WP_Query($args) we must restore original Post Data. Check ref for help ( https://developer.wordpress.org/reference/classes/wp_query/ ). issue eg. D:\XAMPP\htdocs\magazine3\wp-content\plugins\pwa-for-wp\admin\settings.php. Line 3738. Plz check entire plugin
- [x] Every class must have a proper prefix. check these classes. eg. 
        visibility-loader-box
        visibility-loader
        visibility-target-item
        visibility_options_select
        include-btn-box
        include_type_error
        include-btn
        exclude-btn
        pro_alert
        user_refresh_single_addon
        lifetime_

        for more plz check entire main-css.min.css.

- [x] - [ ] Check entire plugin and remove any unused code and commented code. eg D:\XAMPP\htdocs\magazine3\wp-content\plugins\pwa-for-wp\admin\settings.php. Line: 3166 to 3168 
- [x] We should use wordpress default HTTP API ( https://developer.wordpress.org/plugins/http-api/ ). check this function 'pwaforwp_send_push_notification'

**Comment by akshaywali** [comment]
pushed in update 1.7.56
