### ISSUE TITLE
The offline form is not working and shows an error after submitting.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/pwa-for-wp#789]
The offline form is not working and shows an error after submitting.

Ref screenshot: https://prnt.sc/aeVzIDIdqrz5

Ref ticket: https://magazine3.in/conversation/77307?folder_id=27

**Comment by Sdaud1950** [comment]
same issue with this user.
https://magazine3.in/conversation/77594?folder_id=29

**Comment by sajandara** [comment]
Another user is facing the same issue:
https://magazine3.in/conversation/99513?folder_id=27

**Comment by akshaywali** [comment]
Update pushed to Offline Forms for PWA for WP  version 2.2
