### ISSUE TITLE
The cache is not being stored for more than 1 day

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/pwa-for-wp#792]
The cache is not being stored for more than 1 day.

Ref ticket: https://magazine3.in/conversation/102395?folder_id=27

**Comment by sajandara** [comment]
Add a new functionality "PWA should be cached immediately after the user has downloaded it"

**Comment by akshaywali** [comment]
While testing cache was still available for 3 continuous days and still counting.
But if you use any booster apps then they can also clear cache  , also if your storage is low your OS can clear cache to freeup memory

**Comment by akshaywali** [comment]
Closing the ticket , Since  cache is working as expected
