### ISSUE TITLE
app version

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/pwa-for-wp#8]
REF: https://wordpress.org/support/topic/app-stores/

**Comment by Josimarcsilva** [comment]
I was able to take my Web App to the Play Store using TWA

https://developers.google.com/web/updates/2019/02/using-twa

**Comment by TMsravan** [comment]
https://developers.google.com/web/updates/2019/02/using-twa

**Comment by keshavsharma333** [comment]
One more user is asking for this feature.

https://secure.helpscout.net/conversation/885567962/71450?folderId=3044500

**Comment by SayyadF** [comment]
One more user asking for this feature.

REF:https://secure.helpscout.net/conversation/987058024/93603?folderId=3008055

**Comment by TMsravan** [comment]
Another user is also asking for this feature: https://secure.helpscout.net/conversation/995403444/96051/

**Comment by tripledm** [comment]
One more user asking for the feature

**Comment by wankhedekomal** [comment]
Another user is also asking for this feature: https://secure.helpscout.net/conversation/1044234258/104404?folderId=3257665

**Comment by niteshmanav** [comment]
It's been more than 1 year 6 months since it was promised to be added in the development. 

Now that TWA has come ( https://developers.google.com/web/updates/2019/02/using-twa ) , it shouldn't take much time. Can I get any update on this please?

**Comment by ahmedkaludi** [comment]
This feature is now available at https://pwa-for-wp.com/extensions/pwa-to-apk-plugin/
