### ISSUE TITLE
Need to add compatibility with Polylang

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/pwa-for-wp#817]
There is need to add feature support with Polylang.

**Comment by kumawatvikas** [comment]
Added in multilingual-compatibility-for-pwa :- https://github.com/ahmedkaludi/multilingual-compatibility-for-pwa/commit/b01c7841d2bd70c196216d29b7631da4a2956560

**Comment by Sanjeevsetu** [comment]
Added in Multilingual Compatibility for PWA https://pwa-for-wp.com/extensions/multilingual-compatibility-for-pwa/
