### ISSUE TITLE
Navigation Bar is not visible in Samsung devices.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/pwa-for-wp#836]
Ref ticket:-https://magazine3.in/conversation/160474?folder_id=21

Description:-
User create a APK but the navigation feature is not visible on Samsung devices.

Issue screenshot:-
https://prnt.sc/FLFHl4Py0qB7

**Comment by Sanjeevsetu** [comment]
This has been solved in pro ext navigation-bar-for-pwa v1.7
