### ISSUE TITLE
Splash Screen Background Color, App Name, and App Icon Not Functioning Properly on Android 12 and Above

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/pwa-for-wp#837]
user reported that the Splash screen background color, app name, and app icon not functioning correctly as per the plugin setup. Works fine up to Android 11. Requesting testing on physical Android 12+ devices.

Here is the reference ticket: https://wordpress.org/support/topic/splash-screen-not-working-on-android-12/
same user with same issue: https://wordpress.org/support/topic/appname-is-not-visible-in-splash-screen/

**Comment by Sanjeevsetu** [comment]
This ticket was reported on github as well from that users who reported on forum. Here is the link https://github.com/ahmedkaludi/pwa-for-wp/issues/834. So I am closing it as it became duplicate.
