### ISSUE TITLE
Offlineforms are not working with Contact Form7

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/pwa-for-wp#844]
The loader is loading continuously after submitting the form.

Ref ticket: https://magazine3.in/conversation/190641?folder_id=27

**Comment by Sanjeevsetu** [comment]
Ref: https://github.com/ahmedkaludi/offline-forms-for-pwa-for-wp/commit/5d5c87f3c3162b778b1c440bf935e5504da3c306
