### ISSUE TITLE
Need to make compatibility with TranslatePress in the multilingual-compatibility-for-PWA extension.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/pwa-for-wp#849]
Need to make compatibility with TranslatePress in the multilingual-compatibility-for-PWA extension.

Ref ticket: https://magazine3.in/conversation/205528?folder_id=29

**Comment by Sanjeevsetu** [comment]
We already have this feature. Just need to update our docs. https://pwa-for-wp.com/extensions/multilingual-compatibility-for-pwa/
