### ISSUE TITLE
Please give an option for translate in add to home screen

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#85]
We will create an option to translate Add to Home Screen
Reference Link: https://secure.helpscout.net/conversation/801530863/59547?folderId=1060556

**Comment by Rkroy** [comment]
Another user: https://secure.helpscout.net/conversation/814537548/61708?folderId=1680016

**Comment by ajeetku** [comment]
For update Text of banner, already have option Subsection "Custom Add To Homescreen Customization" in Design Tab.

**Comment by ajeetku** [comment]
Pushed in Version 1.5
