### ISSUE TITLE
Conflict issue with the plugin Category Icon

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/pwa-for-wp#851]
Add compatibility with the plugin Category Icon.

Bug: After enabling the plugin, PWAforWP's Navigation Bar icons are getting enlarged

Ref screenshot: https://monosnap.com/direct/C70sR987a653A8JYqHoPZkhUL3cHDu

Ref ticket: https://magazine3.in/conversation/208219?folder_id=27

**Comment by kumawatvikas** [comment]
Refrence : -https://github.com/ahmedkaludi/navigation-bar-for-pwa/commit/883065a268a52cbde71c1db18f9e21432c9015f0
