### ISSUE TITLE
The Navigation Bar appears broken on the Homepage due to the theme Wisteria

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/pwa-for-wp#857]
The Navigation Bar appears broken on the Homepage due to the theme Wisteria

Ref ticket: https://magazine3.in/conversation/219095?folder_id=27

**Comment by kumawatvikas** [comment]
This issue fixed in navigation bar : https://github.com/ahmedkaludi/navigation-bar-for-pwa/commit/a7cfc5557b94b93d97c991ddf6bb778315bfcc9d
