### ISSUE TITLE
offline form feature is not working with formidable forms.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/pwa-for-wp#862]
Ref ticket:- https://magazine3.in/conversation/162767?folder_id=21

Description:-
When the user submits the offline form with dual entries, they appear in the backend. 

Issue screenshot:-
https://prnt.sc/SGAqiEe8FDIv

**Comment by akshaywali** [comment]
https://github.com/ahmedkaludi/offline-forms-for-pwa-for-wp/commit/bbfab59accae1c74188846b04a39623d00bd1afd

**Comment by akshaywali** [comment]
https://github.com/ahmedkaludi/offline-forms-for-pwa-for-wp/commit/bc7eb6afb1396819b7a05ff5cabbdc2bd57a6477
