### ISSUE TITLE
Warning with the PWA PRO version.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/pwa-for-wp#865]
Ref ticket:- https://magazine3.in/conversation/237961?folder_id=21

Warnings:-

Deprecated: Creation of dynamic property CTAFP_Data_EDD_SL_Plugin_Updater::$beta is deprecated in /home2/jattprod/public_html/ckmedianetwork/wp-content/plugins/call-to-action-for-pwa/updater/EDD_SL_Plugin_Updater.php on line 42

Deprecated: Creation of dynamic property PTRFP_Data_EDD_SL_Plugin_Updater::$beta is deprecated in /home2/jattprod/public_html/ckmedianetwork/wp-content/plugins/pull-to-refresh-for-pwa/updater/EDD_SL_Plugin_Updater.php on line 42

Deprecated: Creation of dynamic property PTAFP_Data_EDD_SL_Plugin_Updater::$beta is deprecated in /home2/jattprod/public_html/ckmedianetwork/wp-content/plugins/pwa-to-apk-plugin/updater/EDD_SL_Plugin_Updater.php on line 42

Deprecated: Creation of dynamic property SPBFP_Data_EDD_SL_Plugin_Updater::$beta is deprecated in /home2/jattprod/public_html/ckmedianetwork/wp-content/plugins/scroll-progress-bar-for-pwa/updater/EDD_SL_Plugin_Updater.php on line 42

and fix translation issue.

**Comment by Sanjeevsetu** [comment]
Ref https://github.com/ahmedkaludi/pwa-pro-extension-manager/commit/7cb532f6aeb489d715ea0b07dc99120ee4262cf6

**Comment by Sanjeevsetu** [comment]
this has been fixed for all our pro extensions
