### ISSUE TITLE
PWA PopUp for a Specific Page/post option.

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/pwa-for-wp#867]
User reach out for this request that needs an option for PWA pop for specific pages/posts.

Reference ticket: https://wordpress.org/support/topic/pwa-pop-up-showing-on-a-different-page/

**Comment by Sanjeevsetu** [comment]
We already have this feature. here is the docs. https://pwa-for-wp.com/docs/article/setting-up-visibility-in-pwa/
