### ISSUE TITLE
Need to add a new feature so that users can be able to upload their own images to use as an icon in the Navigation Bar

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/pwa-for-wp#869]
Need to add a new feature so that users can be able to upload their own images to use as an icon in the Navigation Bar

Ref ticket: https://magazine3.in/conversation/243868?folder_id=27

**Comment by kumawatvikas** [comment]
Ref :- https://github.com/ahmedkaludi/navigation-bar-for-pwa/commit/d430ea6ad923e4cd26e21b78fd3b09b7683f1337
