### ISSUE TITLE
Issue with the Push Notification in PWA for WP plugin

### ISSUE THREAD

**Issue by ms-hasan** [ahmedkaludi/pwa-for-wp#87]
1. Push Notification is not showing.
Ref: https://secure.helpscout.net/conversation/806415430/60425?folderId=2614130

**Comment by TMsravan** [comment]
https://secure.helpscout.net/conversation/809625354/60919/

This is also related to the same issue, facing console errors. Please look into it.

**Comment by ajeetku** [comment]
FCM working properly

**Comment by ajeetku** [comment]
Not recreated the issue

**Comment by ajeetku** [comment]
Closing this ticket, we checked our side FCM push notification working.
