### ISSUE TITLE
Need to show dynamic Custom post type as Start_page of PWA and with data on CPT

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/pwa-for-wp#873]
The  user has the Custom post type, and that custom post type has a contact form on it. So the requirement of the user is that the CTA should appear on the only on CPT which the form is added, and then once we install the PWA for the CPT that has the form, the Start_page of the PWA should be the CPT form with data.

Ref Ticket : https://magazine3.in/conversation/252071?folder_id=29

**Comment by Imageburst** [comment]
You mean to say CPT not CTP right?

**Comment by Imageburst** [comment]
Hi, for some reason it's not working any more for me. When on Android I try
to click on the cta button and it doesn't do anything. What could be
causing this? Things appear to be fine on iPhones (so far)

**Comment by Sanjeevsetu** [comment]
Hi @Imageburst 

Could you please contact us here. https://pwa-for-wp.com/contact-us/
