### ISSUE TITLE
Need to added the navigation bar backgound feature.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/pwa-for-wp#874]
Ref ticket: https://magazine3.in/conversation/255469?folder_id=21

Description:-
User wants to change the background color of the navigation bar, and we need to add a new feature.

Here is the screenshot
https://prnt.sc/4NxIhR1uKUwY

**Comment by kumawatvikas** [comment]
Pro Ref : -https://github.com/ahmedkaludi/navigation-bar-for-pwa/commit/44f8be1c15e7264d11d84fcc43e6fe8a84fe5570
