### ISSUE TITLE
Latest Version 1.7.67 Gives Warning: Undefined Variable $force_rememberme 

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/pwa-for-wp#878]
After updating new version 1.7.67 giving "**Warning: Undefined variable $force_rememberme in C:\xampp\htdocs\MyPracto\wp-content\plugins\pwa-for-wp\admin\common-function.php on line 195**"

https://paste.pics/QMO12

reference ticket: https://wordpress.org/support/topic/error-after-update-219/

**Comment by Sanjeevsetu** [comment]
Issue is still valid one.

**Comment by Sdaud1950** [comment]
Ref ticket : https://magazine3.in/conversation/264371?folder_id=29
