### ISSUE TITLE
CTA delayed feature is not working properly in IOS chrome mobile version.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/pwa-for-wp#879]
Ref ticket: https://magazine3.in/conversation/254825?folder_id=21

Description:-
When we set the delay to 5 seconds in the CTA and test on the iOS Chrome mobile version, it's loading with the website.

**Comment by kumawatvikas** [comment]
Pro Ref : https://github.com/ahmedkaludi/call-to-action-for-pwa/commit/7bad5304ae09a9884b293f96fc71dfcc91c43c10
