### ISSUE TITLE
Conflict issue with Polylang plugin

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/pwa-for-wp#880]
Ref ticket:-https://magazine3.in/conversation/248831?folder_id=21

Description:-
When the user selects the start URL in PWA after installing the app in another language, the start URL appears in the main language.

Issue video:-
https://www.dropbox.com/scl/fi/2yeve7vl2lg35372s5vdf/video6084460214378044435.mp4?rlkey=myh3vqru74imjcb7k0wvyahji&dl=0

**Comment by kumawatvikas** [comment]
Ref : https://github.com/ahmedkaludi/multilingual-compatibility-for-pwa/commit/d181b2dc6cf8232446ca5bceaec43ef7459248ee
