### ISSUE TITLE
Add compatibility with wp-multilang

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/pwa-for-wp#881]

**Comment by kumawatvikas** [comment]
Ref:-https://github.com/ahmedkaludi/multilingual-compatibility-for-pwa/commit/0b5474864bba6e4ee99b3baaf5c599f71e867ec5

**Comment by Sanjeevsetu** [comment]
The feature has been released in Addon : Multilingual Compatibility for PWA version 1.6
