### ISSUE TITLE
Custom Add To Home Banner not visible in IOS devices.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/pwa-for-wp#882]
Ref ticket: https://magazine3.in/conversation/258816?folder_id=21

Description:-
When we added the Custom Add to Home Banner, it wasn't visible on iOS devices.

**Comment by Sanjeevsetu** [comment]
We already have this feature in our pro extension call to action for pwa (https://pwa-for-wp.com/extensions/call-to-action-for-pwa/)
