### ISSUE TITLE
PWA: Activation Failed error with wordpress latest update.

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/pwa-for-wp#886]
After every fresh installation of the PWA plugin from the WordPress 'Add Plugin' section, it presents an error. Although the plugin installs without any issues, upon attempting to activate it, it throws an 'Activation Failed' error.

reference video :https://monosnap.com/direct/uzph34DgSFzBRy5jnjvxEbrhNzaWVO

Tested on both Localhost and testing site.

**Comment by Sanjeevsetu** [comment]
This ticket has been pushed in 1.7.69.1
