### ISSUE TITLE
Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in 

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/pwa-for-wp#888]
An error of type E_ERROR was caused in line 560 of the file /home/panel60g/public_html/B-01-Brcomputer.net/wp-content/plugins/pwa-for-wp/admin/common-function.php. Error message: Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in /home/panel60g/public_html/B-01-Brcomputer.net/wp-content/plugins/pwa-for-wp/admin/common-function.php:560
Stack trace:
#0 /home/panel60g/public_html/B-01-Brcomputer.net/wp-content/plugins/pwa-for-wp/admin/common-function.php(560): fwrite(false, 'var swsource="h...')
#1 /home/panel60g/public_html/B-01-Brcomputer.net/wp-content/plugins/pwa-for-wp/service-work/class-init.php(69): pwaforwp_write_a_file('/home/panel60g/...', 'var swsource="h...', NULL)
#2 /home/panel60g/public_html/B-01-Brcomputer.net/wp-content/plugins/pwa-for-wp/admin/common-function.php(591): PWAFORWP_File_Creation_Init->pwaforwp_swr_init(NULL)
#3 /home/panel60g/public_html/B-01-Brcomputer.net/wp-content/plugins/pwa-for-wp/admin/settings.php(63): pwaforwp_required_file_creation()
#4 /home/panel60g/public_html/B-01-Brcomputer.net/wp-includes/class-wp-hook.php(324): pwaforwp_admin_interface_render('')
#5 /home/panel60g/public_html/B-01-Brcomputer.net/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#6 /home/panel60g/public_html/B-01-Brcomputer.net/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /home/panel60g/public_html/B-01-Brcomputer.net/wp-admin/admin.php(259): do_action('toplevel_page_p...')
#8 {main}
  thrown

**Comment by Sanjeevsetu** [comment]
Related #https://github.com/ahmedkaludi/pwa-for-wp/commit/a7919cb29e6f806ee0aaffefc9fd03bc7fbb7353
