### ISSUE TITLE
While clicking the close button on the CTA banner it shows the pop-up to install

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/pwa-for-wp#893]
- [x] While clicking the close button on the CTA banner it shows the pop-up to install
- [x] The option Sticky Banner should be enabled as default if a user activates the extension CTA
- [x] Need to add a note under the option "Show on Desktop" that the banner visibility is enabled on Android/IOS devices by default.
- [x] The option to add a CTA install button using shortcode is missing in the CTA settings

Ref ticket: https://magazine3.in/conversation/272285?folder_id=27

**Comment by kumawatvikas** [comment]
Ref: https://github.com/ahmedkaludi/call-to-action-for-pwa/commit/a9945cedb45a87ea52e9092988f5b6da3d047d3c
