### ISSUE TITLE
CTA is still showing after disabling CTA on desktop.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/pwa-for-wp#898]
CTA is still showing after disabling CTA on desktop.

Ref Ticket:https://magazine3.in/conversation/275336?folder_id=29

**Comment by kumawatvikas** [comment]
Ref : https://github.com/ahmedkaludi/call-to-action-for-pwa/commit/0ab09f4ac0e02858fe601a4be91dea4cf38e2f24

**Comment by Sanjeevsetu** [comment]
The issue has been fixed in CTA pro ext v1.9.8.1
