### ISSUE TITLE
Offline form radio group validation not working

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/pwa-for-wp#900]
Ref ticket: https://magazine3.in/conversation/276628?folder_id=21

Description:-
When we selected the radio group in offline mode, the data was not reflected in the backend.

**Comment by kumawatvikas** [comment]
Ref : - https://github.com/ahmedkaludi/offline-forms-for-pwa-for-wp/commit/77c1b038085581f3269b0dbbb35d755fce962eda

**Comment by akshaywali** [comment]
pushed in offline form for pwa 3.2
