### ISSUE TITLE
Deprecated: Creation of dynamic property is deprecated

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/pwa-for-wp#903]
Deprecated: Creation of dynamic property BUDDYPRESSS_PWAFORWP_Data_EDD_SL_Plugin_Updater::$beta is deprecated in D:\WAMP\www\magazine3\wp-content\plugins\buddypress-for-pwaforwp\updater\EDD_SL_Plugin_Updater.php on line 42

**Comment by akshaywali** [comment]
https://github.com/ahmedkaludi/buddypress-for-pwaforwp/commit/5b8be698b21fc3e6b289982b4556513aa006c40c

**Comment by akshaywali** [comment]
pushed in buddypress for pwa  1.4.3
