### ISSUE TITLE
Fatal error in CTA

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/pwa-for-wp#904]
Trying to access array offset on null in /bitnami/wordpress/wp-content/plugins/call-to-action-for-pwa/admin/admin.php on line 308
PHP Fatal error: Uncaught Error: Call to undefined function pwaforwp_site_url() in /bitnami/wordpress/wp-content/plugins/call-to-action-for-pwa/service/pwaforpw-non-amp-install.php:218

**Comment by akshaywali** [comment]
pushed in call to action for pwa  1.9.9
