### ISSUE TITLE
Option to customize look and text of custom add to home banner

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/pwa-for-wp#91]
https://wordpress.org/support/topic/where-can-i-change-text-of-custom-add-to-home-banner/

**Comment by beingsmart3** [comment]
One More Ref:  https://secure.helpscout.net/conversation/820987728/62502?folderId=1914712

**Comment by yohanmosfr** [comment]
Hello,
Your work is really interesting, bravo.

Regarding this point, I added a little CSS to my code for the button, but impossible to translate into French. Yet I found a .po file, but the text is not in it.
Do you have the opportunity to give us some visibility on this evolution?

Also, I do not know if it's normal or bug related with my site, but I do not have the icon that appears in the PWA window to add to the homepage.

Thank you in advance
Yohan

**Comment by Sanjeevsetu** [comment]
Hi @yohanmosfr,

Yes, we have plan to add text in .po file. Regarding your another issue. 
Plz test your pwa site with google chrome lighthouse (https://developers.google.com/web/tools/lighthouse/) extension and lets know exact issue.?
