### ISSUE TITLE
Navigation bar extension conflict issue

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/pwa-for-wp#910]
When the navigation bar extension is enabled and there is no MENU set (as shown in this screenshot: https://prnt.sc/IXsohQuktFg3), the menu items still appear at the bottom in the PWA, as seen in this screenshot: https://prnt.sc/BoFcZEOHRshp.

Ref Ticket :https://magazine3.in/conversation/279917?folder_id=29

**Comment by kumawatvikas** [comment]
Ref : - https://github.com/ahmedkaludi/navigation-bar-for-pwa/commit/71efac550890ad48ae8fc85921243ab8077fbd2b
