### ISSUE TITLE
Offline form feature not working in IOS device.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/pwa-for-wp#919]
Ref ticket: https://magazine3.in/conversation/294857?folder_id=21

Description:
When we submit the formidable form in offline mode, entires or data are not reflected in the backend, and duplicate entires appear in online mode.

**Comment by akshaywali** [comment]
Ref Commit  :  https://github.com/ahmedkaludi/offline-forms-for-pwa-for-wp/commit/b576c3436421becd290959a2282be5993045fd6f
