### ISSUE TITLE
Large increase server load after last update

### ISSUE THREAD

**Issue by moisb** [ahmedkaludi/pwa-for-wp#92]
As soon as I upgraded to version 1.0.9, the server started issuing alerts of lack of resources.

I started investigating with a terminal log analysis tool (GoAccess) and saw that the files "pwa-amp-sw.js" and "**pwa-sw.js**" were the villains. Each access produced dozens of hits, mainly the "pwa-sw.js" that generated an absurd transfer rate (5GB) in a few hours of analysis:

https://snag.gy/7qe0wV.jpg

**and as I'm sure PWA for WP is the problem:** I deactivated the suspicious plugin and the server immediately returned to normal.

please be more careful when release new updates and if they can find the cause and fix it let me know, please. I liked this plugin

**Comment by Sanjeevsetu** [comment]
Hi @moisb, 

This is a stranger issue. Does previous version work fine for you? We want to debug it. Could you please contact us here http://pwa-for-wp.com/contact-us/.

**Comment by ahmedkaludi** [comment]
@moisb we are unable to re-occur this issue. Please help us see this

**Comment by moisb** [comment]
sorry @ahmedkaludi. I passed all the information I got. I no longer use this plugin on my site.

**Comment by ahmedkaludi** [comment]
@moisb I understand but if you could help us see the problem, then we can solve it for you

**Comment by ahmedkaludi** [comment]
Please write us with more details on https://structured-data-for-wp.com/contact-us/ so that we can **understand** the problem. 

Right now, we see the problem through the screenshot but we don't understand it, it's impossible to solve and issue without understanding it.
