### ISSUE TITLE
R&D related to full screens issue in new Andriod devices.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/pwa-for-wp#920]
Ref ticket: https://magazine3.in/conversation/297515?folder_id=21

Description:-
Full screen not working properly in new andriod devices. 

Here is the device screenshot and issue screenshot:-
https://monosnap.com/direct/tRsFkZuCQpy1k1xvhNuuSIdxhr8XcP
https://monosnap.com/direct/liTSZsVqL8RJY5oZr9Ig9db2XVZX7R

**Comment by Sanjeevsetu** [comment]
This is user specific issue and working find at our end. Need investigation at user end so I am closing it
