### ISSUE TITLE
Nee to connect CTA with add to homescreen in chrome browser.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/pwa-for-wp#924]
Ref ticket: https://magazine3.in/conversation/303657?folder_id=21

Description:-
When we click on the CTA in the Chrome browser, it redirects to the steps banner. We need to connect the CTA to the 'Add to Home Screen' feature that was recently added in the Chrome browser update.

Here is the screenshot 
https://prnt.sc/-5_RXM7L4l8h

**Comment by mezvin** [comment]
@MohammedAkramU7 I can see that this ticket is close. How to have the new feature on my website ?
