### ISSUE TITLE
Fatal Error in offline forms

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/pwa-for-wp#927]
Fatal error: Uncaught Error: Call to undefined function pwaforwp_defaultSettings()
in /var/www/html/eplaportal/wp-content/plugins/offline-forms-for-pwa-for-wp/offline-forms-for-pwa-for-wp.php on line 44

Reference user -: https://magazine3.in/conversation/311106?folder_id=4

**Comment by Sanjeevsetu** [comment]
Commit reference : https://github.com/ahmedkaludi/offline-forms-for-pwa-for-wp/commit/405aab971df00b79a1035e365f095576d507ba1e
