### ISSUE TITLE
Custom Add To Home Banner

### ISSUE THREAD

**Issue by 3900132** [ahmedkaludi/pwa-for-wp#928]
Can the position of the code be adjusted?
There is currently an issue with the display on my website

**Comment by Sanjeevsetu** [comment]
Hi @3900132 

Can you you share more details of the issue?

**Comment by Sanjeevsetu** [comment]
Hi @3900132 

You can raised your ticket through https://pwa-for-wp.com/contact-us/. I am closing it as it does not seem valid issue
