### ISSUE TITLE
Elementor Slider not working

### ISSUE THREAD

**Issue by jokr0815** [ahmedkaludi/pwa-for-wp#93]
Hi,

the elementor slider is showing as a huge blank area - see https://teutonia-grossenlueder.de/amp/ vs. https://teutonia-grossenlueder.de/

Kind regards
Jo

**Comment by jokr0815** [comment]
PS: Link Color is also not good...And had to tweak it by adding custom css - even with !important it is not always green

**Comment by ahmedkaludi** [comment]
Your question is related to AMP, i don't think it has anything to do with the PWA

Plus, the issue is not clear, kindly request for the technical support on http://ampforwp.com/support/ 

Till then the ticket will be closed.
