### ISSUE TITLE
Pushnotifications are not working if PWAforWP is activated

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/pwa-for-wp#930]
Pushnotifications are not working if PWAforWP is activated

Ref ticket: https://magazine3.in/conversation/310841?folder_id=27

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by kumawatvikas** [comment]
There was a conflict with onesingle, it has been solved at user end.
