### ISSUE TITLE
Make a feature to force load the "pwa-non-amp-install" specific parameter URL.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/pwa-for-wp#932]
Ref ticket: https://magazine3.in/conversation/316367?folder_id=21

Description:-
We need to implement a feature to force load the URL with the pwa-non-amp-install parameter in the path.

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by kumawatvikas** [comment]
Ref :- https://github.com/ahmedkaludi/qr-code-for-pwa/commit/a4c24221be534f262a28d2d879e42bc450015ede

**Comment by akshaywali** [comment]
pushed in QR code for pwa 1.6
