### ISSUE TITLE
Minify JS files for production

### ISSUE THREAD

**Issue by Andersang** [ahmedkaludi/pwa-for-wp#933]
Please add the option to utilise minified versions of the javascript files. At the moment, multiple files are not minified in production:

`pwaforwp.min.js` - indicated as minified, but is actually not
`pwaforwp-video.js`
`pwaforwp-download.js`

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Sanjeevsetu** [comment]
Hi @Andersang 

Thanks for reporting it. We will minified it in next updates.
