### ISSUE TITLE
Need to make a option to edit browser banner content.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/pwa-for-wp#934]
Ref ticket: https://magazine3.in/conversation/318150?folder_id=21

Description:
Make a option to edit banner content.

Here is the banner screenshot
https://prnt.sc/Uerq2UtbTEWB

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
