### ISSUE TITLE
Need to add compatibility with Eform in offline forms

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/pwa-for-wp#940]
When we add forms using E-Form and using it offline, it shows server error.

Reference user -: https://magazine3.in/conversation/322385?folder_id=23

**Comment by akshaywali** [comment]
Ref : https://github.com/ahmedkaludi/offline-forms-for-pwa-for-wp/commit/9b0008d473c67589da374e4a1dd3571fce4951b4

**Comment by akshaywali** [comment]
pushed in offline form for wp 3.5
