### ISSUE TITLE
Magazine3 is developing superpwa and ampforwp.com as well

### ISSUE THREAD

**Issue by kochhase** [ahmedkaludi/pwa-for-wp#942]
But what is the difference between the 3 plugins? pwa-for-wp and  superpwa.  superpwa has in the past a lot of bugs in the pro version. And why are you developing 3 Plugins with the same functions? pwa-for-wp, superpwa , ampforwp.com.
I don´t know which one should I take?
thanks for help Henryk

**Comment by ahmedkaludi** [comment]
they are not the same, diff team for diff app. 

kindly email us on team@magazine3.in
