### ISSUE TITLE
Regex in pwaforwp_revert_src() are too generic

### ISSUE THREAD

**Issue by Tabrisrp** [ahmedkaludi/pwa-for-wp#95]
Hi,

The regular expressions used in the function `pwaforwp_revert_src()` are too generic and can cause mismatch and loss of HTML content.

Please update them to be more specific, they will be more efficient and less prone to error.

Even better if you can, don't use output buffering to performs the URL replacement. Instead, add a `apply_filters()` to the original URLs, and then use `add_filter()` to replace them if the CDN option is active.

That will prevent conflict with any other plugin using output buffering.

**Comment by ahmedkaludi** [comment]
https://secure.helpscout.net/conversation/849092807/65515/

**Comment by Sanjeevsetu** [comment]
Hi @Tabrisrp, 

Thanks for the support. Can you give us some example to more specific way. We will appropriate it.

Thanks

**Comment by ahmedkaludi** [comment]
@Sanjeevsetu Let me know if you need help, we can discuss this
