### ISSUE TITLE
add the New Display and orientation options

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/pwa-for-wp#96]
Customer requested: 
“display”: “fullscreen”,
“orientation”: “auto”,

Are these values available? and then implement and test it.

REF: https://wordpress.org/support/topic/helloy/

**Comment by ajeetku** [comment]
**https://github.com/ahmedkaludi/pwa-for-wp/issues/94**

**Comment by ajeetku** [comment]
Pushed in 1.5
